import { afterEach, describe, expect, it, vi } from 'vitest';
import { RoomVideoProgram } from './RoomVideoProgram';

afterEach(() => { vi.restoreAllMocks(); vi.useRealTimers(); });
describe('Preview / Program isolation (unit tests, no hardware)', () => {
  it('renders fixed layout slots in Preview and blocks an incomplete TAKE without changing Program', async () => {
    vi.useFakeTimers();
    const contexts: Array<{ fillRect: ReturnType<typeof vi.fn>; drawImage: ReturnType<typeof vi.fn>; fillText: ReturnType<typeof vi.fn> }> = [];
    vi.spyOn(HTMLCanvasElement.prototype, 'getContext').mockImplementation(() => {
      const context = { fillRect: vi.fn(), drawImage: vi.fn(), fillText: vi.fn() };
      contexts.push(context);
      return context as unknown as CanvasRenderingContext2D;
    });
    Object.defineProperty(HTMLCanvasElement.prototype, 'captureStream', { configurable: true, value: () => ({ getTracks: () => [{ stop: vi.fn() }] }) });
    vi.spyOn(HTMLMediaElement.prototype, 'play').mockResolvedValue();
    vi.spyOn(HTMLMediaElement.prototype, 'pause').mockImplementation(() => undefined);
    vi.spyOn(HTMLMediaElement.prototype, 'readyState', 'get').mockReturnValue(4);
    vi.spyOn(HTMLVideoElement.prototype, 'videoWidth', 'get').mockReturnValue(1280);
    vi.spyOn(HTMLVideoElement.prototype, 'videoHeight', 'get').mockReturnValue(720);
    const source = { getVideoTracks: () => [{ readyState: 'live' }] } as unknown as MediaStream;
    const preview = new RoomVideoProgram(true);
    const program = new RoomVideoProgram();
    await preview.add('A', source); await program.add('A', source);
    program.take({ layout: 'full', sourceIds: ['A'] });
    contexts[0].drawImage.mockClear();
    preview.take({ layout: 'split', sourceIds: ['A'] });
    expect(contexts[0].drawImage).toHaveBeenLastCalledWith(expect.any(HTMLVideoElement), 0, 180, 640, 360);
    expect(contexts[0].fillText).toHaveBeenCalledWith('Source B · à ajouter', 960, 360);
    expect(() => program.take(preview.program)).toThrow('deux sources');
    expect(program.program).toMatchObject({ layout: 'full', sourceIds: ['A'] });
    await preview.add('B', source); await program.add('B', source);
    preview.take({ layout: 'split', sourceIds: ['A', 'B'] });
    expect(contexts[0].drawImage).toHaveBeenLastCalledWith(expect.any(HTMLVideoElement), 640, 180, 640, 360);
    preview.take({ layout: 'pip', sourceIds: ['A', 'B'], pipPosition: { x: 0, y: 0 } });
    expect(contexts[0].drawImage).toHaveBeenLastCalledWith(expect.any(HTMLVideoElement), 0, 0, 384, 216);
    preview.take({ layout: 'pip', sourceIds: ['A', 'B'], pipPosition: { x: 1, y: 1 } });
    expect(contexts[0].drawImage).toHaveBeenLastCalledWith(expect.any(HTMLVideoElement), 896, 504, 384, 216);
    expect(program.program.layout).toBe('full');
    program.take(preview.program);
    expect(contexts[1].drawImage).toHaveBeenLastCalledWith(expect.any(HTMLVideoElement), 896, 504, 384, 216);
    preview.take({ layout: 'grid', sourceIds: ['A', 'B'] });
    expect(contexts[0].drawImage).toHaveBeenLastCalledWith(expect.any(HTMLVideoElement), 640, 0, 640, 360);
    preview.take({ layout: 'split', sourceIds: ['', 'B'] });
    expect(contexts[0].drawImage).toHaveBeenLastCalledWith(expect.any(HTMLVideoElement), 640, 180, 640, 360);
    expect(() => program.take(preview.program)).toThrow('deux sources');
    preview.take({ layout: 'pip', sourceIds: ['A', 'B'], pipPosition: { x: 1, y: 1 }, pipScale: .5 });
    expect(contexts[0].drawImage).toHaveBeenLastCalledWith(expect.any(HTMLVideoElement), 640, 360, 640, 360);
    const free = { layout: 'free' as const, sourceIds: ['A', 'B'], frames: [{ x: 0, y: 0, width: .5, height: 1 }, { x: .7, y: .7, width: .3, height: .3 }], fits: ['cover' as const, 'contain' as const] };
    program.take(free);
    expect(contexts[1].drawImage).toHaveBeenCalledWith(expect.any(HTMLVideoElement), 320, 0, 640, 720, 0, 0, 640, 720);
    free.frames[0].x = .4; free.fits[0] = 'contain';
    expect(program.program.frames?.[0].x).toBe(0);
    expect(program.program.fits?.[0]).toBe('cover');
    const snapshot = program.program; snapshot.frames![0].x = .5;
    expect(program.program.frames?.[0].x).toBe(0);
    preview.dispose(); program.dispose();
    expect(vi.getTimerCount()).toBe(0);
  });
  it('keeps Program stable until TAKE, then stops only its output on disposal', async () => {
    vi.useFakeTimers();
    const outputStop = vi.fn();
    const sourceStop = vi.fn();
    vi.spyOn(HTMLCanvasElement.prototype, 'getContext').mockReturnValue({ fillRect: vi.fn(), drawImage: vi.fn() } as unknown as CanvasRenderingContext2D);
    Object.defineProperty(HTMLCanvasElement.prototype, 'captureStream', { configurable: true, value: () => ({ getTracks: () => [{ stop: outputStop }] }) });
    vi.spyOn(HTMLMediaElement.prototype, 'play').mockResolvedValue();
    vi.spyOn(HTMLMediaElement.prototype, 'pause').mockImplementation(() => undefined);
    const program = new RoomVideoProgram();
    const source = { getTracks: () => [{ stop: sourceStop }] } as unknown as MediaStream;
    await program.add('A', source); await program.add('B', source);
    const preview = { layout: 'full' as const, sourceIds: ['A'] };
    program.take(preview);
    preview.sourceIds[0] = 'B';
    expect(program.program.sourceIds).toEqual(['A']);
    program.take(preview, 500);
    expect(program.program.sourceIds).toEqual(['B']);
    program.dispose(); program.dispose();
    expect(outputStop).toHaveBeenCalledOnce();
    expect(sourceStop).not.toHaveBeenCalled();
    expect(vi.getTimerCount()).toBe(0);
    expect(() => program.take(preview)).toThrow('fermée');
  });
});
