import type { OrbitProfile } from "./types";

/**
 * Five real Meewav profiles calibrated against the supplied globe reference.
 */
export const EXAMPLE_GLOBAL_ORBIT_PROFILES: readonly OrbitProfile[] = [
  {
    id: "gazo",
    name: "Gazo",
    subtitle: "Artiste légendaire",
    imageUrl: "/assets/orbit/legendary-gazo.png",
    gradeLevel: 6,
    angleDeg: 171,
    radialOffsetPx: 0,
    offsetX: 3,
    offsetY: -15,
    scale: 0.88,
    accent: "#805BFF",
  },
  {
    id: "puff",
    name: "Puff",
    subtitle: "Fondateur",
    imageUrl: "/assets/orbit/founder-puff.png",
    angleDeg: 126,
    radialOffsetPx: 0,
    offsetX: -42,
    offsetY: 36,
    scale: 0.89,
    accent: "#805BFF",
  },
  {
    id: "mc-pao",
    name: "MC Pao",
    subtitle: "Investisseur",
    imageUrl: "/assets/orbit/investor-mc-pao.png",
    angleDeg: 57,
    radialOffsetPx: 0,
    offsetX: -89,
    offsetY: 49,
    scale: 0.95,
    accent: "#805BFF",
  },
  {
    id: "nadir",
    name: "Nadir",
    subtitle: "Co-fondateur",
    imageUrl: "/assets/orbit/cofounder-nadir.png",
    angleDeg: 36,
    radialOffsetPx: 0,
    offsetX: -15,
    offsetY: -16,
    scale: 1,
    accent: "#805BFF",
  },
  {
    id: "gims",
    name: "Gims",
    subtitle: "Artiste légendaire",
    imageUrl: "/assets/orbit/legendary-gims.png",
    gradeLevel: 6,
    angleDeg: 340,
    radialOffsetPx: 0,
    offsetX: 5,
    offsetY: -10,
    scale: 1.02,
    accent: "#805BFF",
  },
];
