import type { TremplinGeneratedRosterSeed } from "./rosterTypes";

export const danceRoster = [
  {
    id: "aicha-diop",
    name: "Aïcha Diop",
    image: "/images/tremplin/roster/danse/aicha-diop-hip-hop-saint-denis-v1.webp",
    exactProfession: "Danseuse hip-hop",
    roleId: "danseuse",
    disciplines: ["Danse hip-hop", "Freestyle"],
    styles: ["Hip-hop freestyle", "New style"],
    city: "Saint-Denis",
    region: "Île-de-France",
    stageLabel: "Solo hip-hop en résidence",
    biography: "Aïcha construit un solo très musical autour des changements d'appuis et des ruptures de rythme. Chaque répétition filmée lui permet d'affiner la précision du geste sans perdre l'énergie du freestyle.",
    audioTitle: "Appuis francs",
  },
  {
    id: "malik-doumbia",
    name: "Malik Doumbia",
    image: "/images/tremplin/roster/danse/malik-doumbia-krump-marseille-v1.webp",
    exactProfession: "Danseur krump",
    roleId: "danseur",
    disciplines: ["Krump", "Interprétation scénique"],
    styles: ["Krump", "Danse urbaine"],
    city: "Marseille",
    region: "Provence-Alpes-Côte d'Azur",
    stageLabel: "Création krump en répétition",
    biography: "Malik transforme le stomp, les chest pops et les ruptures du krump en une pièce courte pensée pour la scène. Son travail relie intensité physique, respiration et narration musicale.",
    audioTitle: "Impact brut",
  },
  {
    id: "leonie-marchal",
    name: "Léonie Marchal",
    image: "/images/tremplin/roster/danse/leonie-marchal-contemporary-lyon-v1.webp",
    exactProfession: "Danseuse contemporaine",
    roleId: "danseuse",
    disciplines: ["Danse contemporaine", "Improvisation"],
    styles: ["Contemporain", "Floorwork"],
    city: "Lyon",
    region: "Auvergne-Rhône-Alpes",
    stageLabel: "Pièce contemporaine en recherche",
    biography: "Léonie compose à partir du poids, du sol et de trajectoires très lisibles. Elle développe une pièce où l'improvisation reste encadrée par la structure rythmique de la musique.",
    audioTitle: "Point de gravité",
  },
  {
    id: "ines-navarro",
    name: "Inès Navarro",
    image: "/images/tremplin/roster/danse/ines-navarro-waacking-toulouse-v1.webp",
    exactProfession: "Danseuse waacking",
    roleId: "danseuse",
    disciplines: ["Waacking", "Performance"],
    styles: ["Waacking", "Disco funk"],
    city: "Toulouse",
    region: "Occitanie",
    stageLabel: "Show waacking en construction",
    biography: "Inès travaille la vitesse des bras, les arrêts nets et l'interprétation musicale propres au waacking. Son prochain format mêle freestyle et séquences écrites pour un show de quinze minutes.",
    audioTitle: "Velvet Arms",
  },
  {
    id: "eliott-nguyen",
    name: "Eliott Nguyen",
    image: "/images/tremplin/roster/danse/eliott-nguyen-house-dance-paris-v1.webp",
    exactProfession: "Danseur house",
    roleId: "danseur",
    disciplines: ["House dance", "Freestyle"],
    styles: ["House dance", "Footwork"],
    city: "Paris",
    region: "Île-de-France",
    stageLabel: "Session house filmée en préparation",
    biography: "Eliott construit son vocabulaire autour du jack, du rebond et d'un footwork fluide. Il prépare une session continue où la caméra suit le dialogue entre ses appuis et les variations du morceau.",
    audioTitle: "Jack en continu",
  },
  {
    id: "yara-mensah",
    name: "Yara Mensah",
    image: "/images/tremplin/roster/danse/yara-mensah-afro-dance-bordeaux-v1.webp",
    exactProfession: "Danseuse afro",
    roleId: "danseuse",
    disciplines: ["Afro dance", "Chorégraphie"],
    styles: ["Afro fusion", "Afrobeats"],
    city: "Bordeaux",
    region: "Nouvelle-Aquitaine",
    stageLabel: "Création afro fusion en résidence",
    biography: "Yara relie des appuis puissants, un travail précis du torse et une énergie collective issue des danses afro urbaines. Elle développe actuellement une version solo adaptée aux petites scènes musicales.",
    audioTitle: "Soleil bas",
  },
  {
    id: "yanis-benali",
    name: "Yanis Benali",
    image: "/images/tremplin/roster/danse/yanis-benali-breaking-lille-v1.webp",
    exactProfession: "Danseur breaking",
    roleId: "danseur",
    disciplines: ["Breaking", "Power moves"],
    styles: ["Breaking", "Footwork au sol"],
    city: "Lille",
    region: "Hauts-de-France",
    stageLabel: "Round de breaking en répétition",
    biography: "Yanis alterne footwork, transitions au sol et freezes sans couper la phrase musicale. Son objectif est de transformer un vocabulaire de battle en solo scénique cohérent.",
    audioTitle: "Six Steps",
  },
  {
    id: "dalia-rossi",
    name: "Dalia Rossi",
    image: "/images/tremplin/roster/danse/dalia-rossi-voguing-montpellier-v1.webp",
    exactProfession: "Danseuse voguing",
    roleId: "danseuse",
    disciplines: ["Voguing", "Performance"],
    styles: ["Vogue fem", "Runway"],
    city: "Montpellier",
    region: "Occitanie",
    stageLabel: "Performance voguing en création",
    biography: "Dalia compose avec les lignes, les mains, le runway et les changements de niveau du voguing. Sa pièce rend chaque transition lisible pour conserver la force du mouvement au-delà du format ballroom.",
    audioTitle: "Ligne franche",
  },
  {
    id: "nils-okafor",
    name: "Nils Okafor",
    image: "/images/tremplin/roster/danse/nils-okafor-popping-nantes-v1.webp",
    exactProfession: "Danseur popping",
    roleId: "danseur",
    disciplines: ["Popping", "Animation"],
    styles: ["Popping", "Waving"],
    city: "Nantes",
    region: "Pays de la Loire",
    stageLabel: "Solo popping en précision",
    biography: "Nils développe un solo fondé sur les hits, les isolations et les vagues articulées. Il travaille chaque accent directement sur la production musicale pour éviter l'effet de démonstration technique.",
    audioTitle: "Micro-saccades",
  },
  {
    id: "maeva-laurent",
    name: "Maëva Laurent",
    image: "/images/tremplin/roster/danse/maeva-laurent-dancehall-rennes-v1.webp",
    exactProfession: "Danseuse dancehall",
    roleId: "danseuse",
    disciplines: ["Dancehall", "Chorégraphie"],
    styles: ["Dancehall", "Afro-caribéen"],
    city: "Rennes",
    region: "Bretagne",
    stageLabel: "Show dancehall en répétition",
    biography: "Maëva développe une danse athlétique où les appuis, le bassin et le haut du corps répondent précisément aux percussions. Son show alterne chorégraphie et espaces de freestyle assumés.",
    audioTitle: "Ground Pulse",
  },
  {
    id: "idriss-cohen",
    name: "Idriss Cohen",
    image: "/images/tremplin/roster/danse/idriss-cohen-locking-strasbourg-v1.webp",
    exactProfession: "Danseur locking",
    roleId: "danseur",
    disciplines: ["Locking", "Transmission"],
    styles: ["Locking", "Funk styles"],
    city: "Strasbourg",
    region: "Grand Est",
    stageLabel: "Set funk en préparation",
    biography: "Idriss défend un locking généreux, précis et profondément musical. Il prépare un set où les points, les locks et les changements de direction dialoguent avec un groupe funk en direct.",
    audioTitle: "Stop & Smile",
  },
  {
    id: "clara-bensaid",
    name: "Clara Bensaïd",
    image: "/images/tremplin/roster/danse/clara-bensaid-jazz-nice-v1.webp",
    exactProfession: "Danseuse jazz",
    roleId: "danseuse",
    disciplines: ["Danse jazz", "Interprétation"],
    styles: ["Jazz contemporain", "Modern jazz"],
    city: "Nice",
    region: "Provence-Alpes-Côte d'Azur",
    stageLabel: "Variation jazz en répétition",
    biography: "Clara travaille une danse jazz ample qui conserve la netteté des accents et des directions. Sa nouvelle variation est construite comme un morceau, avec reprises, silences et montée finale.",
    audioTitle: "Cuivres en l'air",
  },
  {
    id: "alba-moreno",
    name: "Alba Moreno",
    image: "/images/tremplin/roster/danse/alba-moreno-flamenco-perpignan-v1.webp",
    exactProfession: "Danseuse flamenco contemporain",
    roleId: "danseuse",
    disciplines: ["Flamenco contemporain", "Chorégraphie"],
    styles: ["Flamenco contemporain", "Danse percussive"],
    city: "Perpignan",
    region: "Occitanie",
    stageLabel: "Solo percussif en résidence",
    biography: "Alba part du compás, du travail des talons et de la tension des bras pour construire une écriture contemporaine. Son solo évite le décor folklorique et place le rythme au premier plan.",
    audioTitle: "Terre battue",
  },
  {
    id: "romain-petrov",
    name: "Romain Petrov",
    image: "/images/tremplin/roster/danse/romain-petrov-contemporary-ballet-grenoble-v1.webp",
    exactProfession: "Danseur de ballet contemporain",
    roleId: "danseur",
    disciplines: ["Ballet contemporain", "Interprétation"],
    styles: ["Néo-classique", "Danse contemporaine"],
    city: "Grenoble",
    region: "Auvergne-Rhône-Alpes",
    stageLabel: "Variation néo-classique en création",
    biography: "Romain utilise sa base classique pour développer une danse plus mobile du torse et des appuis. La variation en cours privilégie l'élan, les suspensions et des atterrissages volontairement visibles.",
    audioTitle: "Ligne de crête",
  },
  {
    id: "selma-kader",
    name: "Selma Kader",
    image: "/images/tremplin/roster/danse/selma-kader-cabaret-reims-v1.webp",
    exactProfession: "Danseuse cabaret & performance",
    roleId: "danseuse",
    disciplines: ["Danse cabaret", "Performance scénique"],
    styles: ["Cabaret contemporain", "Danse théâtrale"],
    city: "Reims",
    region: "Grand Est",
    stageLabel: "Numéro de cabaret en répétition",
    biography: "Selma crée des numéros de cabaret où le mouvement, le regard et le déplacement racontent davantage que le costume. Elle prépare une forme courte pensée pour les scènes musicales et les festivals.",
    audioTitle: "Rideau nuit",
  },
  {
    id: "thomas-akrout",
    name: "Thomas Akrout",
    image: "/images/tremplin/roster/danse/thomas-akrout-choreographer-roubaix-v1.webp",
    exactProfession: "Chorégraphe & danseur",
    roleId: "danseur",
    disciplines: ["Chorégraphie", "Danse contemporaine"],
    styles: ["Écriture chorégraphique", "Performance musicale"],
    city: "Roubaix",
    region: "Hauts-de-France",
    stageLabel: "Création collective en répétition",
    biography: "Thomas dirige la répétition depuis le mouvement et démontre chaque intention avec son propre corps. Sa nouvelle création organise les entrées, les dynamiques et les respirations autour d'une composition originale.",
    audioTitle: "Compte de huit",
  },
] as const satisfies readonly TremplinGeneratedRosterSeed[];
