import type { TremplinGeneratedRosterSeed } from "./rosterTypes";

/**
 * Profils exclusivement pianistes : les scènes montrent toutes un clavier ou
 * un piano réellement joué dans un cadre amateur, local et accessible.
 */
export const pianoRoster = [
  {
    id: "lina-benaissa",
    name: "Lina Benaïssa",
    image: "/images/tremplin/roster/pianistes/lina-benaissa-pianiste-lyon-v1.webp",
    exactProfession: "Pianiste amateur · Néo-soul",
    roleId: "pianiste",
    disciplines: ["Pianiste", "Compositrice"],
    styles: ["Néo-soul", "Chanson contemporaine"],
    city: "Lyon",
    region: "Auvergne-Rhône-Alpes",
    stageLabel: "Premier répertoire solo en répétition",
    biography: "Lina travaille après ses études un répertoire où accords néo-soul et mélodies de chanson se répondent. Elle documente chaque maquette avant de préparer une première session publique dans une petite salle lyonnaise.",
    audioTitle: "Fenêtre ouverte",
  },
  {
    id: "marc-nda",
    name: "Marc N'Da",
    image: "/images/tremplin/roster/pianistes/marc-nda-pianiste-saint-denis-v1.webp",
    exactProfession: "Pianiste amateur · Jazz",
    roleId: "pianiste",
    disciplines: ["Pianiste", "Improvisateur"],
    styles: ["Jazz moderne", "Soul instrumentale"],
    city: "Saint-Denis",
    region: "Île-de-France",
    stageLabel: "Trio amateur en construction",
    biography: "Marc répète le soir dans un centre culturel de quartier. Il développe un jeu sobre, très attentif au silence, et cherche une rythmique locale pour transformer ses esquisses en premier set de trente minutes.",
    audioTitle: "Dernier métro",
  },
  {
    id: "mei-lin-roche",
    name: "Mei-Lin Roche",
    image: "/images/tremplin/roster/pianistes/mei-lin-roche-pianiste-marseille-v1.webp",
    exactProfession: "Pianiste amateur · Ambient",
    roleId: "pianiste",
    disciplines: ["Pianiste", "Compositrice"],
    styles: ["Ambient", "Dream pop instrumentale"],
    city: "Marseille",
    region: "Provence-Alpes-Côte d'Azur",
    stageLabel: "Carnet de pièces courtes à domicile",
    biography: "Mei-Lin compose chez elle des miniatures au piano numérique, enregistrées en une prise pour conserver les bruits du lieu. Son premier objectif est une série de cinq vidéos simples tournées à la lumière naturelle.",
    audioTitle: "Balcon nord",
  },
  {
    id: "lucas-vernay",
    name: "Lucas Vernay",
    image: "/images/tremplin/roster/pianistes/lucas-vernay-pianiste-lille-v1.webp",
    exactProfession: "Pianiste amateur · Néo-classique",
    roleId: "pianiste",
    disciplines: ["Pianiste", "Compositeur"],
    styles: ["Néo-classique", "Minimalisme"],
    city: "Lille",
    region: "Hauts-de-France",
    stageLabel: "Cycle pour piano en apprentissage",
    biography: "Lucas partage son temps entre son travail et une salle municipale où il affine six pièces minimalistes. Il avance lentement, conserve toutes ses versions et prépare une première écoute devant un petit comité.",
    audioTitle: "Craie sur verre",
  },
  {
    id: "nadia-koffi",
    name: "Nadia Koffi",
    image: "/images/tremplin/roster/pianistes/nadia-koffi-pianiste-nantes-v1.webp",
    exactProfession: "Pianiste amateur · Gospel & soul",
    roleId: "pianiste",
    disciplines: ["Pianiste", "Accompagnatrice"],
    styles: ["Gospel", "Soul"],
    city: "Nantes",
    region: "Pays de la Loire",
    stageLabel: "Accompagnement de chœur associatif",
    biography: "Nadia accompagne bénévolement une chorale de quartier et réarrange les morceaux pour des voix de niveaux très différents. Elle prépare un carnet d'accompagnements souples et faciles à reprendre par d'autres groupes.",
    audioTitle: "Voix communes",
  },
  {
    id: "arun-mehta",
    name: "Arun Mehta",
    image: "/images/tremplin/roster/pianistes/arun-mehta-pianiste-toulouse-v1.webp",
    exactProfession: "Pianiste amateur · Musique à l'image",
    roleId: "pianiste",
    disciplines: ["Pianiste", "Compositeur à l'image"],
    styles: ["Musique de film", "Piano minimal"],
    city: "Toulouse",
    region: "Occitanie",
    stageLabel: "Première bande originale en maquette",
    biography: "Arun écrit sur un piano abordable dans sa chambre et apprend à construire des thèmes assez simples pour servir le récit. Il termine la musique d'un court métrage étudiant de huit minutes.",
    audioTitle: "Plan séquence 03",
  },
  {
    id: "claire-hartmann",
    name: "Claire Hartmann",
    image: "/images/tremplin/roster/pianistes/claire-hartmann-pianiste-strasbourg-v1.webp",
    exactProfession: "Pianiste amateur · Boogie-woogie",
    roleId: "pianiste",
    disciplines: ["Pianiste", "Interprète"],
    styles: ["Boogie-woogie", "Blues"],
    city: "Strasbourg",
    region: "Grand Est",
    stageLabel: "Set associatif en préparation",
    biography: "Claire a repris le piano après plusieurs années et travaille un set énergique pour les événements de son association. Son défi est de tenir vingt-cinq minutes sans perdre le rebond ni la précision du tempo.",
    audioTitle: "Quai des bateliers",
  },
  {
    id: "noa-breuil",
    name: "Noa Breuil",
    image: "/images/tremplin/roster/pianistes/noa-breuil-pianiste-bordeaux-v1.webp",
    exactProfession: "Pianiste amateur · Chanson",
    roleId: "pianiste",
    disciplines: ["Pianiste", "Arrangeur"],
    styles: ["Chanson contemporaine", "Pop acoustique"],
    city: "Bordeaux",
    region: "Nouvelle-Aquitaine",
    stageLabel: "Arrangements pour un premier duo",
    biography: "Noa transforme des chansons écrites à la guitare en arrangements de piano dépouillés. Les répétitions se font dans un petit box loué à l'heure, avec une priorité donnée à la respiration de la voix.",
    audioTitle: "Entre deux quais",
  },
  {
    id: "maya-diallo",
    name: "Maya Diallo",
    image: "/images/tremplin/roster/pianistes/maya-diallo-pianiste-rennes-v1.webp",
    exactProfession: "Pianiste amateur · Pop",
    roleId: "pianiste",
    disciplines: ["Pianiste", "Arrangeuse"],
    styles: ["Pop", "R&B acoustique"],
    city: "Rennes",
    region: "Bretagne",
    stageLabel: "Répertoire pop au centre jeunesse",
    biography: "Maya réarrange au piano les titres qu'elle aime pour comprendre l'harmonie et trouver sa propre couleur. Elle prépare trois reprises et une composition pour la prochaine scène ouverte de son quartier.",
    audioTitle: "Accords du matin",
  },
  {
    id: "samir-voss",
    name: "Samir Voss",
    image: "/images/tremplin/roster/pianistes/samir-voss-pianiste-grenoble-v1.webp",
    exactProfession: "Pianiste amateur · Minimal ambient",
    roleId: "pianiste",
    disciplines: ["Pianiste", "Compositeur"],
    styles: ["Minimal ambient", "Piano préparé"],
    city: "Grenoble",
    region: "Auvergne-Rhône-Alpes",
    stageLabel: "Session intimiste en préparation",
    biography: "Samir compose des motifs très courts dans un studio partagé et les fait évoluer par petites variations. Il souhaite enregistrer une session continue qui conserve les respirations et les imperfections du piano.",
    audioTitle: "Neige basse",
  },
  {
    id: "clement-said",
    name: "Clément Saïd",
    image: "/images/tremplin/roster/pianistes/clement-said-pianiste-nice-v1.webp",
    exactProfession: "Pianiste amateur · Latin jazz",
    roleId: "pianiste",
    disciplines: ["Pianiste", "Arrangeur"],
    styles: ["Latin jazz", "Jazz méditerranéen"],
    city: "Nice",
    region: "Provence-Alpes-Côte d'Azur",
    stageLabel: "Premier set de scène ouverte",
    biography: "Clément prépare dans une salle de quartier un set mêlant montunos, jazz et mélodies méditerranéennes. Il travaille dix minutes par dix minutes pour arriver à un premier concert simple, fluide et bien documenté.",
    audioTitle: "Matin sur le port",
  },
] as const satisfies readonly TremplinGeneratedRosterSeed[];
