import type { TremplinGeneratedRosterSeed } from "./rosterTypes";

export const soundImageRoster = [
  {
    id: "maelle-dossou",
    name: "Maëlle Dossou",
    image: "/images/tremplin/roster/son-image/maelle-dossou-son-live-lyon-v1.webp",
    exactProfession: "Ingénieure du son live",
    roleId: "ingenieur-son",
    disciplines: ["Sonorisation live", "Prise de son de concert"],
    styles: ["Concert", "Session live"],
    city: "Lyon",
    region: "Auvergne-Rhône-Alpes",
    stageLabel: "Balance façade en conditions réelles",
    biography: "Maëlle prépare les balances, construit le plan de fréquences et garde chaque voix lisible sans écraser l'énergie du groupe. Elle documente ses réglages pour assurer un son constant de la petite salle au festival.",
    audioTitle: "Balance à 21 h 10",
  },
  {
    id: "tao-legrand",
    name: "Tao Legrand",
    image: "/images/tremplin/roster/son-image/tao-legrand-mixage-paris-v1.webp",
    exactProfession: "Ingénieur mixage",
    roleId: "ingenieur-son",
    disciplines: ["Mixage musical", "Équilibre tonal"],
    styles: ["Soul alternative", "Pop organique"],
    city: "Paris",
    region: "Île-de-France",
    stageLabel: "Album en phase de mixage",
    biography: "Tao construit des mixes précis où la dynamique reste vivante et où chaque arrangement conserve sa place. Son approche associe écoute critique, automation sobre et traitements analogiques choisis pour le morceau.",
    audioTitle: "Fenêtre centrale",
  },
  {
    id: "samira-ait-mansour",
    name: "Samira Aït-Mansour",
    image: "/images/tremplin/roster/son-image/samira-ait-mansour-mastering-marseille-v1.webp",
    exactProfession: "Ingénieure mastering",
    roleId: "ingenieur-son",
    disciplines: ["Mastering musical", "Contrôle de diffusion"],
    styles: ["Album", "Vinyle & streaming"],
    city: "Marseille",
    region: "Provence-Alpes-Côte d'Azur",
    stageLabel: "Master d'album en validation",
    biography: "Samira finalise les projets avec une attention particulière portée à la cohérence entre les titres, à la profondeur et aux écarts de dynamique. Elle vérifie chaque master sur plusieurs systèmes avant la livraison.",
    audioTitle: "Dernier passage",
  },
  {
    id: "mira-kannan",
    name: "Mira Kannan",
    image: "/images/tremplin/roster/son-image/mira-kannan-field-recording-nantes-v1.webp",
    exactProfession: "Sound designer — field recording",
    roleId: "sound-designer",
    disciplines: ["Prise de son de terrain", "Création de textures"],
    styles: ["Ambient", "Paysage sonore"],
    city: "Nantes",
    region: "Pays de la Loire",
    stageLabel: "Banque de sons naturels en collecte",
    biography: "Mira enregistre des matières naturelles, des résonances urbaines et des détails presque imperceptibles pour créer des bibliothèques sonores originales. Chaque prise est ensuite nettoyée, classée et transformée sans perdre sa texture.",
    audioTitle: "Roselière au matin",
  },
  {
    id: "nassim-khoury",
    name: "Nassim Khoury",
    image: "/images/tremplin/roster/son-image/nassim-khoury-sound-design-toulouse-v1.webp",
    exactProfession: "Sound designer — synthèse & foley",
    roleId: "sound-designer",
    disciplines: ["Synthèse modulaire", "Foley musical"],
    styles: ["Électronique texturale", "Expérimental"],
    city: "Toulouse",
    region: "Occitanie",
    stageLabel: "Identité sonore en prototypage",
    biography: "Nassim combine objets acoustiques, gestes de foley et synthèse modulaire pour fabriquer des sons impossibles à trouver dans une banque standard. Il privilégie des sources enregistrées maison et des transformations entièrement traçables.",
    audioTitle: "Métal souple",
  },
  {
    id: "elodie-saint-clair",
    name: "Élodie Saint-Clair",
    image: "/images/tremplin/roster/son-image/elodie-saint-clair-realisatrice-clip-lille-v1.webp",
    exactProfession: "Réalisatrice de clips",
    roleId: "videaste-clipper",
    disciplines: ["Réalisation de clips", "Direction visuelle"],
    styles: ["Clip narratif", "Performance filmée"],
    city: "Lille",
    region: "Hauts-de-France",
    stageLabel: "Clip en préparation de tournage",
    biography: "Élodie transforme l'intention d'un morceau en découpage, axes caméra et direction de lumière avant l'arrivée de l'artiste sur le plateau. Ses clips privilégient une idée visuelle forte et un tournage réalisable avec l'équipe annoncée.",
    audioTitle: "Plan séquence violet",
  },
  {
    id: "martin-vasseur",
    name: "Martin Vasseur",
    image: "/images/tremplin/roster/son-image/martin-vasseur-cinematographe-bordeaux-v1.webp",
    exactProfession: "Chef opérateur & vidéaste",
    roleId: "videaste-clipper",
    disciplines: ["Image cinéma", "Mouvement caméra"],
    styles: ["Clip urbain", "Prise de vue mobile"],
    city: "Bordeaux",
    region: "Nouvelle-Aquitaine",
    stageLabel: "Séquence extérieure au gimbal",
    biography: "Martin conçoit les mouvements caméra et les choix d'optique qui donnent un rythme visuel au morceau. Il travaille en lumière légère pour conserver des tournages mobiles sans sacrifier la stabilité ni la qualité d'image.",
    audioTitle: "Quai bleu",
  },
  {
    id: "linh-moreau",
    name: "Linh Moreau",
    image: "/images/tremplin/roster/son-image/linh-moreau-etalonnage-montpellier-v1.webp",
    exactProfession: "Étalonneuse & réalisatrice de clips",
    roleId: "videaste-clipper",
    disciplines: ["Étalonnage", "Finition de clips"],
    styles: ["Image cinématographique", "Live session"],
    city: "Montpellier",
    region: "Occitanie",
    stageLabel: "Clip en finition couleur",
    biography: "Linh relie le tournage et la postproduction pour garantir une image cohérente de la caméra au master final. Elle construit des palettes sobres, protège les carnations et harmonise les plans sans masquer la matière originale.",
    audioTitle: "Noirs indigo",
  },
  {
    id: "atelier-sillage",
    name: "Atelier Sillage",
    image: "/images/tremplin/roster/son-image/atelier-sillage-studio-rennes-v1.webp",
    exactProfession: "Studio d'enregistrement indépendant",
    roleId: "studio-enregistrement",
    disciplines: ["Enregistrement en studio", "Accueil de sessions"],
    styles: ["Prise live", "Production acoustique"],
    city: "Rennes",
    region: "Bretagne",
    stageLabel: "Plateau prêt pour une nouvelle session",
    biography: "Atelier Sillage réunit une régie, un grand plateau et une équipe technique capable d'accueillir aussi bien une voix seule qu'un ensemble complet. Le studio prépare les plans de micros, les lignes et le suivi de session avant chaque prise.",
    audioTitle: "Room A — prise témoin",
  },
] as const satisfies readonly TremplinGeneratedRosterSeed[];
