import type { TremplinGeneratedRosterSeed } from "./rosterTypes";

export const supportRoster = [
  {
    id: "mina-diallo-coach-vocal",
    name: "Mina Diallo",
    image: "/images/tremplin/roster/accompagnement/coach-vocal-mina-diallo.webp",
    exactProfession: "Coach vocale — respiration & soutien",
    roleId: "coach-vocal",
    disciplines: ["Technique vocale", "Respiration"],
    styles: ["R&B", "Néo-soul"],
    city: "Paris",
    region: "Île-de-France",
    stageLabel: "Programme voix en séance",
    biography:
      "Mina accompagne les voix R&B et néo-soul sur le souffle, l'endurance et la stabilité des prises. Ses séances alternent exercices courts, écoute active et corrections directement applicables au studio.",
    audioTitle: "Souffle stable",
  },
  {
    id: "julien-mori-coach-vocal",
    name: "Julien Mori",
    image: "/images/tremplin/roster/accompagnement/coach-vocal-julien-mori.webp",
    exactProfession: "Coach vocal — technique & résonance",
    roleId: "coach-vocal",
    disciplines: ["Placement vocal", "Résonance"],
    styles: ["Pop", "Indie pop"],
    city: "Lyon",
    region: "Auvergne-Rhône-Alpes",
    stageLabel: "Cycle de placement vocal",
    biography:
      "Julien aide les chanteurs pop à trouver un placement fiable sans rigidifier l'interprétation. Il travaille la résonance, les passages de registre et la récupération entre répétitions.",
    audioTitle: "Résonance claire",
  },
  {
    id: "nadia-bensaid-coach-vocal",
    name: "Nadia Bensaïd",
    image: "/images/tremplin/roster/accompagnement/coach-vocal-nadia-bensaid.webp",
    exactProfession: "Coach vocale — diction & phrasé",
    roleId: "coach-vocal",
    disciplines: ["Diction", "Interprétation"],
    styles: ["Rap mélodique", "Soul"],
    city: "Toulouse",
    region: "Occitanie",
    stageLabel: "Atelier diction en studio",
    biography:
      "Nadia affine la diction et le phrasé des artistes qui naviguent entre chant et rap mélodique. Elle part du texte, replace les respirations et préserve les particularités de chaque voix.",
    audioTitle: "Phrasé vivant",
  },
  {
    id: "gabriel-renard-coach-vocal",
    name: "Gabriel Renard",
    image: "/images/tremplin/roster/accompagnement/coach-vocal-gabriel-renard.webp",
    exactProfession: "Coach vocal — placement & interprétation",
    roleId: "coach-vocal",
    disciplines: ["Placement vocal", "Préparation scénique"],
    styles: ["Chanson", "Pop orchestrale"],
    city: "Strasbourg",
    region: "Grand Est",
    stageLabel: "Préparation voix avant scène",
    biography:
      "Gabriel prépare les voix de chanson et de pop orchestrale aux exigences du live. Son suivi relie placement, articulation et intention pour garder une interprétation lisible sur toute la durée d'un set.",
    audioTitle: "Voix en mouvement",
  },
  {
    id: "malik-sissoko-management",
    name: "Malik Sissoko",
    image: "/images/tremplin/roster/accompagnement/manager-malik-sissoko.webp",
    exactProfession: "Manager d'artistes — tournée & développement",
    roleId: "management",
    disciplines: ["Management d'artistes", "Coordination de tournée"],
    styles: ["Rap", "R&B"],
    city: "Marseille",
    region: "Provence-Alpes-Côte d'Azur",
    stageLabel: "Tournée nationale en préparation",
    biography:
      "Malik structure le développement d'artistes rap et R&B entre stratégie de lancement, partenaires et calendrier de tournée. Il privilégie des étapes réalistes et une équipe resserrée autour de chaque projet.",
    audioTitle: "Feuille de route",
  },
  {
    id: "priya-mehta-management",
    name: "Priya Mehta",
    image: "/images/tremplin/roster/accompagnement/manager-priya-mehta.webp",
    exactProfession: "Manageuse d'artistes — stratégie de carrière",
    roleId: "management",
    disciplines: ["Stratégie de carrière", "Développement de projet"],
    styles: ["Indie folk", "Chanson"],
    city: "Nantes",
    region: "Pays de la Loire",
    stageLabel: "Plan de développement en atelier",
    biography:
      "Priya accompagne des projets indie folk et chanson dans leurs choix de répertoire, d'image et de partenaires. Chaque feuille de route relie objectifs artistiques, rythme de sortie et capacité réelle de production.",
    audioTitle: "Cap commun",
  },
  {
    id: "claire-vasseur-management",
    name: "Claire Vasseur",
    image: "/images/tremplin/roster/accompagnement/manager-claire-vasseur.webp",
    exactProfession: "Manageuse d'artistes — sorties & live",
    roleId: "management",
    disciplines: ["Management de groupe", "Production live"],
    styles: ["Rock indépendant", "Post-punk"],
    city: "Bordeaux",
    region: "Nouvelle-Aquitaine",
    stageLabel: "Sortie d'EP et dates en montage",
    biography:
      "Claire coordonne la sortie et le développement live de groupes indépendants. Elle transforme les ambitions du collectif en priorités concrètes, de la résidence scénique jusqu'aux premières dates hors région.",
    audioTitle: "Calendrier ouvert",
  },
  {
    id: "noe-mercier-management",
    name: "Noé Mercier",
    image: "/images/tremplin/roster/accompagnement/manager-noe-mercier.webp",
    exactProfession: "Manager d'artistes — coordination de tournée",
    roleId: "management",
    disciplines: ["Coordination de tournée", "Accompagnement d'artistes"],
    styles: ["Électro-pop", "Rap alternatif"],
    city: "Lille",
    region: "Hauts-de-France",
    stageLabel: "Préproduction live en cours",
    biography:
      "Noé sécurise les liens entre artistes, salles et équipes techniques avant chaque déplacement. Son approche combine anticipation logistique, présence backstage et décisions rapides sans empiéter sur la direction artistique.",
    audioTitle: "Avant l'ouverture",
  },
  {
    id: "sillage-ar-label",
    name: "Sillage A&R",
    image: "/images/tremplin/roster/accompagnement/label-sillage-ar.webp",
    exactProfession: "Équipe A&R — repérage & développement",
    roleId: "label",
    disciplines: ["A&R", "Développement artistique"],
    styles: ["R&B", "Pop urbaine"],
    city: "Paris",
    region: "Île-de-France",
    stageLabel: "Session d'écoute éditoriale",
    biography:
      "Sillage réunit trois profils complémentaires pour écouter les démos, formuler un retour exploitable et construire une trajectoire de développement. L'équipe distingue le potentiel d'un titre de la solidité globale du projet.",
    audioTitle: "Écoute croisée",
  },
  {
    id: "atelier-phare-label",
    name: "Atelier Phare",
    image: "/images/tremplin/roster/accompagnement/label-atelier-phare.webp",
    exactProfession: "Label indépendant — direction artistique",
    roleId: "label",
    disciplines: ["Direction artistique", "Production phonographique"],
    styles: ["Soul", "Méditerranéen"],
    city: "Marseille",
    region: "Provence-Alpes-Côte d'Azur",
    stageLabel: "Sélection de maquettes en cours",
    biography:
      "Atelier Phare développe des projets soul et méditerranéens avec une attention égale au son, au récit et au rythme de sortie. Le label avance par sessions d'écoute courtes et décisions documentées.",
    audioTitle: "Maquette numéro trois",
  },
  {
    id: "fenetre-nord-label",
    name: "Fenêtre Nord",
    image: "/images/tremplin/roster/accompagnement/label-fenetre-nord.webp",
    exactProfession: "Équipe A&R — sessions & développement",
    roleId: "label",
    disciplines: ["A&R", "Suivi de sessions"],
    styles: ["Indie pop", "Chanson alternative"],
    city: "Rennes",
    region: "Bretagne",
    stageLabel: "Live session en évaluation",
    biography:
      "Fenêtre Nord suit les artistes depuis les premières sessions jusqu'au choix d'un format de sortie. Son trio A&R croise qualité d'écriture, identité sonore et capacité du projet à tenir sur scène.",
    audioTitle: "Derrière la vitre",
  },
  {
    id: "maelle-zhou-organisation-scenique",
    name: "Maëlle Zhou",
    image: "/images/tremplin/roster/accompagnement/regie-maelle-zhou.webp",
    exactProfession: "Régisseuse générale — coordination scénique",
    roleId: "organisation-scenique",
    disciplines: ["Régie générale", "Coordination scénique"],
    styles: ["Musiques actuelles", "Concert en salle"],
    city: "Montpellier",
    region: "Occitanie",
    stageLabel: "Montage plateau avant balances",
    biography:
      "Maëlle coordonne les équipes, les accès et les séquences techniques avant l'arrivée des artistes. Elle transforme la conduite du concert en repères simples pour que chacun sache quand et comment intervenir.",
    audioTitle: "Top plateau",
  },
  {
    id: "moussa-toure-organisation-scenique",
    name: "Moussa Touré",
    image: "/images/tremplin/roster/accompagnement/production-moussa-toure.webp",
    exactProfession: "Directeur de production — technique live",
    roleId: "organisation-scenique",
    disciplines: ["Direction de production", "Technique live"],
    styles: ["Grandes scènes", "Tournée"],
    city: "Saint-Denis",
    region: "Île-de-France",
    stageLabel: "Préparation technique du concert",
    biography:
      "Moussa pilote les moyens humains et techniques des productions live de grande jauge. Il arbitre les contraintes de plateau avec les régisseurs spécialisés tout en maintenant la sécurité et le calendrier de montage.",
    audioTitle: "Structure prête",
  },
  {
    id: "anne-laure-perrin-organisation-scenique",
    name: "Anne-Laure Perrin",
    image: "/images/tremplin/roster/accompagnement/festival-anne-laure-perrin.webp",
    exactProfession: "Coordinatrice de festival — production scénique",
    roleId: "organisation-scenique",
    disciplines: ["Coordination de festival", "Production scénique"],
    styles: ["Festival", "Musiques actuelles"],
    city: "Clermont-Ferrand",
    region: "Auvergne-Rhône-Alpes",
    stageLabel: "Visite technique avant ouverture",
    biography:
      "Anne-Laure organise les circulations, les équipes et les temps de montage d'un site festivalier. Son travail relie accueil des artistes, contraintes du terrain et continuité de service jusqu'à l'ouverture au public.",
    audioTitle: "Site en ordre",
  },
] as const satisfies readonly TremplinGeneratedRosterSeed[];
