import type { MarketProduct } from "./marketDemoData";

type ExpansionSeed = {
  id: string;
  category: MarketProduct["category"];
  brand: string;
  model: string;
  title: string;
  description: string;
  imageUrl: string;
  price: number;
  sellerId: string;
  locationId: string;
  ratingScore?: number;
  ratingCount?: number;
  conditionLabel?: string;
  badge?: string;
  featured?: boolean;
};

type RentalExpansionSeed = ExpansionSeed & {
  rental: NonNullable<MarketProduct["rental"]>;
};

type ServiceExpansionSeed = ExpansionSeed & {
  service: NonNullable<MarketProduct["service"]>;
};

const actionOnlyCart = (): MarketProduct["cart"] => ({
  eligible: false,
  quantity: 0,
  maxQuantity: 0,
});

function createRentalProduct(seed: RentalExpansionSeed): MarketProduct {
  return {
    id: seed.id,
    slug: seed.id,
    pillarId: "rental",
    category: seed.category,
    brand: seed.brand,
    model: seed.model,
    title: seed.title,
    description: seed.description,
    imageUrl: seed.imageUrl,
    imageAlt: `${seed.title}, disponible à la location sur Meewav`,
    condition: "excellent",
    conditionLabel: seed.conditionLabel ?? "Parc vérifié · Prêt à louer",
    price: { amount: seed.price, currency: "EUR", unit: "day" },
    sellerId: seed.sellerId,
    locationId: seed.locationId,
    rating: { score: seed.ratingScore ?? 4.8, count: seed.ratingCount ?? 48 },
    favorite: false,
    cart: actionOnlyCart(),
    rental: seed.rental,
    service: null,
    collective: null,
    featured: seed.featured ?? false,
    ...(seed.badge ? { badge: seed.badge } : {}),
  };
}

function createServiceProduct(seed: ServiceExpansionSeed): MarketProduct {
  return {
    id: seed.id,
    slug: seed.id,
    pillarId: "services",
    category: seed.category,
    brand: seed.brand,
    model: seed.model,
    title: seed.title,
    description: seed.description,
    imageUrl: seed.imageUrl,
    imageAlt: `${seed.title}, prestation proposée sur Meewav`,
    condition: "new",
    conditionLabel: seed.conditionLabel ?? seed.service.deliveryLabel,
    price: { amount: seed.price, currency: "EUR", unit: "item" },
    sellerId: seed.sellerId,
    locationId: seed.locationId,
    rating: { score: seed.ratingScore ?? 4.9, count: seed.ratingCount ?? 36 },
    favorite: false,
    cart: actionOnlyCart(),
    rental: null,
    service: seed.service,
    collective: null,
    featured: seed.featured ?? false,
    ...(seed.badge ? { badge: seed.badge } : {}),
  };
}

const rentalExpansionSeeds: RentalExpansionSeed[] = [
  {
    id: "exp-rental-moog-sub37-strasbourg",
    category: "Synthétiseurs",
    brand: "Moog",
    model: "Subsequent 37",
    title: "Moog Subsequent 37 · Flight case",
    description: "Analogique calibré avant chaque départ, livré avec flight case, housse pluie et câbles MIDI.",
    imageUrl: "/images/market/moog-subsequent-37.jpg",
    price: 45,
    sellerId: "modular-corner",
    locationId: "strasbourg-krutenau",
    badge: "Réservation instantanée",
    featured: true,
    ratingScore: 4.9,
    ratingCount: 127,
    rental: { dailyPrice: 45, weekendPrice: 104, weeklyPrice: 235, deposit: 850, minimumDays: 1, availableFrom: "2026-07-19", instantBook: true },
  },
  {
    id: "exp-rental-arturia-minifreak-rennes",
    category: "Synthétiseurs",
    brand: "Arturia",
    model: "MiniFreak",
    title: "Arturia MiniFreak · Pack résidence",
    description: "Synthé hybride compact avec alimentation, housse et banque de presets prête pour une résidence.",
    imageUrl: "/images/market/arturia-minifreak.jpg",
    price: 24,
    sellerId: "noemie-sound",
    locationId: "rennes-centre",
    ratingCount: 74,
    rental: { dailyPrice: 24, weekendPrice: 56, weeklyPrice: 126, deposit: 420, minimumDays: 1, availableFrom: "2026-07-20", instantBook: true },
  },
  {
    id: "exp-rental-korg-minilogue-montpellier",
    category: "Synthétiseurs",
    brand: "Korg",
    model: "Minilogue XD",
    title: "Korg Minilogue XD · Set live",
    description: "Polyphonique quatre voix contrôlé en atelier, avec pédale sustain et stand compact.",
    imageUrl: "/images/market/korg-minilogue-xd.jpg",
    price: 26,
    sellerId: "synth-district",
    locationId: "montpellier-beaux-arts",
    badge: "Stand inclus",
    ratingCount: 93,
    rental: { dailyPrice: 26, weekendPrice: 60, weeklyPrice: 136, deposit: 450, minimumDays: 1, availableFrom: "2026-07-22", instantBook: true },
  },
  {
    id: "exp-rental-nord-stage-grenoble",
    category: "Synthétiseurs",
    brand: "Nord",
    model: "Stage 4 73",
    title: "Nord Stage 4 73 · Pack tournée",
    description: "Clavier de scène avec flight case à roulettes, pédalier triple et stand renforcé.",
    imageUrl: "/images/market/nord-stage-4.jpg",
    price: 92,
    sellerId: "atlas-audio",
    locationId: "grenoble-bouchayer",
    conditionLabel: "Parc tournée · Révisé",
    badge: "Livraison locale",
    featured: true,
    ratingScore: 5,
    ratingCount: 58,
    rental: { dailyPrice: 92, weekendPrice: 218, weeklyPrice: 475, deposit: 1900, minimumDays: 2, availableFrom: "2026-07-24", instantBook: false },
  },
  {
    id: "exp-rental-astra-sampler-angers",
    category: "Synthétiseurs",
    brand: "Astra Audio",
    model: "Graphite 16",
    title: "Astra Graphite 16 · Sampler autonome",
    description: "Station de production autonome avec 16 pads, SSD de projets vierge et carte SD de secours.",
    imageUrl: "/images/market/sampler-workstation-graphite-v1.webp",
    price: 39,
    sellerId: "modular-corner",
    locationId: "angers-doutre",
    badge: "Nouveau au parc",
    ratingCount: 21,
    rental: { dailyPrice: 39, weekendPrice: 90, weeklyPrice: 205, deposit: 700, minimumDays: 1, availableFrom: "2026-07-21", instantBook: true },
  },
  {
    id: "exp-rental-apollo-twin-dijon",
    category: "Interfaces audio",
    brand: "Universal Audio",
    model: "Apollo Twin X Duo",
    title: "Apollo Twin X Duo · Kit mobile",
    description: "Interface Thunderbolt avec alimentation, adaptateurs et valise rigide pour sessions nomades.",
    imageUrl: "/images/market/apollo-twin-x.jpg",
    price: 31,
    sellerId: "atlas-audio",
    locationId: "dijon-centre",
    ratingScore: 4.9,
    ratingCount: 116,
    rental: { dailyPrice: 31, weekendPrice: 72, weeklyPrice: 159, deposit: 500, minimumDays: 1, availableFrom: "2026-07-19", instantBook: true },
  },
  {
    id: "exp-rental-audient-id14-nice",
    category: "Interfaces audio",
    brand: "Audient",
    model: "iD14 MKII",
    title: "Audient iD14 MKII · Duo nomade",
    description: "Interface compacte avec deux préamplis, hub USB-C et câblage complet pour enregistrer partout.",
    imageUrl: "/images/market/audient-id14.jpg",
    price: 16,
    sellerId: "waveform-studio",
    locationId: "nice-port",
    ratingCount: 69,
    rental: { dailyPrice: 16, weekendPrice: 37, weeklyPrice: 82, deposit: 240, minimumDays: 2, availableFrom: "2026-07-23", instantBook: true },
  },
  {
    id: "exp-rental-focusrite-scarlett-rouen",
    category: "Interfaces audio",
    brand: "Focusrite",
    model: "Scarlett 2i2 4th Gen",
    title: "Scarlett 2i2 · Pack voix mobile",
    description: "Interface, micro statique, pied compact et casque réunis dans une mallette prête à partir.",
    imageUrl: "/images/market/focusrite-scarlett-2i2.jpg",
    price: 19,
    sellerId: "studio-supply",
    locationId: "rouen-rive-droite",
    badge: "Pack complet",
    ratingCount: 143,
    rental: { dailyPrice: 19, weekendPrice: 44, weeklyPrice: 96, deposit: 280, minimumDays: 1, availableFrom: "2026-07-18", instantBook: true },
  },
  {
    id: "exp-rental-shure-sm7b-angers",
    category: "Microphones",
    brand: "Shure",
    model: "SM7B Broadcast Kit",
    title: "Shure SM7B · Kit broadcast",
    description: "Micro dynamique avec préampli en ligne, bras articulé, suspension et câble XLR de cinq mètres.",
    imageUrl: "/images/market/shure-sm7b.jpg",
    price: 14,
    sellerId: "broadcast-lab",
    locationId: "angers-doutre",
    badge: "Désinfecté",
    ratingScore: 4.9,
    ratingCount: 201,
    rental: { dailyPrice: 14, weekendPrice: 32, weeklyPrice: 72, deposit: 210, minimumDays: 2, availableFrom: "2026-07-19", instantBook: true },
  },
  {
    id: "exp-rental-neumann-tlm103-paris",
    category: "Microphones",
    brand: "Neumann",
    model: "TLM 103 Vocal Set",
    title: "Neumann TLM 103 · Vocal Set",
    description: "Micro premium en valise avec suspension, filtre anti-pop et contrôle de capsule documenté.",
    imageUrl: "/images/market/neumann-tlm103.jpg",
    price: 34,
    sellerId: "broadcast-lab",
    locationId: "paris-11",
    conditionLabel: "Capsule contrôlée · Valise scellée",
    badge: "Libre aujourd’hui",
    featured: true,
    ratingScore: 5,
    ratingCount: 162,
    rental: { dailyPrice: 34, weekendPrice: 78, weeklyPrice: 176, deposit: 700, minimumDays: 1, availableFrom: "2026-07-18", instantBook: true },
  },
  {
    id: "exp-rental-rode-nt1a-bordeaux",
    category: "Microphones",
    brand: "RØDE",
    model: "NT1-A Studio Pack",
    title: "RØDE NT1-A · Kit home studio",
    description: "Ensemble silencieux pour voix et guitare avec suspension, filtre, pied et câble équilibré.",
    imageUrl: "/images/market/rode-nt1a.jpg",
    price: 11,
    sellerId: "room-collective",
    locationId: "bordeaux-chartrons",
    ratingCount: 88,
    rental: { dailyPrice: 11, weekendPrice: 25, weeklyPrice: 58, deposit: 160, minimumDays: 2, availableFrom: "2026-07-20", instantBook: true },
  },
  {
    id: "exp-rental-ath-m50x-rennes",
    category: "Casques",
    brand: "Audio-Technica",
    model: "ATH-M50x Quartet",
    title: "4 casques ATH-M50x · Session groupe",
    description: "Lot de quatre casques fermés avec répartiteur, adaptateurs et bonnettes nettoyées.",
    imageUrl: "/images/market/audio-technica-m50x.jpg",
    price: 18,
    sellerId: "studio-supply",
    locationId: "rennes-centre",
    badge: "Lot de 4",
    ratingCount: 57,
    rental: { dailyPrice: 18, weekendPrice: 42, weeklyPrice: 92, deposit: 260, minimumDays: 1, availableFrom: "2026-07-22", instantBook: true },
  },
  {
    id: "exp-rental-dt770-strasbourg",
    category: "Casques",
    brand: "Beyerdynamic",
    model: "DT 770 Pro 80 Ω Duo",
    title: "Duo DT 770 Pro · Prise voix",
    description: "Deux casques fermés avec coussinets de rechange et rallonges pour cabine d’enregistrement.",
    imageUrl: "/images/market/beyerdynamic-dt770.jpg",
    price: 12,
    sellerId: "waveform-studio",
    locationId: "strasbourg-krutenau",
    ratingCount: 102,
    rental: { dailyPrice: 12, weekendPrice: 28, weeklyPrice: 62, deposit: 180, minimumDays: 2, availableFrom: "2026-07-21", instantBook: true },
  },
  {
    id: "exp-rental-fender-strat-montpellier",
    category: "Guitares",
    brand: "Fender",
    model: "American Professional II Stratocaster",
    title: "Fender American Pro II Strat · Étui",
    description: "Stratocaster réglée en 10–46, étui rigide, sangle et jeu de cordes de secours inclus.",
    imageUrl: "/images/market/fender-strat.jpg",
    price: 41,
    sellerId: "guitar-house",
    locationId: "montpellier-beaux-arts",
    badge: "Réglée cette semaine",
    ratingScore: 4.9,
    ratingCount: 84,
    rental: { dailyPrice: 41, weekendPrice: 95, weeklyPrice: 210, deposit: 900, minimumDays: 1, availableFrom: "2026-07-20", instantBook: true },
  },
  {
    id: "exp-rental-fender-tele-nice",
    category: "Guitares",
    brand: "Fender",
    model: "Player Telecaster",
    title: "Fender Player Telecaster · Session",
    description: "Telecaster révisée, accordée au choix et fournie avec housse rembourrée et câble silencieux.",
    imageUrl: "/images/market/fender-telecaster-used.jpg",
    price: 29,
    sellerId: "guitar-house",
    locationId: "nice-port",
    ratingCount: 61,
    rental: { dailyPrice: 29, weekendPrice: 68, weeklyPrice: 148, deposit: 600, minimumDays: 1, availableFrom: "2026-07-25", instantBook: false },
  },
  {
    id: "exp-rental-gibson-lespaul-dijon",
    category: "Guitares",
    brand: "Gibson",
    model: "Les Paul Standard 60s",
    title: "Gibson Les Paul Standard · Studio",
    description: "Les Paul en finition cherry sunburst, contrôlée avant retrait avec étui Gibson et sangle large.",
    imageUrl: "/images/market/gibson-les-paul-used.jpg",
    price: 52,
    sellerId: "guitar-house",
    locationId: "dijon-centre",
    conditionLabel: "Parc premium · Réglage inclus",
    badge: "Étui rigide",
    ratingScore: 4.9,
    ratingCount: 47,
    rental: { dailyPrice: 52, weekendPrice: 120, weeklyPrice: 265, deposit: 1200, minimumDays: 2, availableFrom: "2026-07-23", instantBook: false },
  },
  {
    id: "exp-rental-prs-custom24-paris",
    category: "Guitares",
    brand: "PRS",
    model: "SE Custom 24",
    title: "PRS SE Custom 24 · Pack polyvalent",
    description: "Guitare double humbucker avec housse, accordeur, sangle et option accordage abaissé.",
    imageUrl: "/images/market/prs-se-custom-24-used.jpg",
    price: 32,
    sellerId: "elise-tones",
    locationId: "paris-11",
    ratingCount: 72,
    rental: { dailyPrice: 32, weekendPrice: 74, weeklyPrice: 162, deposit: 650, minimumDays: 1, availableFrom: "2026-07-21", instantBook: true },
  },
  {
    id: "exp-rental-roland-td17-lille",
    category: "Batteries électroniques",
    brand: "Roland",
    model: "TD-17KVX2",
    title: "Roland TD-17KVX2 · Kit répétition",
    description: "Batterie silencieuse complète avec rack, siège, pédale de grosse caisse et tapis antidérapant.",
    imageUrl: "/images/market/roland-td17kvx.jpg",
    price: 42,
    sellerId: "rhythm-workshop",
    locationId: "lille-wazemmes",
    badge: "Hardware complet",
    featured: true,
    ratingScore: 4.9,
    ratingCount: 91,
    rental: { dailyPrice: 42, weekendPrice: 98, weeklyPrice: 220, deposit: 760, minimumDays: 2, availableFrom: "2026-07-26", instantBook: false },
  },
  {
    id: "exp-rental-pioneer-ddj1000-marseille",
    category: "DJ & vinyle",
    brand: "Pioneer DJ",
    model: "DDJ-1000",
    title: "Pioneer DDJ-1000 · Pack soirée",
    description: "Contrôleur quatre voies avec flight case, câbles XLR et ordinateur de secours en option.",
    imageUrl: "/images/market/pioneer-ddj-1000-used.jpg",
    price: 58,
    sellerId: "vinyl-circuit",
    locationId: "marseille-cours-julien",
    badge: "Flight case inclus",
    ratingScore: 4.9,
    ratingCount: 134,
    rental: { dailyPrice: 58, weekendPrice: 134, weeklyPrice: 298, deposit: 950, minimumDays: 1, availableFrom: "2026-07-19", instantBook: true },
  },
  {
    id: "exp-rental-pioneer-flx10-rouen",
    category: "DJ & vinyle",
    brand: "Pioneer DJ",
    model: "DDJ-FLX10",
    title: "Pioneer DDJ-FLX10 · Open-format",
    description: "Contrôleur récent avec flight case, câblage symétrique et briefing de prise en main au retrait.",
    imageUrl: "/images/market/pioneer-ddj-flx10.jpg",
    price: 64,
    sellerId: "vinyl-circuit",
    locationId: "rouen-rive-droite",
    badge: "Briefing inclus",
    ratingCount: 63,
    rental: { dailyPrice: 64, weekendPrice: 148, weeklyPrice: 326, deposit: 1050, minimumDays: 1, availableFrom: "2026-07-22", instantBook: true },
  },
  {
    id: "exp-rental-technics-duo-marseille",
    category: "DJ & vinyle",
    brand: "Technics",
    model: "SL-1200MK2 Duo",
    title: "Duo Technics SL-1200MK2 · Cellules",
    description: "Deux platines révisées avec cellules Concorde, capots et flight cases individuels.",
    imageUrl: "/images/market/technics-sl1200.jpg",
    price: 72,
    sellerId: "vinyl-circuit",
    locationId: "marseille-cours-julien",
    conditionLabel: "Pitch calibré · Cellules contrôlées",
    badge: "La paire",
    ratingScore: 5,
    ratingCount: 109,
    rental: { dailyPrice: 72, weekendPrice: 168, weeklyPrice: 370, deposit: 1200, minimumDays: 2, availableFrom: "2026-07-24", instantBook: false },
  },
  {
    id: "exp-rental-oxygen49-nantes",
    category: "Contrôleurs MIDI",
    brand: "M-Audio",
    model: "Oxygen Pro 49",
    title: "M-Audio Oxygen Pro 49 · Création mobile",
    description: "Clavier maître 49 touches avec pédale sustain, câble USB-C et housse de transport.",
    imageUrl: "/images/market/m-audio-oxygen-pro-49.jpg",
    price: 15,
    sellerId: "synth-district",
    locationId: "nantes-centre",
    ratingCount: 55,
    rental: { dailyPrice: 15, weekendPrice: 35, weeklyPrice: 77, deposit: 220, minimumDays: 2, availableFrom: "2026-07-20", instantBook: true },
  },
  {
    id: "exp-rental-adam-a7x-clermont",
    category: "Monitoring",
    brand: "Adam Audio",
    model: "A7X Matched Pair",
    title: "Paire Adam A7X · Monitoring mobile",
    description: "Paire appairée avec mousses de transport, supports isolants et câbles XLR de trois mètres.",
    imageUrl: "/images/market/adam-a7x-used.jpg",
    price: 51,
    sellerId: "waveform-studio",
    locationId: "clermont-jaude",
    conditionLabel: "Paire mesurée · Courbe fournie",
    badge: "Paire appairée",
    ratingScore: 4.9,
    ratingCount: 78,
    rental: { dailyPrice: 51, weekendPrice: 118, weeklyPrice: 262, deposit: 950, minimumDays: 2, availableFrom: "2026-07-25", instantBook: false },
  },
  {
    id: "exp-rental-zoom-h6-lyon",
    category: "Enregistreurs",
    brand: "Zoom",
    model: "H6 Documentary Kit",
    title: "Zoom H6 · Kit documentaire",
    description: "Enregistreur six pistes avec capsules XY, bonnette, carte SD et batteries rechargeables.",
    imageUrl: "/images/market/zoom-h6-used.jpg",
    price: 21,
    sellerId: "room-collective",
    locationId: "lyon-2",
    badge: "Batteries incluses",
    ratingCount: 124,
    rental: { dailyPrice: 21, weekendPrice: 48, weeklyPrice: 106, deposit: 260, minimumDays: 1, availableFrom: "2026-07-18", instantBook: true },
  },
  {
    id: "exp-rental-vocal-booth-bordeaux",
    category: "Rooms & studios",
    brand: "Room Collective",
    model: "Vocal Booth B",
    title: "Vocal Booth B · Journée autonome",
    description: "Cabine traitée, chaîne voix premium et poste de travail disponibles en accès autonome accompagné.",
    imageUrl: "/images/market/service-studio-room.png",
    price: 165,
    sellerId: "room-collective",
    locationId: "bordeaux-chartrons",
    conditionLabel: "Cabine traitée · Chaîne contrôlée",
    badge: "9 h – 19 h",
    featured: true,
    ratingScore: 4.9,
    ratingCount: 119,
    rental: { dailyPrice: 165, weekendPrice: 310, weeklyPrice: 720, deposit: 350, minimumDays: 1, availableFrom: "2026-07-21", instantBook: true },
  },
  {
    id: "exp-rental-control-room-lyon",
    category: "Rooms & studios",
    brand: "Session Club",
    model: "Control Room C",
    title: "Control Room C · Mix en autonomie",
    description: "Régie calibrée avec double écran, contrôleur de monitoring et écoute nearfield prête à mixer.",
    imageUrl: "/images/market/service-mix-mastering.png",
    price: 190,
    sellerId: "session-club",
    locationId: "lyon-2",
    conditionLabel: "Régie calibrée · Accès sécurisé",
    badge: "Calibration incluse",
    ratingScore: 5,
    ratingCount: 86,
    rental: { dailyPrice: 190, weekendPrice: 360, weeklyPrice: 840, deposit: 400, minimumDays: 1, availableFrom: "2026-07-22", instantBook: true },
  },
  {
    id: "exp-rental-live-room-clermont",
    category: "Rooms & studios",
    brand: "Room Collective",
    model: "Live Room 120",
    title: "Live Room 120 · Répétition journée",
    description: "Grande salle équipée d’une façade, de retours, d’une batterie et de pieds micro pour un groupe complet.",
    imageUrl: "/images/market/service-live-room.webp",
    price: 230,
    sellerId: "room-collective",
    locationId: "clermont-jaude",
    conditionLabel: "Backline vérifié · Plateau prêt",
    badge: "Backline inclus",
    ratingCount: 97,
    rental: { dailyPrice: 230, weekendPrice: 430, weeklyPrice: 990, deposit: 500, minimumDays: 1, availableFrom: "2026-07-27", instantBook: false },
  },
  {
    id: "exp-rental-stage-toulouse",
    category: "Rooms & studios",
    brand: "Meewav Rooms",
    model: "Starlight Stage",
    title: "Starlight Stage · Filage & captation",
    description: "Plateau lumière violet avec façade, retours et régie vidéo pour répétition générale ou showcase.",
    imageUrl: "/images/market/service-live-room-starlight.png",
    price: 420,
    sellerId: "synth-district",
    locationId: "toulouse-saint-cyprien",
    conditionLabel: "Plateau contrôlé · Régie disponible",
    badge: "Captation en option",
    featured: true,
    ratingScore: 4.9,
    ratingCount: 64,
    rental: { dailyPrice: 420, weekendPrice: 790, weeklyPrice: 1750, deposit: 800, minimumDays: 1, availableFrom: "2026-07-29", instantBook: false },
  },
  {
    id: "exp-rental-writing-suite-angers",
    category: "Rooms & studios",
    brand: "Modular Corner",
    model: "Writing Suite 4",
    title: "Writing Suite 4 · Production à deux",
    description: "Suite de composition avec claviers, contrôleurs, double casque et espace confortable pour deux artistes.",
    imageUrl: "/images/market/service-beatmaking-masterclass.png",
    price: 145,
    sellerId: "modular-corner",
    locationId: "angers-doutre",
    conditionLabel: "Suite préparée · Session sauvegardée",
    badge: "Deux postes",
    ratingCount: 52,
    rental: { dailyPrice: 145, weekendPrice: 275, weeklyPrice: 620, deposit: 300, minimumDays: 1, availableFrom: "2026-07-24", instantBook: true },
  },
  {
    id: "exp-rental-acoustic-kit-rennes",
    category: "Rooms & studios",
    brand: "Atlas Audio",
    model: "Flex Acoustic 12",
    title: "Kit acoustique mobile · 12 panneaux",
    description: "Douze panneaux absorbants sur pieds, deux bass traps et couvertures de transport pour prise nomade.",
    imageUrl: "/images/market/market-acoustic-wall.webp",
    price: 36,
    sellerId: "atlas-audio",
    locationId: "rennes-centre",
    conditionLabel: "Textiles propres · Pieds contrôlés",
    badge: "Installation possible",
    ratingCount: 38,
    rental: { dailyPrice: 36, weekendPrice: 84, weeklyPrice: 186, deposit: 320, minimumDays: 2, availableFrom: "2026-07-26", instantBook: false },
  },
];

const serviceExpansionSeeds: ServiceExpansionSeed[] = [
  {
    id: "exp-service-mix-single-camille",
    category: "Mix & mastering",
    brand: "Camille Mix",
    model: "Mix Single Signature",
    title: "Mix complet · Single jusqu’à 40 pistes",
    description: "Équilibre, automation, traitements créatifs et deux séries de retours pour finaliser un single.",
    imageUrl: "/images/market/service-mix-mastering.png",
    price: 219,
    sellerId: "camille-mix",
    locationId: "rennes-centre",
    badge: "2 retours inclus",
    featured: true,
    ratingScore: 5,
    ratingCount: 142,
    service: { kind: "production", format: "À distance", durationLabel: "1 morceau", deliveryLabel: "Livraison sous 6 jours", nextAvailability: "Démarrage le 20 juillet" },
  },
  {
    id: "exp-service-podcast-production-bordeaux",
    category: "Rooms & studios",
    brand: "Broadcast Lab",
    model: "Podcast clé en main",
    title: "Podcast vidéo · Tournage & montage",
    description: "Studio quatre micros, réalisation multicam, montage, mix et exports verticaux pour un épisode.",
    imageUrl: "/images/market/service-podcast-studio.jpg",
    price: 390,
    sellerId: "broadcast-lab",
    locationId: "bordeaux-chartrons",
    badge: "4 micros · 3 caméras",
    ratingScore: 4.9,
    ratingCount: 96,
    service: { kind: "room", format: "Présentiel", durationLabel: "Demi-journée", deliveryLabel: "Épisode livré sous 5 jours", nextAvailability: "Lundi · 9 h" },
  },
  {
    id: "exp-service-vocal-session-paris",
    category: "Rooms & studios",
    brand: "Room Collective",
    model: "Vocal Session Premium",
    title: "Session voix · Ingénieur & direction",
    description: "Trois heures de prise, direction d’interprétation, comping et nettoyage des pistes le jour même.",
    imageUrl: "/images/market/service-studio-room.png",
    price: 230,
    sellerId: "room-collective",
    locationId: "paris-11",
    badge: "Chaîne premium",
    featured: true,
    ratingScore: 5,
    ratingCount: 174,
    service: { kind: "room", format: "Présentiel", durationLabel: "3 heures", deliveryLabel: "Pistes éditées sous 24 h", nextAvailability: "Demain · 10 h" },
  },
  {
    id: "exp-service-vocal-coach-nantes",
    category: "Cours & coaching",
    brand: "Élise Tones",
    model: "Voix en studio",
    title: "Coaching vocal · Préparer une session",
    description: "Échauffement ciblé, placement, endurance et plan de travail adapté au morceau à enregistrer.",
    imageUrl: "/images/market/service-vocal-coaching.jpg",
    price: 72,
    sellerId: "elise-tones",
    locationId: "nantes-centre",
    badge: "Plan vocal inclus",
    ratingScore: 4.9,
    ratingCount: 118,
    service: { kind: "coaching", format: "Studio ou visio", durationLabel: "1 h 30", deliveryLabel: "Routine audio personnalisée", nextAvailability: "Mardi · 17 h" },
  },
  {
    id: "exp-service-dj-transition-marseille",
    category: "Cours & coaching",
    brand: "Vinyl Circuit",
    model: "Transitions avancées",
    title: "Coaching DJ · Transitions & énergie",
    description: "Travail des enchaînements, lecture du dancefloor et construction d’un set de 45 minutes enregistré.",
    imageUrl: "/images/market/service-dj-coaching.jpg",
    price: 64,
    sellerId: "vinyl-circuit",
    locationId: "marseille-cours-julien",
    ratingScore: 4.9,
    ratingCount: 87,
    service: { kind: "coaching", format: "Présentiel", durationLabel: "2 heures", deliveryLabel: "Set filmé et commenté", nextAvailability: "Samedi · 11 h" },
  },
  {
    id: "exp-service-art-direction-nice",
    category: "Cours & coaching",
    brand: "Noémie Sound",
    model: "Direction artistique express",
    title: "Direction artistique · Audit de projet",
    description: "Écoute du catalogue, positionnement, références et feuille de route visuelle et sonore sur trente jours.",
    imageUrl: "/images/market/service-coach-artist.webp",
    price: 135,
    sellerId: "noemie-sound",
    locationId: "nice-port",
    badge: "Roadmap 30 jours",
    ratingCount: 75,
    service: { kind: "coaching", format: "Visio", durationLabel: "2 heures", deliveryLabel: "Dossier stratégique sous 48 h", nextAvailability: "Jeudi · 14 h" },
  },
  {
    id: "exp-service-mao-arrangement-lyon",
    category: "Cours & coaching",
    brand: "Session Club",
    model: "Arrangement MAO",
    title: "Coaching MAO · Finir son arrangement",
    description: "Session individuelle sur ton projet pour clarifier la structure, les transitions et le mouvement du morceau.",
    imageUrl: "/images/market/service-coaching-mao.webp",
    price: 69,
    sellerId: "session-club",
    locationId: "lyon-2",
    badge: "Sur ton projet",
    ratingScore: 4.9,
    ratingCount: 132,
    service: { kind: "coaching", format: "Visio ou studio", durationLabel: "1 h 30", deliveryLabel: "Projet annoté et replay", nextAvailability: "Demain · 19 h" },
  },
  {
    id: "exp-service-beatmaking-masterclass-strasbourg",
    category: "Cours & coaching",
    brand: "Modular Corner",
    model: "Beatmaking sans écran",
    title: "Masterclass beatmaking · Workflow hardware",
    description: "Créer un morceau complet avec sampler et synthés, du premier pattern au live jam final.",
    imageUrl: "/images/market/service-beatmaking-masterclass.png",
    price: 42,
    sellerId: "modular-corner",
    locationId: "strasbourg-krutenau",
    badge: "10 places",
    featured: true,
    ratingScore: 4.9,
    ratingCount: 68,
    service: { kind: "coaching", format: "Room interactive", durationLabel: "3 heures", deliveryLabel: "Replay et samples inclus", nextAvailability: "26 juillet · 18 h" },
  },
  {
    id: "exp-service-live-ticket-clermont",
    category: "Billetterie",
    brand: "Meewav Rooms",
    model: "Midnight Echo Pass",
    title: "Live Room · Midnight Echo",
    description: "Concert immersif, chat artistes, coulisses numériques et replay disponible pendant sept jours.",
    imageUrl: "/images/market/service-live-room.webp",
    price: 13,
    sellerId: "room-collective",
    locationId: "clermont-jaude",
    badge: "52 places",
    ratingCount: 219,
    service: { kind: "ticket", format: "Room en direct", durationLabel: "85 minutes", deliveryLabel: "Replay pendant 7 jours", nextAvailability: "24 juillet · 21 h 30" },
  },
  {
    id: "exp-service-starlight-ticket-toulouse",
    category: "Billetterie",
    brand: "Meewav Rooms",
    model: "Starlight Session Pass",
    title: "Starlight Session · Showcase interactif",
    description: "Showcase en direct avec vote sur la setlist, questions artistes et accès aux répétitions filmées.",
    imageUrl: "/images/market/service-live-room-starlight.png",
    price: 17,
    sellerId: "synth-district",
    locationId: "toulouse-saint-cyprien",
    badge: "Vote sur la setlist",
    ratingScore: 4.9,
    ratingCount: 164,
    service: { kind: "ticket", format: "Room en direct", durationLabel: "75 minutes", deliveryLabel: "Backstage et replay inclus", nextAvailability: "29 juillet · 20 h 30" },
  },
  {
    id: "exp-service-accordion-session",
    category: "Mix & mastering",
    brand: "Lucien Session",
    model: "Accordéon à distance",
    title: "Accordéoniste session · 4 pistes",
    description: "Accordéon acoustique ou musette enregistré sur ta maquette, avec quatre propositions et stems propres.",
    imageUrl: "/avatar/web/hd/accordeoniste.webp",
    price: 145,
    sellerId: "noemie-sound",
    locationId: "rennes-centre",
    badge: "Stems 24 bits",
    ratingScore: 4.9,
    ratingCount: 54,
    service: { kind: "production", format: "À distance", durationLabel: "Jusqu’à 4 pistes", deliveryLabel: "Livraison sous 4 jours", nextAvailability: "Disponible lundi" },
  },
  {
    id: "exp-service-lyrics-french",
    category: "Cours & coaching",
    brand: "Atelier des Mots",
    model: "Paroles francophones",
    title: "Écriture de paroles · Refrain & couplets",
    description: "Co-écriture francophone à partir de ton thème et de ta topline, avec une session de révision incluse.",
    imageUrl: "/avatar/web/hd/auteur-parolier.webp",
    price: 125,
    sellerId: "elise-tones",
    locationId: "paris-11",
    badge: "Co-écriture",
    ratingScore: 5,
    ratingCount: 81,
    service: { kind: "production", format: "Visio + document partagé", durationLabel: "1 chanson", deliveryLabel: "Texte final sous 5 jours", nextAvailability: "Créneau mardi" },
  },
  {
    id: "exp-service-bass-session",
    category: "Mix & mastering",
    brand: "Session Club",
    model: "Basse électrique session",
    title: "Bassiste session · Groove sur mesure",
    description: "Prise DI et ampli, trois variations de groove et fichiers édités prêts pour le mix.",
    imageUrl: "/avatar/web/hd/bassiste.webp",
    price: 95,
    sellerId: "session-club",
    locationId: "lyon-2",
    ratingScore: 4.9,
    ratingCount: 73,
    service: { kind: "production", format: "À distance", durationLabel: "1 morceau", deliveryLabel: "Stems livrés sous 72 h", nextAvailability: "Deux créneaux cette semaine" },
  },
  {
    id: "exp-service-drum-session",
    category: "Rooms & studios",
    brand: "Rhythm Workshop",
    model: "Drums Session Pro",
    title: "Batteur session · Prise multipiste",
    description: "Batterie acoustique accordée pour ton morceau, prise multipiste et trois options de jeu complètes.",
    imageUrl: "/avatar/web/hd/batteur-batteuse.webp",
    price: 175,
    sellerId: "rhythm-workshop",
    locationId: "lille-wazemmes",
    badge: "12 pistes",
    featured: true,
    ratingScore: 5,
    ratingCount: 103,
    service: { kind: "production", format: "Studio ou à distance", durationLabel: "1 morceau", deliveryLabel: "Multipistes sous 4 jours", nextAvailability: "Session dimanche" },
  },
  {
    id: "exp-service-beatbox-workshop",
    category: "Cours & coaching",
    brand: "Pulse Academy",
    model: "Beatbox Foundations",
    title: "Atelier beatbox · Rythme & textures",
    description: "Cours collectif accessible pour construire une boîte à rythmes vocale et enregistrer une mini performance.",
    imageUrl: "/avatar/web/hd/beatboxer.webp",
    price: 32,
    sellerId: "rhythm-workshop",
    locationId: "nantes-centre",
    badge: "8 places",
    ratingCount: 44,
    service: { kind: "coaching", format: "Présentiel", durationLabel: "2 heures", deliveryLabel: "Performance enregistrée", nextAvailability: "Samedi · 14 h" },
  },
  {
    id: "exp-service-beat-production",
    category: "Mix & mastering",
    brand: "Noémie Sound",
    model: "Beat original exclusif",
    title: "Production d’un beat original · Exclusif",
    description: "Instrumentale construite autour de ton univers, avec arrangement complet, stems et deux retours.",
    imageUrl: "/avatar/web/hd/beatmaker.webp",
    price: 260,
    sellerId: "noemie-sound",
    locationId: "montpellier-beaux-arts",
    badge: "Licence exclusive",
    ratingScore: 4.9,
    ratingCount: 92,
    service: { kind: "production", format: "À distance", durationLabel: "1 instrumentale", deliveryLabel: "Première version sous 7 jours", nextAvailability: "Démarrage le 27 juillet" },
  },
  {
    id: "exp-service-rap-feature",
    category: "Mix & mastering",
    brand: "Atlas Sessions",
    model: "Couplet invité",
    title: "Couplet rap invité · 16 mesures",
    description: "Écriture, interprétation et prises voix propres pour un couplet invité cohérent avec ton titre.",
    imageUrl: "/avatar/web/hd/chanteur-rappeur.webp",
    price: 190,
    sellerId: "atlas-audio",
    locationId: "dijon-centre",
    badge: "Voix éditées",
    ratingCount: 59,
    service: { kind: "production", format: "À distance", durationLabel: "16 mesures", deliveryLabel: "Stems sous 6 jours", nextAvailability: "Disponible mercredi" },
  },
  {
    id: "exp-service-vocal-feature",
    category: "Mix & mastering",
    brand: "Élise Tones",
    model: "Topline & voix",
    title: "Topline chantée · Lead & harmonies",
    description: "Topline originale, voix lead, doubles et harmonies livrées éditées pour ton morceau.",
    imageUrl: "/avatar/web/hd/chanteuse-rappeuse.webp",
    price: 240,
    sellerId: "elise-tones",
    locationId: "paris-11",
    badge: "Harmonies incluses",
    featured: true,
    ratingScore: 5,
    ratingCount: 126,
    service: { kind: "production", format: "À distance", durationLabel: "1 refrain + couplet", deliveryLabel: "Stems sous 7 jours", nextAvailability: "Démarrage vendredi" },
  },
  {
    id: "exp-service-coach-vocal-visio",
    category: "Cours & coaching",
    brand: "Solène Voice",
    model: "Bilan vocal personnalisé",
    title: "Bilan vocal · Technique & endurance",
    description: "Diagnostic de ta voix, exercices ciblés et programme audio sur deux semaines pour progresser durablement.",
    imageUrl: "/avatar/web/hd/coach-vocal.webp",
    price: 68,
    sellerId: "elise-tones",
    locationId: "bordeaux-chartrons",
    badge: "Programme 14 jours",
    ratingScore: 4.9,
    ratingCount: 151,
    service: { kind: "coaching", format: "Visio", durationLabel: "1 h 15", deliveryLabel: "Programme audio personnalisé", nextAvailability: "Demain · 12 h" },
  },
  {
    id: "exp-service-composition-film",
    category: "Mix & mastering",
    brand: "Camille Mix",
    model: "Composition à l’image",
    title: "Composition originale · Film court",
    description: "Thème, variations et mix stéréo conçus pour accompagner un film, une bande-annonce ou un générique.",
    imageUrl: "/avatar/web/hd/compositeur.webp",
    price: 480,
    sellerId: "camille-mix",
    locationId: "rennes-centre",
    badge: "Cession web incluse",
    ratingScore: 5,
    ratingCount: 67,
    service: { kind: "production", format: "À distance", durationLabel: "Jusqu’à 3 minutes", deliveryLabel: "Maquette sous 8 jours", nextAvailability: "Brief lundi" },
  },
  {
    id: "exp-service-choreo-stage",
    category: "Cours & coaching",
    brand: "Pulse Academy",
    model: "Chorégraphie scénique solo",
    title: "Chorégraphie · Performance solo",
    description: "Création d’une chorégraphie adaptée à ton morceau, ton niveau et l’espace réel de la scène.",
    imageUrl: "/avatar/web/hd/danseur.webp",
    price: 210,
    sellerId: "room-collective",
    locationId: "marseille-cours-julien",
    badge: "Vidéo miroir incluse",
    ratingCount: 52,
    service: { kind: "coaching", format: "Studio", durationLabel: "2 sessions de 2 h", deliveryLabel: "Tutoriel vidéo inclus", nextAvailability: "Week-end du 25 juillet" },
  },
  {
    id: "exp-service-dance-workshop",
    category: "Cours & coaching",
    brand: "Pulse Academy",
    model: "Stage danse clip",
    title: "Stage danse · Préparer un clip",
    description: "Atelier collectif de mouvements caméra, synchronisation et présence pour réussir une journée de tournage.",
    imageUrl: "/avatar/web/hd/danseuse.webp",
    price: 45,
    sellerId: "room-collective",
    locationId: "lyon-2",
    badge: "12 places",
    ratingCount: 83,
    service: { kind: "coaching", format: "Présentiel", durationLabel: "3 heures", deliveryLabel: "Répétition filmée", nextAvailability: "2 août · 14 h" },
  },
  {
    id: "exp-service-artistic-direction-release",
    category: "Cours & coaching",
    brand: "Noémie Sound",
    model: "Direction artistique release",
    title: "Direction artistique · Prochaine sortie",
    description: "Cohérence sonore, image, séquençage des contenus et calendrier pour transformer un titre en vraie sortie.",
    imageUrl: "/avatar/web/hd/directeur-artistique.webp",
    price: 320,
    sellerId: "noemie-sound",
    locationId: "nice-port",
    badge: "Plan de campagne",
    featured: true,
    ratingScore: 5,
    ratingCount: 89,
    service: { kind: "coaching", format: "Hybride", durationLabel: "3 rendez-vous", deliveryLabel: "Dossier complet sous 10 jours", nextAvailability: "Démarrage le 28 juillet" },
  },
  {
    id: "exp-service-dj-private-event",
    category: "Billetterie",
    brand: "Vinyl Circuit",
    model: "DJ set événement",
    title: "DJ set · Événement privé 4 heures",
    description: "Programmation musicale sur mesure, préparation des demandes et performance DJ pour ton événement.",
    imageUrl: "/avatar/web/hd/dj.webp",
    price: 520,
    sellerId: "vinyl-circuit",
    locationId: "marseille-cours-julien",
    badge: "Set sur mesure",
    ratingScore: 4.9,
    ratingCount: 111,
    service: { kind: "ticket", format: "Prestation sur site", durationLabel: "Jusqu’à 4 heures", deliveryLabel: "Playlist préparatoire incluse", nextAvailability: "Samedi 1er août" },
  },
  {
    id: "exp-service-acoustic-guitar-session",
    category: "Mix & mastering",
    brand: "Guitar House",
    model: "Guitare acoustique session",
    title: "Guitare acoustique · Prise stéréo",
    description: "Accompagnement, arpèges ou textures enregistrés en stéréo avec trois propositions d’interprétation.",
    imageUrl: "/avatar/web/hd/guitariste-acoustique.webp",
    price: 90,
    sellerId: "guitar-house",
    locationId: "montpellier-beaux-arts",
    ratingScore: 4.9,
    ratingCount: 64,
    service: { kind: "production", format: "À distance", durationLabel: "1 morceau", deliveryLabel: "Pistes sous 4 jours", nextAvailability: "Disponible jeudi" },
  },
  {
    id: "exp-service-electric-guitar-session",
    category: "Mix & mastering",
    brand: "Guitar House",
    model: "Guitares électriques reampées",
    title: "Guitares électriques · Rythmiques & leads",
    description: "Doubles rythmiques, leads et DI propres avec plusieurs couleurs d’amplis prêtes pour ton arrangement.",
    imageUrl: "/avatar/web/hd/guitariste-electrique.webp",
    price: 110,
    sellerId: "guitar-house",
    locationId: "dijon-centre",
    badge: "DI + amplis",
    ratingScore: 4.9,
    ratingCount: 78,
    service: { kind: "production", format: "À distance", durationLabel: "1 morceau", deliveryLabel: "Pistes sous 5 jours", nextAvailability: "Deux créneaux ouverts" },
  },
  {
    id: "exp-service-audio-postproduction",
    category: "Mix & mastering",
    brand: "Broadcast Lab",
    model: "Postproduction vidéo",
    title: "Postproduction audio · Vidéo 10 minutes",
    description: "Nettoyage des dialogues, sound design, mix et normalisation broadcast pour une vidéo prête à publier.",
    imageUrl: "/avatar/web/hd/ingenieur-son.webp",
    price: 295,
    sellerId: "broadcast-lab",
    locationId: "bordeaux-chartrons",
    badge: "Normes web & broadcast",
    featured: true,
    ratingScore: 5,
    ratingCount: 137,
    service: { kind: "production", format: "À distance", durationLabel: "Jusqu’à 10 minutes", deliveryLabel: "Version mixée sous 6 jours", nextAvailability: "Démarrage mardi" },
  },
  {
    id: "exp-service-release-management",
    category: "Cours & coaching",
    brand: "Atlas Audio",
    model: "Release Management Sprint",
    title: "Accompagnement sortie · Sprint 21 jours",
    description: "Rétroplanning, métadonnées, distribution et suivi des livrables pour publier ton titre sans angle mort.",
    imageUrl: "/avatar/web/hd/management.webp",
    price: 260,
    sellerId: "atlas-audio",
    locationId: "rouen-rive-droite",
    badge: "Suivi 21 jours",
    ratingScore: 4.9,
    ratingCount: 58,
    service: { kind: "coaching", format: "Visio + espace partagé", durationLabel: "3 semaines", deliveryLabel: "Checklist et suivi inclus", nextAvailability: "Cohorte du 27 juillet" },
  },
  {
    id: "exp-service-music-video",
    category: "Rooms & studios",
    brand: "Waveform Studio",
    model: "Clip performance vertical",
    title: "Clip performance · Tournage vertical",
    description: "Concept simple, tournage multicam et montage de trois versions verticales pour annoncer un morceau.",
    imageUrl: "/avatar/web/hd/videaste-clipper.webp",
    price: 590,
    sellerId: "waveform-studio",
    locationId: "nice-port",
    badge: "3 formats livrés",
    ratingScore: 4.9,
    ratingCount: 72,
    service: { kind: "room", format: "Tournage sur site", durationLabel: "Demi-journée", deliveryLabel: "Montages sous 7 jours", nextAvailability: "3 août · 9 h" },
  },
  {
    id: "exp-service-violin-arrangement",
    category: "Mix & mastering",
    brand: "Camille Mix",
    model: "Cordes solo arrangées",
    title: "Violon session · Arrangement & prises",
    description: "Arrangement de lignes de cordes, trois couches de violon et livraison des prises éditées avec partition.",
    imageUrl: "/avatar/web/hd/violoniste.webp",
    price: 165,
    sellerId: "camille-mix",
    locationId: "strasbourg-krutenau",
    badge: "Partition incluse",
    ratingScore: 5,
    ratingCount: 66,
    service: { kind: "production", format: "À distance", durationLabel: "1 morceau", deliveryLabel: "Stems et partition sous 6 jours", nextAvailability: "Disponible dès lundi" },
  },
];

export const marketRentalExpansionProducts: MarketProduct[] = rentalExpansionSeeds.map(createRentalProduct);

export const marketServiceExpansionProducts: MarketProduct[] = serviceExpansionSeeds.map(createServiceProduct);

export const marketRentalServiceExpansionProducts: MarketProduct[] = [
  ...marketRentalExpansionProducts,
  ...marketServiceExpansionProducts,
];

export const MARKET_RENTAL_SERVICE_EXPANSION_COUNTS = {
  rental: marketRentalExpansionProducts.length,
  services: marketServiceExpansionProducts.length,
  total: marketRentalServiceExpansionProducts.length,
} as const;
