import type { MarketProduct } from "./marketDemoData";

type RentalSeed = {
  id: string;
  category: MarketProduct["category"];
  brand: string;
  model: string;
  title: string;
  description: string;
  imageUrl: string;
  price: number;
  sellerId: string;
  locationId: string;
  ratingScore: number;
  ratingCount: number;
  rental: NonNullable<MarketProduct["rental"]>;
};

type ServiceSeed = {
  id: string;
  category: MarketProduct["category"];
  brand: string;
  model: string;
  title: string;
  description: string;
  imageUrl: string;
  price: number;
  sellerId: string;
  locationId: string;
  ratingScore: number;
  ratingCount: number;
  service: NonNullable<MarketProduct["service"]>;
};

const IMAGE_ROOT = "/images/market/expansion/wave2-rental-services";

const rentalImages = {
  dj: `${IMAGE_ROOT}/rental-dj-performance-rig.webp`,
  wireless: `${IMAGE_ROOT}/rental-wireless-microphone-kit.webp`,
  piano: `${IMAGE_ROOT}/rental-upright-piano-recording.webp`,
  booth: `${IMAGE_ROOT}/rental-portable-vocal-booth.webp`,
  guitar: `${IMAGE_ROOT}/rental-touring-guitar-rig.webp`,
  synth: `${IMAGE_ROOT}/rental-analog-synth-workstation.webp`,
} as const;

const serviceImages = {
  mastering: `${IMAGE_ROOT}/service-mastering-engineer.webp`,
  vocal: `${IMAGE_ROOT}/service-vocal-coaching.webp`,
  liveSound: `${IMAGE_ROOT}/service-live-sound-engineer.webp`,
  luthier: `${IMAGE_ROOT}/service-luthier-guitar-setup.webp`,
  production: `${IMAGE_ROOT}/service-production-mentoring.webp`,
  streaming: `${IMAGE_ROOT}/service-live-stream-production.webp`,
} as const;

const actionOnlyCart = (): MarketProduct["cart"] => ({
  eligible: false,
  quantity: 0,
  maxQuantity: 0,
});

function createRentalProduct(seed: RentalSeed): MarketProduct {
  return {
    id: seed.id,
    slug: seed.id,
    pillarId: "rental",
    category: seed.category,
    brand: seed.brand,
    model: seed.model,
    title: seed.title,
    description: seed.description,
    imageUrl: seed.imageUrl,
    imageAlt: `${seed.title}, pack de location musicale`,
    condition: "excellent",
    conditionLabel: "Parc professionnel · Contrôlé avant départ",
    price: { amount: seed.price, currency: "EUR", unit: "day" },
    sellerId: seed.sellerId,
    locationId: seed.locationId,
    rating: { score: seed.ratingScore, count: seed.ratingCount },
    favorite: false,
    cart: actionOnlyCart(),
    rental: seed.rental,
    service: null,
    collective: null,
    featured: false,
  };
}

function createServiceProduct(seed: ServiceSeed): MarketProduct {
  return {
    id: seed.id,
    slug: seed.id,
    pillarId: "services",
    category: seed.category,
    brand: seed.brand,
    model: seed.model,
    title: seed.title,
    description: seed.description,
    imageUrl: seed.imageUrl,
    imageAlt: `${seed.title}, prestation musicale professionnelle`,
    condition: "new",
    conditionLabel: seed.service.deliveryLabel,
    price: { amount: seed.price, currency: "EUR", unit: "item" },
    sellerId: seed.sellerId,
    locationId: seed.locationId,
    rating: { score: seed.ratingScore, count: seed.ratingCount },
    favorite: false,
    cart: actionOnlyCart(),
    rental: null,
    service: seed.service,
    collective: null,
    featured: false,
  };
}

const rentalSeeds: RentalSeed[] = [
  {
    id: "wave2-rental-dj-club-paris",
    category: "DJ & vinyle",
    brand: "Pulse Hire",
    model: "Club Performance 2+1",
    title: "Régie DJ club complète · 2 players + mixer",
    description: "Régie prête à jouer, installée en flight case avec monitoring, câbles audio et contrôle technique au départ.",
    imageUrl: rentalImages.dj,
    price: 119,
    sellerId: "vinyl-circuit",
    locationId: "paris-11",
    ratingScore: 4.9,
    ratingCount: 184,
    rental: { dailyPrice: 119, weekendPrice: 269, weeklyPrice: 585, deposit: 1800, minimumDays: 1, availableFrom: "2026-07-21", instantBook: true },
  },
  {
    id: "wave2-rental-dj-event-lyon",
    category: "DJ & vinyle",
    brand: "Stage Circuit",
    model: "Event Deck Pro",
    title: "Pack DJ événement · Régie et retours",
    description: "Deux lecteurs, table de mixage quatre voies et retours compacts pour une soirée, un showcase ou un pop-up.",
    imageUrl: rentalImages.dj,
    price: 104,
    sellerId: "atlas-audio",
    locationId: "lyon-2",
    ratingScore: 4.8,
    ratingCount: 96,
    rental: { dailyPrice: 104, weekendPrice: 238, weeklyPrice: 525, deposit: 1600, minimumDays: 1, availableFrom: "2026-07-23", instantBook: true },
  },
  {
    id: "wave2-rental-dj-stream-nantes",
    category: "DJ & vinyle",
    brand: "Room Ready",
    model: "Broadcast DJ Desk",
    title: "Régie DJ streaming · Pack studio",
    description: "Configuration compacte pour live filmé avec sortie dédiée diffusion, casque fermé et câblage repéré.",
    imageUrl: rentalImages.dj,
    price: 89,
    sellerId: "broadcast-lab",
    locationId: "nantes-centre",
    ratingScore: 4.9,
    ratingCount: 71,
    rental: { dailyPrice: 89, weekendPrice: 204, weeklyPrice: 446, deposit: 1350, minimumDays: 1, availableFrom: "2026-07-22", instantBook: false },
  },
  {
    id: "wave2-rental-wireless-stage-marseille",
    category: "Microphones",
    brand: "Stage Circuit",
    model: "Wireless Stage 4",
    title: "Kit sans-fil scène · 4 voix",
    description: "Quatre micros main, quatre bodypacks, récepteurs et station de charge réunis dans une valise prête scène.",
    imageUrl: rentalImages.wireless,
    price: 78,
    sellerId: "broadcast-lab",
    locationId: "marseille-cours-julien",
    ratingScore: 4.9,
    ratingCount: 122,
    rental: { dailyPrice: 78, weekendPrice: 179, weeklyPrice: 390, deposit: 1200, minimumDays: 1, availableFrom: "2026-07-21", instantBook: true },
  },
  {
    id: "wave2-rental-wireless-ensemble-lille",
    category: "Microphones",
    brand: "Harmonic Rent",
    model: "Wireless Ensemble 8",
    title: "Système HF ensemble · 8 canaux",
    description: "Solution huit canaux coordonnée pour groupe vocal, théâtre ou conférence musicale, avec antennes et accessoires.",
    imageUrl: rentalImages.wireless,
    price: 146,
    sellerId: "studio-supply",
    locationId: "lille-wazemmes",
    ratingScore: 4.8,
    ratingCount: 65,
    rental: { dailyPrice: 146, weekendPrice: 329, weeklyPrice: 710, deposit: 2200, minimumDays: 2, availableFrom: "2026-07-25", instantBook: false },
  },
  {
    id: "wave2-rental-wireless-session-bordeaux",
    category: "Microphones",
    brand: "Room Ready",
    model: "Session Wireless 4",
    title: "Pack HF session live · 4 artistes",
    description: "Micros et bodypacks appairés pour session live, répète filmée ou petite scène avec batteries de secours.",
    imageUrl: rentalImages.wireless,
    price: 72,
    sellerId: "room-collective",
    locationId: "bordeaux-chartrons",
    ratingScore: 4.8,
    ratingCount: 83,
    rental: { dailyPrice: 72, weekendPrice: 165, weeklyPrice: 360, deposit: 1100, minimumDays: 1, availableFrom: "2026-07-24", instantBook: true },
  },
  {
    id: "wave2-rental-piano-recording-paris",
    category: "Rooms & studios",
    brand: "Session Club",
    model: "Upright Recording Suite",
    title: "Piano droit + prise stéréo · Journée",
    description: "Piano entretenu, pièce traitée et paire de micros installée pour enregistrer immédiatement une maquette ou un titre.",
    imageUrl: rentalImages.piano,
    price: 165,
    sellerId: "session-club",
    locationId: "paris-11",
    ratingScore: 5,
    ratingCount: 91,
    rental: { dailyPrice: 165, weekendPrice: 360, weeklyPrice: 790, deposit: 600, minimumDays: 1, availableFrom: "2026-07-26", instantBook: false },
  },
  {
    id: "wave2-rental-piano-songwriter-lyon",
    category: "Rooms & studios",
    brand: "Room Ready",
    model: "Songwriter Piano Room",
    title: "Room piano songwriter · Session 8 h",
    description: "Piano acoustique, banquette, micros et interface pour composer, arranger et enregistrer dans une pièce calme.",
    imageUrl: rentalImages.piano,
    price: 138,
    sellerId: "waveform-studio",
    locationId: "lyon-2",
    ratingScore: 4.9,
    ratingCount: 74,
    rental: { dailyPrice: 138, weekendPrice: 310, weeklyPrice: 680, deposit: 500, minimumDays: 1, availableFrom: "2026-07-23", instantBook: true },
  },
  {
    id: "wave2-rental-piano-duo-nantes",
    category: "Rooms & studios",
    brand: "Harmonic Rent",
    model: "Piano Duo Capture",
    title: "Piano acoustique · Pack duo captation",
    description: "Piano droit accordé avec deux micros, casque et interface pour capturer un duo voix-piano sans installation.",
    imageUrl: rentalImages.piano,
    price: 149,
    sellerId: "room-collective",
    locationId: "nantes-centre",
    ratingScore: 4.9,
    ratingCount: 58,
    rental: { dailyPrice: 149, weekendPrice: 335, weeklyPrice: 720, deposit: 550, minimumDays: 1, availableFrom: "2026-07-27", instantBook: false },
  },
  {
    id: "wave2-rental-vocal-booth-nice",
    category: "Microphones",
    brand: "Room Ready",
    model: "Mobile Vocal Booth",
    title: "Cabine vocale mobile · Kit complet",
    description: "Panneaux acoustiques modulaires, micro, filtre, casque et pied pour transformer une pièce en espace voix contrôlé.",
    imageUrl: rentalImages.booth,
    price: 54,
    sellerId: "broadcast-lab",
    locationId: "nice-port",
    ratingScore: 4.9,
    ratingCount: 136,
    rental: { dailyPrice: 54, weekendPrice: 124, weeklyPrice: 270, deposit: 750, minimumDays: 2, availableFrom: "2026-07-20", instantBook: true },
  },
  {
    id: "wave2-rental-podcast-booth-lille",
    category: "Microphones",
    brand: "Pulse Hire",
    model: "Podcast Isolation Kit",
    title: "Isolation podcast · Pack voix premium",
    description: "Cabine compacte, microphone et écoute fermée pour produire une voix nette dans un bureau ou un appartement.",
    imageUrl: rentalImages.booth,
    price: 43,
    sellerId: "studio-supply",
    locationId: "lille-wazemmes",
    ratingScore: 4.8,
    ratingCount: 101,
    rental: { dailyPrice: 43, weekendPrice: 99, weeklyPrice: 215, deposit: 620, minimumDays: 2, availableFrom: "2026-07-22", instantBook: true },
  },
  {
    id: "wave2-rental-vocal-residency-bordeaux",
    category: "Microphones",
    brand: "Harmonic Rent",
    model: "Residency Vocal Kit",
    title: "Booth vocal mobile · Pack résidence",
    description: "Ensemble renforcé pour une semaine de création, avec traitement, micro, casque et câbles de rechange.",
    imageUrl: rentalImages.booth,
    price: 49,
    sellerId: "room-collective",
    locationId: "bordeaux-chartrons",
    ratingScore: 4.8,
    ratingCount: 62,
    rental: { dailyPrice: 49, weekendPrice: 112, weeklyPrice: 238, deposit: 690, minimumDays: 3, availableFrom: "2026-07-25", instantBook: false },
  },
  {
    id: "wave2-rental-guitar-tour-marseille",
    category: "Guitares",
    brand: "Backline Atlas",
    model: "Touring Guitar Twin",
    title: "Backline guitare tournée · Double ampli",
    description: "Deux amplis, pedalboard, guitare de secours et flight cases pour une date ou une mini-tournée sans compromis.",
    imageUrl: rentalImages.guitar,
    price: 96,
    sellerId: "guitar-house",
    locationId: "marseille-cours-julien",
    ratingScore: 4.9,
    ratingCount: 117,
    rental: { dailyPrice: 96, weekendPrice: 220, weeklyPrice: 480, deposit: 1500, minimumDays: 2, availableFrom: "2026-07-24", instantBook: false },
  },
  {
    id: "wave2-rental-guitar-stereo-paris",
    category: "Guitares",
    brand: "Guitar House",
    model: "Stereo Session Rig",
    title: "Rig guitare stéréo · Session studio",
    description: "Deux amplis complémentaires et pedalboard câblé pour textures larges, reamping ou captation live en studio.",
    imageUrl: rentalImages.guitar,
    price: 82,
    sellerId: "guitar-house",
    locationId: "paris-11",
    ratingScore: 4.9,
    ratingCount: 143,
    rental: { dailyPrice: 82, weekendPrice: 188, weeklyPrice: 410, deposit: 1280, minimumDays: 1, availableFrom: "2026-07-21", instantBook: true },
  },
  {
    id: "wave2-rental-guitar-heavy-strasbourg",
    category: "Guitares",
    brand: "Backline Atlas",
    model: "Heavy Stage Rig",
    title: "Rig guitare heavy · Scène complète",
    description: "Guitare sept cordes, amplification puissante et pedalboard réglé pour répétition, studio ou concert lourd.",
    imageUrl: rentalImages.guitar,
    price: 88,
    sellerId: "atlas-audio",
    locationId: "strasbourg-krutenau",
    ratingScore: 4.8,
    ratingCount: 79,
    rental: { dailyPrice: 88, weekendPrice: 202, weeklyPrice: 440, deposit: 1380, minimumDays: 1, availableFrom: "2026-07-26", instantBook: true },
  },
  {
    id: "wave2-rental-analog-live-lyon",
    category: "Synthétiseurs",
    brand: "Analog Fleet",
    model: "Live Analog Twin",
    title: "Workstation analogique · Set live",
    description: "Deux synthés, séquenceur, interface et flight cases pour construire un set live complet et immédiatement jouable.",
    imageUrl: rentalImages.synth,
    price: 91,
    sellerId: "synth-district",
    locationId: "lyon-2",
    ratingScore: 4.9,
    ratingCount: 128,
    rental: { dailyPrice: 91, weekendPrice: 209, weeklyPrice: 455, deposit: 1700, minimumDays: 2, availableFrom: "2026-07-22", instantBook: true },
  },
  {
    id: "wave2-rental-analog-residency-montpellier",
    category: "Synthétiseurs",
    brand: "Modular Corner",
    model: "Analog Residency Rack",
    title: "Station synthés · Pack résidence",
    description: "Claviers analogiques, séquenceur et interface livrés en flight cases pour plusieurs jours de création intensive.",
    imageUrl: rentalImages.synth,
    price: 84,
    sellerId: "modular-corner",
    locationId: "montpellier-beaux-arts",
    ratingScore: 4.9,
    ratingCount: 92,
    rental: { dailyPrice: 84, weekendPrice: 192, weeklyPrice: 418, deposit: 1580, minimumDays: 3, availableFrom: "2026-07-25", instantBook: false },
  },
  {
    id: "wave2-rental-analog-writing-rennes",
    category: "Synthétiseurs",
    brand: "Analog Fleet",
    model: "Writing Room Twin",
    title: "Duo synthés analogiques · Writing camp",
    description: "Deux claviers complémentaires, séquenceur et écoute casque pour une équipe de composition ou un writing camp.",
    imageUrl: rentalImages.synth,
    price: 79,
    sellerId: "noemie-sound",
    locationId: "rennes-centre",
    ratingScore: 4.8,
    ratingCount: 67,
    rental: { dailyPrice: 79, weekendPrice: 181, weeklyPrice: 394, deposit: 1450, minimumDays: 2, availableFrom: "2026-07-23", instantBook: true },
  },
  {
    id: "wave2-rental-analog-score-nantes",
    category: "Synthétiseurs",
    brand: "Room Ready",
    model: "Cinematic Analog Desk",
    title: "Station analogique · Composition à l’image",
    description: "Synthés expressifs et séquenceur synchronisable pour textures cinématiques, sound design et composition à l’image.",
    imageUrl: rentalImages.synth,
    price: 86,
    sellerId: "waveform-studio",
    locationId: "nantes-centre",
    ratingScore: 4.9,
    ratingCount: 75,
    rental: { dailyPrice: 86, weekendPrice: 197, weeklyPrice: 430, deposit: 1620, minimumDays: 2, availableFrom: "2026-07-27", instantBook: false },
  },
  {
    id: "wave2-rental-analog-production-bordeaux",
    category: "Synthétiseurs",
    brand: "Pulse Hire",
    model: "Producer Analog Suite",
    title: "Suite analogique producer · 3 machines",
    description: "Trio de machines complémentaires, interface et câbles pour enrichir une production sans déplacer tout le studio.",
    imageUrl: rentalImages.synth,
    price: 94,
    sellerId: "synth-district",
    locationId: "bordeaux-chartrons",
    ratingScore: 4.9,
    ratingCount: 109,
    rental: { dailyPrice: 94, weekendPrice: 215, weeklyPrice: 470, deposit: 1750, minimumDays: 2, availableFrom: "2026-07-24", instantBook: true },
  },
];

const serviceSeeds: ServiceSeed[] = [
  {
    id: "wave2-service-mastering-album-paris",
    category: "Mix & mastering",
    brand: "Camille Mix",
    model: "Album Mastering",
    title: "Mastering album · Cohérence complète",
    description: "Mastering analogique et numérique d’un album, cohérence entre les titres, contrôle streaming et livraison des masters.",
    imageUrl: serviceImages.mastering,
    price: 590,
    sellerId: "camille-mix",
    locationId: "paris-11",
    ratingScore: 5,
    ratingCount: 168,
    service: { kind: "production", format: "Studio + livraison en ligne", durationLabel: "Jusqu’à 10 titres", deliveryLabel: "Livré sous 7 jours", nextAvailability: "22 juillet" },
  },
  {
    id: "wave2-service-mastering-single-lyon",
    category: "Mix & mastering",
    brand: "Waveform Studio",
    model: "Single Master",
    title: "Mastering single · Streaming & club",
    description: "Deux versions optimisées, streaming et club, avec contrôle des graves et une série de corrections incluse.",
    imageUrl: serviceImages.mastering,
    price: 89,
    sellerId: "waveform-studio",
    locationId: "lyon-2",
    ratingScore: 4.9,
    ratingCount: 214,
    service: { kind: "production", format: "À distance", durationLabel: "1 titre", deliveryLabel: "Livré sous 72 h", nextAvailability: "20 juillet" },
  },
  {
    id: "wave2-service-mastering-vinyl-marseille",
    category: "Mix & mastering",
    brand: "Camille Mix",
    model: "Vinyl Premaster",
    title: "Prémaster vinyle · Face A / Face B",
    description: "Préparation dynamique et fréquentielle pour gravure, séquençage des faces et fichiers conformes au pressage.",
    imageUrl: serviceImages.mastering,
    price: 320,
    sellerId: "camille-mix",
    locationId: "marseille-cours-julien",
    ratingScore: 4.9,
    ratingCount: 83,
    service: { kind: "production", format: "À distance + appel", durationLabel: "EP ou album court", deliveryLabel: "Livré sous 6 jours", nextAvailability: "24 juillet" },
  },
  {
    id: "wave2-service-mastering-stems-montpellier",
    category: "Mix & mastering",
    brand: "Waveform Studio",
    model: "Stem Mastering",
    title: "Stem mastering · 6 groupes",
    description: "Mastering à partir de six stems pour reprendre l’équilibre du morceau tout en conservant l’intention du mix.",
    imageUrl: serviceImages.mastering,
    price: 145,
    sellerId: "waveform-studio",
    locationId: "montpellier-beaux-arts",
    ratingScore: 4.9,
    ratingCount: 126,
    service: { kind: "production", format: "À distance", durationLabel: "1 titre · 6 stems", deliveryLabel: "Livré sous 4 jours", nextAvailability: "21 juillet" },
  },
  {
    id: "wave2-service-vocal-coaching-paris",
    category: "Cours & coaching",
    brand: "Élise Tones",
    model: "Vocal Performance",
    title: "Coaching vocal · Interprétation studio",
    description: "Travail du souffle, placement et intention face au micro pour préparer une prise exigeante ou un live.",
    imageUrl: serviceImages.vocal,
    price: 72,
    sellerId: "elise-tones",
    locationId: "paris-11",
    ratingScore: 5,
    ratingCount: 193,
    service: { kind: "coaching", format: "En studio", durationLabel: "1 h 30", deliveryLabel: "Compte-rendu inclus", nextAvailability: "20 juillet" },
  },
  {
    id: "wave2-service-vocal-technique-lyon",
    category: "Cours & coaching",
    brand: "Élise Tones",
    model: "Vocal Technique",
    title: "Technique vocale · Cycle de 4 séances",
    description: "Cycle progressif pour développer soutien, justesse, endurance et confort dans votre registre artistique.",
    imageUrl: serviceImages.vocal,
    price: 235,
    sellerId: "elise-tones",
    locationId: "lyon-2",
    ratingScore: 4.9,
    ratingCount: 151,
    service: { kind: "coaching", format: "Présentiel ou visio", durationLabel: "4 × 1 h", deliveryLabel: "Programme personnalisé", nextAvailability: "23 juillet" },
  },
  {
    id: "wave2-service-vocal-audition-lille",
    category: "Cours & coaching",
    brand: "Session Club",
    model: "Audition Ready",
    title: "Préparation audition · Voix & présence",
    description: "Sélection du morceau, direction vocale, présence et simulation filmée pour arriver prêt à l’audition.",
    imageUrl: serviceImages.vocal,
    price: 110,
    sellerId: "session-club",
    locationId: "lille-wazemmes",
    ratingScore: 4.9,
    ratingCount: 88,
    service: { kind: "coaching", format: "En studio", durationLabel: "2 h", deliveryLabel: "Vidéo de travail incluse", nextAvailability: "25 juillet" },
  },
  {
    id: "wave2-service-vocal-direction-nice",
    category: "Cours & coaching",
    brand: "Noémie Sound",
    model: "Vocal Direction Session",
    title: "Direction vocale · Session d’enregistrement",
    description: "Accompagnement pendant vos prises pour harmonies, intentions, diction et choix des meilleures performances.",
    imageUrl: serviceImages.vocal,
    price: 160,
    sellerId: "noemie-sound",
    locationId: "nice-port",
    ratingScore: 4.9,
    ratingCount: 97,
    service: { kind: "coaching", format: "Dans votre studio", durationLabel: "Demi-journée", deliveryLabel: "Notes de direction incluses", nextAvailability: "22 juillet" },
  },
  {
    id: "wave2-service-live-sound-nantes",
    category: "Mix & mastering",
    brand: "Atlas Audio",
    model: "Live Soundcheck",
    title: "Ingénieur son live · Concert club",
    description: "Préparation du patch, balances, façade et suivi du concert pour un groupe jusqu’à huit musiciens.",
    imageUrl: serviceImages.liveSound,
    price: 390,
    sellerId: "atlas-audio",
    locationId: "nantes-centre",
    ratingScore: 4.9,
    ratingCount: 142,
    service: { kind: "production", format: "Sur site", durationLabel: "Balance + concert", deliveryLabel: "Fiche technique préparée", nextAvailability: "27 juillet" },
  },
  {
    id: "wave2-service-live-tour-marseille",
    category: "Mix & mastering",
    brand: "Atlas Audio",
    model: "Tour FOH Day",
    title: "Mix façade · Date de tournée",
    description: "Prise en charge complète d’une date, coordination technique locale, balance et mix façade pendant le show.",
    imageUrl: serviceImages.liveSound,
    price: 480,
    sellerId: "atlas-audio",
    locationId: "marseille-cours-julien",
    ratingScore: 4.9,
    ratingCount: 109,
    service: { kind: "production", format: "Sur site", durationLabel: "1 journée", deliveryLabel: "Préproduction incluse", nextAvailability: "29 juillet" },
  },
  {
    id: "wave2-service-live-system-bordeaux",
    category: "Mix & mastering",
    brand: "Broadcast Lab",
    model: "Live System Design",
    title: "Conception son live · Petite salle",
    description: "Dimensionnement, patch, implantation et réglage d’un système pour showcase, lancement ou événement musical.",
    imageUrl: serviceImages.liveSound,
    price: 290,
    sellerId: "broadcast-lab",
    locationId: "bordeaux-chartrons",
    ratingScore: 4.8,
    ratingCount: 76,
    service: { kind: "production", format: "Audit + intervention", durationLabel: "Jusqu’à 150 personnes", deliveryLabel: "Plan technique fourni", nextAvailability: "24 juillet" },
  },
  {
    id: "wave2-service-luthier-setup-paris",
    category: "Guitares",
    brand: "Guitar House",
    model: "Precision Setup",
    title: "Setup guitare complet · Jeu sur mesure",
    description: "Réglage manche, action, intonation, sillet et électronique selon votre tirant et votre manière de jouer.",
    imageUrl: serviceImages.luthier,
    price: 95,
    sellerId: "guitar-house",
    locationId: "paris-11",
    ratingScore: 5,
    ratingCount: 231,
    service: { kind: "production", format: "Atelier", durationLabel: "1 instrument", deliveryLabel: "Prêt sous 3 jours", nextAvailability: "21 juillet" },
  },
  {
    id: "wave2-service-luthier-frets-lille",
    category: "Guitares",
    brand: "Guitar House",
    model: "Fret Level Pro",
    title: "Planification des frettes · Guitare ou basse",
    description: "Diagnostic, planification, polissage et réglage final pour retrouver une action basse sans frise.",
    imageUrl: serviceImages.luthier,
    price: 175,
    sellerId: "guitar-house",
    locationId: "lille-wazemmes",
    ratingScore: 4.9,
    ratingCount: 118,
    service: { kind: "production", format: "Atelier", durationLabel: "1 instrument", deliveryLabel: "Prêt sous 5 jours", nextAvailability: "25 juillet" },
  },
  {
    id: "wave2-service-luthier-tour-strasbourg",
    category: "Guitares",
    brand: "Backline Atlas",
    model: "Tour Prep",
    title: "Préparation guitare tournée · Contrôle total",
    description: "Contrôle mécanique et électronique, pièces d’usure, nettoyage et réglage stable avant plusieurs dates.",
    imageUrl: serviceImages.luthier,
    price: 135,
    sellerId: "atlas-audio",
    locationId: "strasbourg-krutenau",
    ratingScore: 4.9,
    ratingCount: 86,
    service: { kind: "production", format: "Atelier", durationLabel: "1 instrument", deliveryLabel: "Rapport de contrôle fourni", nextAvailability: "23 juillet" },
  },
  {
    id: "wave2-service-production-mentoring-paris",
    category: "Cours & coaching",
    brand: "Noémie Sound",
    model: "Producer Mentoring",
    title: "Mentorat production · De l’idée au master",
    description: "Session individuelle sur arrangement, sound design, workflow et finitions à partir de votre projet en cours.",
    imageUrl: serviceImages.production,
    price: 120,
    sellerId: "noemie-sound",
    locationId: "paris-11",
    ratingScore: 5,
    ratingCount: 177,
    service: { kind: "coaching", format: "Studio ou visio", durationLabel: "2 h", deliveryLabel: "Plan d’action personnalisé", nextAvailability: "20 juillet" },
  },
  {
    id: "wave2-service-beat-coaching-marseille",
    category: "Cours & coaching",
    brand: "Rhythm Workshop",
    model: "Beat Lab Intensive",
    title: "Coaching beatmaking · Session intensive",
    description: "Groove, drums, basses, transitions et arrangement travaillés directement dans votre session de production.",
    imageUrl: serviceImages.production,
    price: 88,
    sellerId: "rhythm-workshop",
    locationId: "marseille-cours-julien",
    ratingScore: 4.9,
    ratingCount: 146,
    service: { kind: "coaching", format: "En studio", durationLabel: "2 h", deliveryLabel: "Projet annoté inclus", nextAvailability: "22 juillet" },
  },
  {
    id: "wave2-service-arrangement-rennes",
    category: "Cours & coaching",
    brand: "Noémie Sound",
    model: "Arrangement Clinic",
    title: "Clinic arrangement · Terminer son morceau",
    description: "Diagnostic de structure et décisions concrètes pour transformer une boucle prometteuse en titre abouti.",
    imageUrl: serviceImages.production,
    price: 78,
    sellerId: "noemie-sound",
    locationId: "rennes-centre",
    ratingScore: 4.9,
    ratingCount: 119,
    service: { kind: "coaching", format: "Visio", durationLabel: "1 h 30", deliveryLabel: "Roadmap fournie après session", nextAvailability: "21 juillet" },
  },
  {
    id: "wave2-service-stream-live-paris",
    category: "Rooms & studios",
    brand: "Broadcast Lab",
    model: "MultiCam Live Session",
    title: "Captation live multicam · Session complète",
    description: "Réalisation multicam, mix image, enregistrement et direction technique pour une session musicale en direct.",
    imageUrl: serviceImages.streaming,
    price: 690,
    sellerId: "broadcast-lab",
    locationId: "paris-11",
    ratingScore: 4.9,
    ratingCount: 104,
    service: { kind: "room", format: "Studio équipé", durationLabel: "Demi-journée", deliveryLabel: "Master vidéo livré sous 5 jours", nextAvailability: "26 juillet" },
  },
  {
    id: "wave2-service-stream-acoustic-nantes",
    category: "Rooms & studios",
    brand: "Room Collective",
    model: "Acoustic Live Capture",
    title: "Session acoustique filmée · 3 caméras",
    description: "Captation sobre et intimiste d’un artiste ou duo, prise de son multipiste et montage d’une performance complète.",
    imageUrl: serviceImages.streaming,
    price: 420,
    sellerId: "room-collective",
    locationId: "nantes-centre",
    ratingScore: 4.9,
    ratingCount: 81,
    service: { kind: "room", format: "Studio équipé", durationLabel: "3 h", deliveryLabel: "Vidéo montée + stems", nextAvailability: "24 juillet" },
  },
  {
    id: "wave2-service-stream-release-bordeaux",
    category: "Rooms & studios",
    brand: "Broadcast Lab",
    model: "Release Live Stream",
    title: "Live stream lancement · Réalisation complète",
    description: "Préproduction, habillage, multicam et diffusion d’un showcase de sortie avec enregistrement de secours.",
    imageUrl: serviceImages.streaming,
    price: 840,
    sellerId: "broadcast-lab",
    locationId: "bordeaux-chartrons",
    ratingScore: 4.9,
    ratingCount: 69,
    service: { kind: "room", format: "Sur site ou studio", durationLabel: "1 événement", deliveryLabel: "Replay livré sous 72 h", nextAvailability: "30 juillet" },
  },
];

export const marketWave2RentalProducts: MarketProduct[] = rentalSeeds.map(createRentalProduct);

export const marketWave2ServiceProducts: MarketProduct[] = serviceSeeds.map(createServiceProduct);

export const marketWave2RentalServiceProducts: MarketProduct[] = [
  ...marketWave2RentalProducts,
  ...marketWave2ServiceProducts,
];

export const MARKET_WAVE2_RENTAL_SERVICE_COUNTS = {
  rental: marketWave2RentalProducts.length,
  services: marketWave2ServiceProducts.length,
  total: marketWave2RentalServiceProducts.length,
} as const;
