import type {
  MarketCategory,
  MarketProduct,
} from "./marketDemoData";

type CollectiveProductSeed = {
  id: string;
  category: MarketCategory;
  brand: string;
  model: string;
  title: string;
  pitch: string;
  imageUrl: string;
  price: number;
  retailPrice: number;
  sellerId: string;
  locationId: string;
  joined: number;
  target: number;
  daysRemaining: number;
  badge?: string;
};

const generatedImageRoot = "/images/market/expansion/collective";

const collectiveImages = {
  synthBundle: `${generatedImageRoot}/collective-synth-bundle.webp`,
  homeStudioBundle: `${generatedImageRoot}/collective-home-studio-bundle.webp`,
  podcastBundle: `${generatedImageRoot}/collective-podcast-bundle.webp`,
  guitarStageBundle: `${generatedImageRoot}/collective-guitar-stage-bundle.webp`,
  electronicDrumBundle: `${generatedImageRoot}/collective-edrum-bundle.webp`,
  djBundle: `${generatedImageRoot}/collective-dj-bundle.webp`,
  fieldRecordingBundle: `${generatedImageRoot}/collective-field-recording-bundle.webp`,
  beatmakingBundle: `${generatedImageRoot}/collective-beatmaking-bundle.webp`,
  monitoringBundle: `${generatedImageRoot}/collective-monitoring-bundle.webp`,
} as const;

const existingMarketImage = (filename: string) => `/images/market/${filename}`;

const collectiveSeeds = [
  // Synthétiseurs : instruments, grooveboxes et packs nomades.
  {
    id: "collective-exp-sequential-take5-duo",
    category: "Synthétiseurs",
    brand: "Sequential",
    model: "Take 5 Duo Pack",
    title: "Sequential Take 5 · Duo Pack communauté",
    pitch: "Housse renforcée, pédale et câblage inclus au palier collectif.",
    imageUrl: collectiveImages.synthBundle,
    price: 1249,
    retailPrice: 1499,
    sellerId: "synth-district",
    locationId: "paris-11",
    joined: 38,
    target: 50,
    daysRemaining: 5,
    badge: "76 % atteint",
  },
  {
    id: "collective-exp-hydrasynth-explorer",
    category: "Synthétiseurs",
    brand: "ASM",
    model: "Hydrasynth Explorer Creator Pack",
    title: "Hydrasynth Explorer · Pack créateurs",
    pitch: "Pack nomade avec alimentation, housse et banque de sons partagée.",
    imageUrl: existingMarketImage("arturia-minifreak.jpg"),
    price: 519,
    retailPrice: 649,
    sellerId: "modular-corner",
    locationId: "rennes-centre",
    joined: 72,
    target: 90,
    daysRemaining: 3,
    badge: "Fin imminente",
  },
  {
    id: "collective-exp-novation-peak-studio",
    category: "Synthétiseurs",
    brand: "Novation",
    model: "Peak Studio Pack",
    title: "Novation Peak · Pack studio collectif",
    pitch: "Support incliné et câbles symétriques débloqués dès vingt participants.",
    imageUrl: existingMarketImage("korg-minilogue-xd.jpg"),
    price: 1249,
    retailPrice: 1499,
    sellerId: "synth-district",
    locationId: "lyon-2",
    joined: 19,
    target: 28,
    daysRemaining: 8,
    badge: "Support offert",
  },
  {
    id: "collective-exp-elektron-digitone-ii",
    category: "Synthétiseurs",
    brand: "Elektron",
    model: "Digitone II Community Edition",
    title: "Elektron Digitone II · Édition communauté",
    pitch: "Capot rigide et carte de samples Meewav compris dans la commande.",
    imageUrl: existingMarketImage("sampler-workstation-graphite-v1.webp"),
    price: 849,
    retailPrice: 999,
    sellerId: "modular-corner",
    locationId: "strasbourg-krutenau",
    joined: 44,
    target: 56,
    daysRemaining: 4,
    badge: "Capot débloqué",
  },
  {
    id: "collective-exp-yamaha-reface-cp-club",
    category: "Synthétiseurs",
    brand: "Yamaha",
    model: "Reface CP Club Pack",
    title: "Yamaha Reface CP · Pack club",
    pitch: "Mini-clavier vintage avec housse, pédale et adaptateur de voyage.",
    imageUrl: existingMarketImage("nord-stage-4.jpg"),
    price: 349,
    retailPrice: 429,
    sellerId: "atlas-audio",
    locationId: "toulouse-saint-cyprien",
    joined: 83,
    target: 100,
    daysRemaining: 2,
    badge: "Plus que 17 places",
  },
  {
    id: "collective-exp-op1-field-creator",
    category: "Synthétiseurs",
    brand: "Teenage Engineering",
    model: "OP-1 Field Creator Pack",
    title: "OP-1 Field · Commande créateurs",
    pitch: "Étui rigide, câble USB-C tressé et atelier de prise en main inclus.",
    imageUrl: collectiveImages.beatmakingBundle,
    price: 1699,
    retailPrice: 1999,
    sellerId: "session-club",
    locationId: "nantes-centre",
    joined: 16,
    target: 24,
    daysRemaining: 7,
    badge: "Atelier inclus",
  },

  // Interfaces audio : du home studio au rack collectif.
  {
    id: "collective-exp-ssl2-plus-mkii",
    category: "Interfaces audio",
    brand: "Solid State Logic",
    model: "SSL 2+ MKII Creator Pack",
    title: "SSL 2+ MKII · Pack créateur collectif",
    pitch: "Interface, casque fermé et câbles micro réunis pour démarrer sans délai.",
    imageUrl: collectiveImages.homeStudioBundle,
    price: 279,
    retailPrice: 349,
    sellerId: "studio-supply",
    locationId: "bordeaux-chartrons",
    joined: 54,
    target: 70,
    daysRemaining: 6,
    badge: "Casque inclus",
  },
  {
    id: "collective-exp-motu-m4-duo",
    category: "Interfaces audio",
    brand: "MOTU",
    model: "M4 Duo Session",
    title: "MOTU M4 · Offre duo session",
    pitch: "Deux entrées supplémentaires et un hub USB alimenté au palier final.",
    imageUrl: existingMarketImage("audient-id14.jpg"),
    price: 249,
    retailPrice: 319,
    sellerId: "waveform-studio",
    locationId: "nice-port",
    joined: 42,
    target: 50,
    daysRemaining: 3,
    badge: "84 % atteint",
  },
  {
    id: "collective-exp-ua-volt476-producer",
    category: "Interfaces audio",
    brand: "Universal Audio",
    model: "Volt 476 Producer Pack",
    title: "Volt 476 · Pack producteurs",
    pitch: "Interface quatre entrées, casque et micro à condensateur au tarif négocié.",
    imageUrl: existingMarketImage("apollo-twin-x.jpg"),
    price: 319,
    retailPrice: 399,
    sellerId: "atlas-audio",
    locationId: "dijon-centre",
    joined: 61,
    target: 80,
    daysRemaining: 5,
    badge: "Pack complet",
  },
  {
    id: "collective-exp-focusrite-18i20-hub",
    category: "Interfaces audio",
    brand: "Focusrite",
    model: "Scarlett 18i20 Studio Hub",
    title: "Scarlett 18i20 · Hub studio collectif",
    pitch: "Rack huit préamplis avec patch de câbles et extension ADAT négociée.",
    imageUrl: existingMarketImage("focusrite-scarlett-2i2.jpg"),
    price: 529,
    retailPrice: 649,
    sellerId: "broadcast-lab",
    locationId: "lille-wazemmes",
    joined: 27,
    target: 36,
    daysRemaining: 8,
    badge: "Extension ADAT",
  },
  {
    id: "collective-exp-rme-babyface-pro-fs",
    category: "Interfaces audio",
    brand: "RME",
    model: "Babyface Pro FS Club Pack",
    title: "RME Babyface Pro FS · Pack club",
    pitch: "Interface nomade avec étui, breakout sécurisé et garantie étendue.",
    imageUrl: collectiveImages.homeStudioBundle,
    price: 799,
    retailPrice: 949,
    sellerId: "waveform-studio",
    locationId: "clermont-jaude",
    joined: 14,
    target: 18,
    daysRemaining: 4,
    badge: "Garantie 4 ans",
  },

  // Microphones : voix, scène, podcast et tournage.
  {
    id: "collective-exp-lewitt-lct440-pair",
    category: "Microphones",
    brand: "Lewitt",
    model: "LCT 440 PURE Stereo Pair",
    title: "Lewitt LCT 440 PURE · Paire collective",
    pitch: "Deux micros appairés, suspensions et barre stéréo dans un même lot.",
    imageUrl: collectiveImages.homeStudioBundle,
    price: 429,
    retailPrice: 558,
    sellerId: "broadcast-lab",
    locationId: "angers-doutre",
    joined: 34,
    target: 44,
    daysRemaining: 6,
    badge: "Paire appairée",
  },
  {
    id: "collective-exp-shure-mv7plus-duo",
    category: "Microphones",
    brand: "Shure",
    model: "MV7+ Podcast Duo",
    title: "Shure MV7+ · Duo podcast collectif",
    pitch: "Deux micros, bras de table et casques pour lancer une émission à deux.",
    imageUrl: collectiveImages.podcastBundle,
    price: 499,
    retailPrice: 638,
    sellerId: "broadcast-lab",
    locationId: "paris-11",
    joined: 47,
    target: 60,
    daysRemaining: 4,
    badge: "Bras inclus",
  },
  {
    id: "collective-exp-rode-wireless-pro",
    category: "Microphones",
    brand: "RØDE",
    model: "Wireless PRO Creator Kit",
    title: "RØDE Wireless PRO · Kit créateurs",
    pitch: "Deux émetteurs, lavaliers, timecode et étui de charge au prix communauté.",
    imageUrl: collectiveImages.fieldRecordingBundle,
    price: 349,
    retailPrice: 429,
    sellerId: "room-collective",
    locationId: "bordeaux-chartrons",
    joined: 76,
    target: 90,
    daysRemaining: 2,
    badge: "84 % atteint",
  },
  {
    id: "collective-exp-aston-spirit-vocal-pair",
    category: "Microphones",
    brand: "Aston",
    model: "Spirit Vocal Pair",
    title: "Aston Spirit · Duo vocal communauté",
    pitch: "Deux capsules polyvalentes avec suspensions et filtres anti-pop métalliques.",
    imageUrl: existingMarketImage("neumann-tlm103.jpg"),
    price: 479,
    retailPrice: 598,
    sellerId: "waveform-studio",
    locationId: "montpellier-beaux-arts",
    joined: 23,
    target: 32,
    daysRemaining: 9,
    badge: "Filtres offerts",
  },
  {
    id: "collective-exp-sennheiser-e935-five",
    category: "Microphones",
    brand: "Sennheiser",
    model: "e 935 Stage Five Pack",
    title: "Sennheiser e 935 · Lot scène x5",
    pitch: "Cinq micros de scène avec pinces, bonnettes et mallette commune.",
    imageUrl: collectiveImages.podcastBundle,
    price: 699,
    retailPrice: 895,
    sellerId: "session-club",
    locationId: "marseille-cours-julien",
    joined: 18,
    target: 24,
    daysRemaining: 7,
    badge: "Mallette incluse",
  },

  // Casques : lots pour studios, écoles et collectifs.
  {
    id: "collective-exp-beyerdynamic-dt990-six",
    category: "Casques",
    brand: "Beyerdynamic",
    model: "DT 990 Pro Six Pack",
    title: "Beyerdynamic DT 990 Pro · Lot x6",
    pitch: "Six casques ouverts avec supports et coussinets de rechange.",
    imageUrl: existingMarketImage("beyerdynamic-dt770.jpg"),
    price: 699,
    retailPrice: 954,
    sellerId: "studio-supply",
    locationId: "strasbourg-krutenau",
    joined: 66,
    target: 80,
    daysRemaining: 3,
    badge: "-27 %",
  },
  {
    id: "collective-exp-ath-m50x-five",
    category: "Casques",
    brand: "Audio-Technica",
    model: "ATH-M50x Studio Five",
    title: "Audio-Technica ATH-M50x · Lot studio x5",
    pitch: "Cinq casques fermés, pochettes nominatives et adaptateurs vissables.",
    imageUrl: existingMarketImage("audio-technica-m50x.jpg"),
    price: 649,
    retailPrice: 845,
    sellerId: "atlas-audio",
    locationId: "rouen-rive-droite",
    joined: 49,
    target: 64,
    daysRemaining: 6,
    badge: "Pochettes incluses",
  },
  {
    id: "collective-exp-sennheiser-hd600-circle",
    category: "Casques",
    brand: "Sennheiser",
    model: "HD 600 Listening Circle",
    title: "Sennheiser HD 600 · Cercle d’écoute",
    pitch: "Casques de référence négociés avec câble court et support de bureau.",
    imageUrl: collectiveImages.monitoringBundle,
    price: 319,
    retailPrice: 399,
    sellerId: "waveform-studio",
    locationId: "grenoble-bouchayer",
    joined: 31,
    target: 40,
    daysRemaining: 5,
    badge: "Câble bonus",
  },
  {
    id: "collective-exp-aiaiai-tma2-team",
    category: "Casques",
    brand: "AIAIAI",
    model: "TMA-2 Studio Team Pack",
    title: "AIAIAI TMA-2 Studio · Pack équipe x4",
    pitch: "Quatre casques modulaires avec pièces interchangeables et étuis souples.",
    imageUrl: collectiveImages.beatmakingBundle,
    price: 799,
    retailPrice: 1036,
    sellerId: "session-club",
    locationId: "lyon-2",
    joined: 39,
    target: 48,
    daysRemaining: 4,
    badge: "Modules offerts",
  },

  // Guitares : instruments, amplis et pedalboards prêts pour la scène.
  {
    id: "collective-exp-fender-player2-tele-stage",
    category: "Guitares",
    brand: "Fender",
    model: "Player II Telecaster Stage Pack",
    title: "Fender Player II Tele · Pack scène",
    pitch: "Guitare, housse, sangle et réglage complet avant expédition groupée.",
    imageUrl: existingMarketImage("fender-telecaster-used.jpg"),
    price: 749,
    retailPrice: 929,
    sellerId: "guitar-house",
    locationId: "nantes-centre",
    joined: 26,
    target: 34,
    daysRemaining: 6,
    badge: "Réglage offert",
  },
  {
    id: "collective-exp-prs-se-dgt-community",
    category: "Guitares",
    brand: "PRS",
    model: "SE DGT Community Pack",
    title: "PRS SE DGT · Pack communauté",
    pitch: "Modèle signature avec housse premium et jeu de cordes supplémentaire.",
    imageUrl: existingMarketImage("prs-se-custom-24-used.jpg"),
    price: 849,
    retailPrice: 1049,
    sellerId: "guitar-house",
    locationId: "nice-port",
    joined: 17,
    target: 24,
    daysRemaining: 8,
    badge: "Cordes incluses",
  },
  {
    id: "collective-exp-yamaha-revstar-standard",
    category: "Guitares",
    brand: "Yamaha",
    model: "Revstar Standard Stage Kit",
    title: "Yamaha Revstar Standard · Kit scène",
    pitch: "Guitare, petit ampli à lampes et pedalboard réunis dans un lot négocié.",
    imageUrl: collectiveImages.guitarStageBundle,
    price: 999,
    retailPrice: 1299,
    sellerId: "guitar-house",
    locationId: "toulouse-saint-cyprien",
    joined: 37,
    target: 45,
    daysRemaining: 3,
    badge: "-23 %",
  },
  {
    id: "collective-exp-gretsch-electromatic-club",
    category: "Guitares",
    brand: "Gretsch",
    model: "Electromatic Club Bundle",
    title: "Gretsch Electromatic · Bundle club",
    pitch: "Demi-caisse, étui rigide et sangle cuir au tarif du collectif.",
    imageUrl: collectiveImages.guitarStageBundle,
    price: 699,
    retailPrice: 899,
    sellerId: "guitar-house",
    locationId: "lille-wazemmes",
    joined: 21,
    target: 28,
    daysRemaining: 5,
    badge: "Étui rigide inclus",
  },
  {
    id: "collective-exp-pedalboard-essentials-five",
    category: "Guitares",
    brand: "StageLab",
    model: "Pedalboard Essentials Five",
    title: "Pedalboard Essentials · Pack de cinq effets",
    pitch: "Cinq effets essentiels, alimentation isolée, patchs et flight case compact.",
    imageUrl: collectiveImages.guitarStageBundle,
    price: 449,
    retailPrice: 629,
    sellerId: "guitar-house",
    locationId: "angers-doutre",
    joined: 58,
    target: 70,
    daysRemaining: 2,
    badge: "-29 %",
  },

  // Batteries électroniques et percussion hybride.
  {
    id: "collective-exp-roland-td27-stage",
    category: "Batteries électroniques",
    brand: "Roland",
    model: "TD-27KV2 Stage Bundle",
    title: "Roland TD-27KV2 · Bundle scène",
    pitch: "Kit mesh, siège, pédales et casque réunis pour les batteurs du collectif.",
    imageUrl: collectiveImages.electronicDrumBundle,
    price: 2799,
    retailPrice: 3299,
    sellerId: "rhythm-workshop",
    locationId: "lille-wazemmes",
    joined: 13,
    target: 18,
    daysRemaining: 9,
    badge: "Siège inclus",
  },
  {
    id: "collective-exp-yamaha-dtx8k-club",
    category: "Batteries électroniques",
    brand: "Yamaha",
    model: "DTX8K Club Pack",
    title: "Yamaha DTX8K · Pack club",
    pitch: "Configuration complète avec double pédale et monitoring fermé.",
    imageUrl: collectiveImages.electronicDrumBundle,
    price: 2499,
    retailPrice: 2999,
    sellerId: "rhythm-workshop",
    locationId: "marseille-cours-julien",
    joined: 16,
    target: 22,
    daysRemaining: 7,
    badge: "Double pédale",
  },
  {
    id: "collective-exp-alesis-strata-prime",
    category: "Batteries électroniques",
    brand: "Alesis",
    model: "Strata Prime Community Kit",
    title: "Alesis Strata Prime · Kit communauté",
    pitch: "Module tactile, quatre cymbales et accessoires de jeu au palier premium.",
    imageUrl: existingMarketImage("roland-td17kvx.jpg"),
    price: 2899,
    retailPrice: 3499,
    sellerId: "rhythm-workshop",
    locationId: "clermont-jaude",
    joined: 9,
    target: 12,
    daysRemaining: 4,
    badge: "Palier premium",
  },
  {
    id: "collective-exp-spdsx-pro-percussion",
    category: "Batteries électroniques",
    brand: "Roland",
    model: "SPD-SX PRO Percussion Pack",
    title: "Roland SPD-SX PRO · Pack percussion",
    pitch: "Pad de sampling, stand, trigger et housse pour enrichir un set live.",
    imageUrl: collectiveImages.beatmakingBundle,
    price: 899,
    retailPrice: 1099,
    sellerId: "rhythm-workshop",
    locationId: "rennes-centre",
    joined: 33,
    target: 42,
    daysRemaining: 5,
    badge: "Trigger offert",
  },

  // DJ & vinyle : contrôleurs, platines et mixage club.
  {
    id: "collective-exp-alphatheta-xdjaz-club",
    category: "DJ & vinyle",
    brand: "AlphaTheta",
    model: "XDJ-AZ Club Flight Pack",
    title: "AlphaTheta XDJ-AZ · Flight Pack collectif",
    pitch: "Système autonome, flight case et paire de moniteurs au tarif négocié.",
    imageUrl: collectiveImages.djBundle,
    price: 2999,
    retailPrice: 3499,
    sellerId: "vinyl-circuit",
    locationId: "paris-11",
    joined: 18,
    target: 24,
    daysRemaining: 6,
    badge: "Flight case inclus",
  },
  {
    id: "collective-exp-pioneer-omnis-duo",
    category: "DJ & vinyle",
    brand: "Pioneer DJ",
    model: "OMNIS-DUO Creator Pack",
    title: "Pioneer OMNIS-DUO · Pack créateurs",
    pitch: "Contrôleur autonome nomade avec housse, casque et batterie externe.",
    imageUrl: existingMarketImage("pioneer-ddj-flx10.jpg"),
    price: 1199,
    retailPrice: 1499,
    sellerId: "vinyl-circuit",
    locationId: "bordeaux-chartrons",
    joined: 31,
    target: 40,
    daysRemaining: 4,
    badge: "Batterie externe",
  },
  {
    id: "collective-exp-rane-four-battle",
    category: "DJ & vinyle",
    brand: "Rane",
    model: "FOUR Battle Bundle",
    title: "Rane FOUR · Battle Bundle communauté",
    pitch: "Contrôleur quatre voies avec flight case et monitoring de cabine.",
    imageUrl: collectiveImages.djBundle,
    price: 1399,
    retailPrice: 1699,
    sellerId: "vinyl-circuit",
    locationId: "lyon-2",
    joined: 22,
    target: 30,
    daysRemaining: 8,
    badge: "Monitoring inclus",
  },
  {
    id: "collective-exp-technics-mk7-twin",
    category: "DJ & vinyle",
    brand: "Technics",
    model: "SL-1200MK7 Twin Deck",
    title: "Technics SL-1200MK7 · Paire club",
    pitch: "Deux platines appairées avec cellules, capots et tapis Meewav.",
    imageUrl: existingMarketImage("technics-sl1200.jpg"),
    price: 1699,
    retailPrice: 2198,
    sellerId: "vinyl-circuit",
    locationId: "marseille-cours-julien",
    joined: 27,
    target: 32,
    daysRemaining: 2,
    badge: "84 % atteint",
  },
  {
    id: "collective-exp-xone96-club-mixer",
    category: "DJ & vinyle",
    brand: "Allen & Heath",
    model: "Xone:96 Club Mixer Pack",
    title: "Xone:96 · Mixer club collectif",
    pitch: "Console analogique, housse rigide et câblage cabine premium.",
    imageUrl: collectiveImages.djBundle,
    price: 1599,
    retailPrice: 1999,
    sellerId: "vinyl-circuit",
    locationId: "strasbourg-krutenau",
    joined: 12,
    target: 16,
    daysRemaining: 5,
    badge: "Câblage premium",
  },

  // Contrôleurs MIDI et stations de beatmaking.
  {
    id: "collective-exp-arturia-keylab61-producer",
    category: "Contrôleurs MIDI",
    brand: "Arturia",
    model: "KeyLab 61 mk3 Producer Pack",
    title: "Arturia KeyLab 61 mk3 · Pack producteurs",
    pitch: "Clavier maître, stand et pédale avec atelier de mapping collectif.",
    imageUrl: collectiveImages.beatmakingBundle,
    price: 499,
    retailPrice: 649,
    sellerId: "modular-corner",
    locationId: "montpellier-beaux-arts",
    joined: 63,
    target: 80,
    daysRemaining: 6,
    badge: "Atelier mapping",
  },
  {
    id: "collective-exp-launchkey49-stage",
    category: "Contrôleurs MIDI",
    brand: "Novation",
    model: "Launchkey 49 mk4 Stage Pack",
    title: "Novation Launchkey 49 · Pack scène",
    pitch: "Contrôleur, housse, pédale et hub USB pour les configurations mobiles.",
    imageUrl: existingMarketImage("m-audio-oxygen-pro-49.jpg"),
    price: 249,
    retailPrice: 329,
    sellerId: "modular-corner",
    locationId: "rouen-rive-droite",
    joined: 71,
    target: 90,
    daysRemaining: 3,
    badge: "-24 %",
  },
  {
    id: "collective-exp-push3-standalone",
    category: "Contrôleurs MIDI",
    brand: "Ableton",
    model: "Push 3 Standalone Community",
    title: "Push 3 Standalone · Offre communauté",
    pitch: "Station autonome avec étui, support incliné et pack de samples partagé.",
    imageUrl: existingMarketImage("sampler-workstation-graphite-v1.webp"),
    price: 1699,
    retailPrice: 1999,
    sellerId: "session-club",
    locationId: "nantes-centre",
    joined: 19,
    target: 26,
    daysRemaining: 7,
    badge: "Samples inclus",
  },
  {
    id: "collective-exp-kontrol-s61-composer",
    category: "Contrôleurs MIDI",
    brand: "Native Instruments",
    model: "Kontrol S61 Composer Pack",
    title: "Kontrol S61 · Pack compositeurs",
    pitch: "Clavier polyphonique avec support, pédale et SSD de bibliothèque.",
    imageUrl: collectiveImages.beatmakingBundle,
    price: 699,
    retailPrice: 899,
    sellerId: "atlas-audio",
    locationId: "dijon-centre",
    joined: 28,
    target: 36,
    daysRemaining: 4,
    badge: "SSD inclus",
  },

  // Monitoring : paires appairées et calibration de pièce.
  {
    id: "collective-exp-genelec-8030c-pair",
    category: "Monitoring",
    brand: "Genelec",
    model: "8030C Matched Pair",
    title: "Genelec 8030C · Paire appairée collective",
    pitch: "Deux enceintes mesurées, supports isolants et câbles symétriques.",
    imageUrl: collectiveImages.monitoringBundle,
    price: 999,
    retailPrice: 1298,
    sellerId: "waveform-studio",
    locationId: "paris-11",
    joined: 41,
    target: 52,
    daysRemaining: 5,
    badge: "Mesure incluse",
  },
  {
    id: "collective-exp-neumann-kh120ii-pair",
    category: "Monitoring",
    brand: "Neumann",
    model: "KH 120 II Calibration Pack",
    title: "Neumann KH 120 II · Pack calibration",
    pitch: "Paire de moniteurs, micro de mesure et calibration guidée à distance.",
    imageUrl: collectiveImages.monitoringBundle,
    price: 1499,
    retailPrice: 1899,
    sellerId: "broadcast-lab",
    locationId: "bordeaux-chartrons",
    joined: 24,
    target: 30,
    daysRemaining: 3,
    badge: "80 % atteint",
  },
  {
    id: "collective-exp-adam-a7v-stereo",
    category: "Monitoring",
    brand: "Adam Audio",
    model: "A7V Stereo Room Pack",
    title: "Adam A7V · Pack stéréo communauté",
    pitch: "Paire contrôlée avec isolation, calibration et garantie étendue.",
    imageUrl: existingMarketImage("adam-a7x-used.jpg"),
    price: 1199,
    retailPrice: 1498,
    sellerId: "waveform-studio",
    locationId: "clermont-jaude",
    joined: 35,
    target: 46,
    daysRemaining: 6,
    badge: "Garantie étendue",
  },
  {
    id: "collective-exp-focal-shape65-pair",
    category: "Monitoring",
    brand: "Focal",
    model: "Shape 65 Matched Pair",
    title: "Focal Shape 65 · Paire studio collective",
    pitch: "Paire issue du même lot, supports lourds et câbles premium compris.",
    imageUrl: collectiveImages.monitoringBundle,
    price: 1199,
    retailPrice: 1598,
    sellerId: "atlas-audio",
    locationId: "lyon-2",
    joined: 17,
    target: 22,
    daysRemaining: 8,
    badge: "-25 %",
  },
  {
    id: "collective-exp-kali-in8-pair",
    category: "Monitoring",
    brand: "Kali Audio",
    model: "IN-8 V2 Creator Pair",
    title: "Kali IN-8 V2 · Paire créateurs",
    pitch: "Monitoring trois voies avec pads isolants et kit de mesure acoustique.",
    imageUrl: collectiveImages.homeStudioBundle,
    price: 699,
    retailPrice: 898,
    sellerId: "studio-supply",
    locationId: "rennes-centre",
    joined: 69,
    target: 84,
    daysRemaining: 2,
    badge: "Kit de mesure",
  },

  // Enregistreurs : documentaire, cinéma et flottes pédagogiques.
  {
    id: "collective-exp-zoom-f6-location",
    category: "Enregistreurs",
    brand: "Zoom",
    model: "F6 Location Sound Pack",
    title: "Zoom F6 · Pack son de tournage",
    pitch: "Enregistreur 32 bits, perche carbone, bonnettes et alimentation nomade.",
    imageUrl: collectiveImages.fieldRecordingBundle,
    price: 599,
    retailPrice: 749,
    sellerId: "room-collective",
    locationId: "bordeaux-chartrons",
    joined: 46,
    target: 60,
    daysRemaining: 5,
    badge: "Perche incluse",
  },
  {
    id: "collective-exp-tascam-portacapture-x8",
    category: "Enregistreurs",
    brand: "Tascam",
    model: "Portacapture X8 Documentary",
    title: "Tascam Portacapture X8 · Kit documentaire",
    pitch: "Recorder tactile, suspension, bonnette et carte mémoire haute capacité.",
    imageUrl: existingMarketImage("zoom-h6-used.jpg"),
    price: 399,
    retailPrice: 499,
    sellerId: "room-collective",
    locationId: "toulouse-saint-cyprien",
    joined: 57,
    target: 72,
    daysRemaining: 4,
    badge: "Carte 256 Go",
  },
  {
    id: "collective-exp-mixpre6-cinema",
    category: "Enregistreurs",
    brand: "Sound Devices",
    model: "MixPre-6 II Cinema Pack",
    title: "MixPre-6 II · Pack cinéma collectif",
    pitch: "Enregistreur professionnel, sacoche, batterie et câblage timecode.",
    imageUrl: collectiveImages.fieldRecordingBundle,
    price: 1199,
    retailPrice: 1499,
    sellerId: "broadcast-lab",
    locationId: "paris-11",
    joined: 11,
    target: 16,
    daysRemaining: 9,
    badge: "Timecode inclus",
  },
  {
    id: "collective-exp-zoom-h1-classroom-ten",
    category: "Enregistreurs",
    brand: "Zoom",
    model: "H1essential Classroom Ten",
    title: "Zoom H1essential · Flotte pédagogique x10",
    pitch: "Dix enregistreurs, étuis numérotés et chargeurs pour ateliers sonores.",
    imageUrl: existingMarketImage("zoom-h6-used.jpg"),
    price: 899,
    retailPrice: 1190,
    sellerId: "session-club",
    locationId: "nantes-centre",
    joined: 28,
    target: 34,
    daysRemaining: 3,
    badge: "-24 %",
  },
  {
    id: "collective-exp-dji-mic2-filmmaker",
    category: "Enregistreurs",
    brand: "DJI",
    model: "Mic 2 Filmmaker Pack",
    title: "DJI Mic 2 · Pack vidéastes collectif",
    pitch: "Deux émetteurs, boîtier de charge, lavaliers et adaptateurs caméra.",
    imageUrl: collectiveImages.fieldRecordingBundle,
    price: 299,
    retailPrice: 399,
    sellerId: "broadcast-lab",
    locationId: "nice-port",
    joined: 77,
    target: 96,
    daysRemaining: 2,
    badge: "Plus que 19 places",
  },
] satisfies readonly CollectiveProductSeed[];

function createCollectiveProduct(seed: CollectiveProductSeed): MarketProduct {
  const progressPercent = Math.round((seed.joined / seed.target) * 100);
  const savingsPercent = Math.round(((seed.retailPrice - seed.price) / seed.retailPrice) * 100);

  return {
    id: seed.id,
    slug: seed.id,
    pillarId: "collective",
    category: seed.category,
    brand: seed.brand,
    model: seed.model,
    title: seed.title,
    description: `${seed.title}. ${seed.pitch}`,
    imageUrl: seed.imageUrl,
    imageAlt: `${seed.title}, achat groupé sur le Market Meewav`,
    condition: "new",
    conditionLabel: "Neuf · Commande groupée",
    price: {
      amount: seed.price,
      compareAtAmount: seed.retailPrice,
      currency: "EUR",
      unit: "item",
    },
    sellerId: seed.sellerId,
    locationId: seed.locationId,
    rating: {
      score: 4.7 + (seed.joined % 3) * 0.1,
      count: 42 + seed.joined,
    },
    favorite: false,
    cart: {
      eligible: false,
      quantity: 0,
      maxQuantity: 0,
    },
    rental: null,
    service: null,
    collective: {
      joined: seed.joined,
      target: seed.target,
      progressPercent,
      daysRemaining: seed.daysRemaining,
      retailUnitPrice: seed.retailPrice,
      unlockedUnitPrice: seed.price,
      savingsPercent,
    },
    featured: false,
    badge: seed.badge,
  };
}

/**
 * Forty-eight additional group-buy offers for the long vertical Market wall.
 * The home rail stays curated separately in `MARKET_HOME_RAILS`.
 */
export const MARKET_EXPANSION_COLLECTIVE_PRODUCTS: MarketProduct[] = collectiveSeeds.map(
  createCollectiveProduct,
);
