import type { MarketCategory, MarketProduct } from "./marketDemoData";

type CollectiveWave2Seed = {
  id: `wave2-collective-${string}`;
  category: MarketCategory;
  brand: string;
  model: string;
  title: string;
  pitch: string;
  imageUrl: string;
  price: number;
  retailPrice: number;
  sellerId: string;
  locationId: string;
  joined: number;
  target: number;
  daysRemaining: number;
};

const imageRoot = "/images/market/expansion/wave2-collective";

const wave2CollectiveImages = {
  studioCreator: `${imageRoot}/studio-creator-bundle.webp`,
  djClub: `${imageRoot}/dj-club-bundle.webp`,
  liveWireless: `${imageRoot}/live-wireless-bundle.webp`,
  podcastStudio: `${imageRoot}/podcast-studio-bundle.webp`,
  acousticStrings: `${imageRoot}/acoustic-strings-bundle.webp`,
  immersiveMonitoring: `${imageRoot}/immersive-monitoring-bundle.webp`,
  fieldRecording: `${imageRoot}/field-recording-bundle.webp`,
  electronicLive: `${imageRoot}/electronic-live-bundle.webp`,
  mobileVocalBooth: `${imageRoot}/mobile-vocal-booth-bundle.webp`,
  worldPercussion: `${imageRoot}/world-percussion-bundle.webp`,
} as const;

const wave2CollectiveSeeds = [
  {
    id: "wave2-collective-studio-core-five",
    category: "Interfaces audio",
    brand: "Meewav Selection",
    model: "Studio Core Five",
    title: "Studio Core Five · Pack production complet",
    pitch: "Interface, paire de monitors, micro et casque réunis au tarif collectif.",
    imageUrl: wave2CollectiveImages.studioCreator,
    price: 899,
    retailPrice: 1169,
    sellerId: "studio-supply",
    locationId: "paris-11",
    joined: 47,
    target: 60,
    daysRemaining: 5,
  },
  {
    id: "wave2-collective-studio-creator-eight",
    category: "Monitoring",
    brand: "Creator Studio",
    model: "Creator Eight Bundle",
    title: "Creator Eight · Studio partagé prêt à mixer",
    pitch: "Configuration calibrée pour huit créateurs avec câblage et supports inclus.",
    imageUrl: wave2CollectiveImages.studioCreator,
    price: 1049,
    retailPrice: 1399,
    sellerId: "waveform-studio",
    locationId: "lyon-2",
    joined: 31,
    target: 44,
    daysRemaining: 8,
  },
  {
    id: "wave2-collective-studio-vocal-pro",
    category: "Microphones",
    brand: "Session Lab",
    model: "Vocal Production Pack",
    title: "Vocal Production · Chaîne studio collective",
    pitch: "Micro à condensateur, interface, écoute de proximité et casque fermé.",
    imageUrl: wave2CollectiveImages.studioCreator,
    price: 749,
    retailPrice: 949,
    sellerId: "broadcast-lab",
    locationId: "bordeaux-chartrons",
    joined: 72,
    target: 90,
    daysRemaining: 3,
  },
  {
    id: "wave2-collective-dj-club-four",
    category: "DJ & vinyle",
    brand: "Club Circuit",
    model: "Club Four Performance",
    title: "Club Four · Régie DJ complète",
    pitch: "Deux lecteurs, mixer quatre voies, casques et monitoring de cabine.",
    imageUrl: wave2CollectiveImages.djClub,
    price: 4290,
    retailPrice: 5290,
    sellerId: "vinyl-circuit",
    locationId: "marseille-cours-julien",
    joined: 18,
    target: 24,
    daysRemaining: 9,
  },
  {
    id: "wave2-collective-dj-tour-ready",
    category: "DJ & vinyle",
    brand: "Night Session",
    model: "Tour Ready Duo",
    title: "Tour Ready Duo · Pack régie mobile",
    pitch: "Régie complète avec flight cases renforcés et câbles de secours.",
    imageUrl: wave2CollectiveImages.djClub,
    price: 3890,
    retailPrice: 4740,
    sellerId: "session-club",
    locationId: "lille-wazemmes",
    joined: 26,
    target: 36,
    daysRemaining: 7,
  },
  {
    id: "wave2-collective-dj-school-fleet",
    category: "DJ & vinyle",
    brand: "Mix Academy",
    model: "DJ School Fleet",
    title: "DJ School Fleet · Quatre postes pédagogiques",
    pitch: "Commande mutualisée pour écoles et collectifs avec mise en service incluse.",
    imageUrl: wave2CollectiveImages.djClub,
    price: 7290,
    retailPrice: 8990,
    sellerId: "rhythm-workshop",
    locationId: "nantes-centre",
    joined: 12,
    target: 18,
    daysRemaining: 11,
  },
  {
    id: "wave2-collective-live-wireless-eight",
    category: "Microphones",
    brand: "Stage Link",
    model: "Wireless Eight",
    title: "Wireless Eight · Pack scène sans fil",
    pitch: "Quatre micros main, retours in-ear, récepteurs et rack de transport.",
    imageUrl: wave2CollectiveImages.liveWireless,
    price: 2790,
    retailPrice: 3490,
    sellerId: "room-collective",
    locationId: "toulouse-saint-cyprien",
    joined: 34,
    target: 46,
    daysRemaining: 6,
  },
  {
    id: "wave2-collective-live-stagebox-sixteen",
    category: "Interfaces audio",
    brand: "Stage Link",
    model: "Stagebox Sixteen",
    title: "Stagebox Sixteen · Liaison scène collective",
    pitch: "Stagebox numérique, multipaires et réseau audio sécurisé pour les Rooms.",
    imageUrl: wave2CollectiveImages.liveWireless,
    price: 1890,
    retailPrice: 2390,
    sellerId: "atlas-audio",
    locationId: "montpellier-beaux-arts",
    joined: 43,
    target: 54,
    daysRemaining: 4,
  },
  {
    id: "wave2-collective-live-iem-crew",
    category: "Monitoring",
    brand: "Stage Link",
    model: "IEM Crew Pack",
    title: "IEM Crew · Retours personnels pour quatre artistes",
    pitch: "Quatre packs in-ear, antennes et rack prêts pour une tournée collective.",
    imageUrl: wave2CollectiveImages.liveWireless,
    price: 2190,
    retailPrice: 2760,
    sellerId: "room-collective",
    locationId: "rennes-centre",
    joined: 63,
    target: 78,
    daysRemaining: 3,
  },
  {
    id: "wave2-collective-podcast-roundtable-four",
    category: "Microphones",
    brand: "Broadcast Circle",
    model: "Roundtable Four",
    title: "Roundtable Four · Studio podcast complet",
    pitch: "Quatre micros broadcast, bras, casques et console multitrack.",
    imageUrl: wave2CollectiveImages.podcastStudio,
    price: 1290,
    retailPrice: 1640,
    sellerId: "broadcast-lab",
    locationId: "strasbourg-krutenau",
    joined: 81,
    target: 100,
    daysRemaining: 2,
  },
  {
    id: "wave2-collective-podcast-media-school",
    category: "Interfaces audio",
    brand: "Broadcast Circle",
    model: "Media School Lab",
    title: "Media School Lab · Flotte podcast pédagogique",
    pitch: "Deux tables de quatre intervenants avec câblage et formation de lancement.",
    imageUrl: wave2CollectiveImages.podcastStudio,
    price: 2490,
    retailPrice: 3190,
    sellerId: "session-club",
    locationId: "dijon-centre",
    joined: 22,
    target: 30,
    daysRemaining: 10,
  },
  {
    id: "wave2-collective-podcast-live-video",
    category: "Enregistreurs",
    brand: "Broadcast Circle",
    model: "Live Video Audio Pack",
    title: "Podcast Live · Son multitrack pour vidéo",
    pitch: "Console, quatre micros et monitoring pour émissions filmées en direct.",
    imageUrl: wave2CollectiveImages.podcastStudio,
    price: 1549,
    retailPrice: 1990,
    sellerId: "noemie-sound",
    locationId: "nice-port",
    joined: 39,
    target: 52,
    daysRemaining: 6,
  },
  {
    id: "wave2-collective-strings-chamber-room",
    category: "Guitares",
    brand: "Wood & Bow",
    model: "Chamber Room Ensemble",
    title: "Chamber Room · Ensemble cordes acoustiques",
    pitch: "Violons, alto, violoncelle, guitare et microphones de prise naturelle.",
    imageUrl: wave2CollectiveImages.acousticStrings,
    price: 3290,
    retailPrice: 4190,
    sellerId: "guitar-house",
    locationId: "angers-doutre",
    joined: 17,
    target: 26,
    daysRemaining: 12,
  },
  {
    id: "wave2-collective-strings-acoustic-session",
    category: "Guitares",
    brand: "Wood & Bow",
    model: "Acoustic Session Pack",
    title: "Acoustic Session · Cordes et captation stéréo",
    pitch: "Pack instruments sélectionnés avec paire de micros et accessoires de studio.",
    imageUrl: wave2CollectiveImages.acousticStrings,
    price: 2190,
    retailPrice: 2790,
    sellerId: "elise-tones",
    locationId: "clermont-jaude",
    joined: 29,
    target: 40,
    daysRemaining: 8,
  },
  {
    id: "wave2-collective-strings-education-five",
    category: "Guitares",
    brand: "Wood & Bow",
    model: "Education Five",
    title: "Education Five · Parc instrumental partagé",
    pitch: "Cinq instruments, étuis et captation mobile pour ateliers collectifs.",
    imageUrl: wave2CollectiveImages.acousticStrings,
    price: 2690,
    retailPrice: 3450,
    sellerId: "rhythm-workshop",
    locationId: "rouen-rive-droite",
    joined: 56,
    target: 72,
    daysRemaining: 5,
  },
  {
    id: "wave2-collective-monitoring-immersive-five-one",
    category: "Monitoring",
    brand: "Spatial Reference",
    model: "Immersive 5.1",
    title: "Immersive 5.1 · Système studio calibré",
    pitch: "Cinq monitors, subwoofer, contrôleur et microphone de calibration.",
    imageUrl: wave2CollectiveImages.immersiveMonitoring,
    price: 3490,
    retailPrice: 4490,
    sellerId: "waveform-studio",
    locationId: "paris-11",
    joined: 24,
    target: 32,
    daysRemaining: 7,
  },
  {
    id: "wave2-collective-monitoring-postproduction",
    category: "Monitoring",
    brand: "Spatial Reference",
    model: "Postproduction Suite",
    title: "Postproduction Suite · Écoute multicanale",
    pitch: "Pack destiné aux studios image avec calibration et contrôleur central.",
    imageUrl: wave2CollectiveImages.immersiveMonitoring,
    price: 3890,
    retailPrice: 4980,
    sellerId: "camille-mix",
    locationId: "lyon-2",
    joined: 14,
    target: 20,
    daysRemaining: 13,
  },
  {
    id: "wave2-collective-monitoring-room-network",
    category: "Rooms & studios",
    brand: "Spatial Reference",
    model: "Room Network Pack",
    title: "Room Network · Monitoring pour studios partagés",
    pitch: "Système complet pour équiper une Room et partager des presets de calibration.",
    imageUrl: wave2CollectiveImages.immersiveMonitoring,
    price: 3190,
    retailPrice: 4050,
    sellerId: "room-collective",
    locationId: "grenoble-bouchayer",
    joined: 41,
    target: 56,
    daysRemaining: 6,
  },
  {
    id: "wave2-collective-field-cinema-eight",
    category: "Enregistreurs",
    brand: "Field Unit",
    model: "Cinema Eight",
    title: "Cinema Eight · Kit son de tournage",
    pitch: "Recorder huit pistes, perche carbone, HF, timecode et valise étanche.",
    imageUrl: wave2CollectiveImages.fieldRecording,
    price: 2890,
    retailPrice: 3690,
    sellerId: "broadcast-lab",
    locationId: "bordeaux-chartrons",
    joined: 36,
    target: 48,
    daysRemaining: 7,
  },
  {
    id: "wave2-collective-field-documentary",
    category: "Enregistreurs",
    brand: "Field Unit",
    model: "Documentary Pro",
    title: "Documentary Pro · Pack terrain complet",
    pitch: "Enregistrement 32 bits, micros stéréo, harnais et protection météo.",
    imageUrl: wave2CollectiveImages.fieldRecording,
    price: 1649,
    retailPrice: 2090,
    sellerId: "noemie-sound",
    locationId: "montpellier-beaux-arts",
    joined: 68,
    target: 84,
    daysRemaining: 3,
  },
  {
    id: "wave2-collective-field-school-fleet",
    category: "Enregistreurs",
    brand: "Field Unit",
    model: "Sound School Fleet",
    title: "Sound School Fleet · Six kits de reportage",
    pitch: "Flotte pédagogique numérotée avec valises, casques et sessions de prise en main.",
    imageUrl: wave2CollectiveImages.fieldRecording,
    price: 5190,
    retailPrice: 6750,
    sellerId: "session-club",
    locationId: "nantes-centre",
    joined: 11,
    target: 16,
    daysRemaining: 14,
  },
  {
    id: "wave2-collective-electronic-live-rig",
    category: "Synthétiseurs",
    brand: "Circuit Union",
    model: "Electronic Live Rig",
    title: "Electronic Live Rig · Performance sans ordinateur",
    pitch: "Synthé analogique, sampler, séquenceur, boîte à rythmes et mixer.",
    imageUrl: wave2CollectiveImages.electronicLive,
    price: 2690,
    retailPrice: 3390,
    sellerId: "synth-district",
    locationId: "strasbourg-krutenau",
    joined: 49,
    target: 64,
    daysRemaining: 5,
  },
  {
    id: "wave2-collective-electronic-beat-lab",
    category: "Contrôleurs MIDI",
    brand: "Circuit Union",
    model: "Beat Lab Hardware",
    title: "Beat Lab Hardware · Table de création collective",
    pitch: "Stations complémentaires pour produire, sampler et arranger à plusieurs.",
    imageUrl: wave2CollectiveImages.electronicLive,
    price: 2290,
    retailPrice: 2890,
    sellerId: "modular-corner",
    locationId: "rennes-centre",
    joined: 77,
    target: 96,
    daysRemaining: 2,
  },
  {
    id: "wave2-collective-electronic-tour-cases",
    category: "Synthétiseurs",
    brand: "Circuit Union",
    model: "Tour Cases Edition",
    title: "Electronic Tour · Rig complet en flight cases",
    pitch: "Configuration live avec câblage prémonté et caisses de transport dédiées.",
    imageUrl: wave2CollectiveImages.electronicLive,
    price: 3090,
    retailPrice: 3950,
    sellerId: "atlas-audio",
    locationId: "nice-port",
    joined: 28,
    target: 38,
    daysRemaining: 9,
  },
  {
    id: "wave2-collective-vocal-booth-mobile",
    category: "Microphones",
    brand: "Vocal Haven",
    model: "Mobile Booth Pro",
    title: "Mobile Booth Pro · Cabine vocale transportable",
    pitch: "Panneaux pliants, micro, préampli, casque et sacs de transport.",
    imageUrl: wave2CollectiveImages.mobileVocalBooth,
    price: 1390,
    retailPrice: 1790,
    sellerId: "studio-supply",
    locationId: "lille-wazemmes",
    joined: 59,
    target: 75,
    daysRemaining: 4,
  },
  {
    id: "wave2-collective-vocal-room-starter",
    category: "Rooms & studios",
    brand: "Vocal Haven",
    model: "Room Starter",
    title: "Vocal Room Starter · Espace d’enregistrement clé en main",
    pitch: "Traitement mobile et chaîne audio complète pour lancer une petite Room.",
    imageUrl: wave2CollectiveImages.mobileVocalBooth,
    price: 1690,
    retailPrice: 2150,
    sellerId: "room-collective",
    locationId: "marseille-cours-julien",
    joined: 33,
    target: 46,
    daysRemaining: 7,
  },
  {
    id: "wave2-collective-vocal-school-three",
    category: "Microphones",
    brand: "Vocal Haven",
    model: "Vocal School Three",
    title: "Vocal School Three · Trois postes d’enregistrement",
    pitch: "Trois cabines mobiles équipées pour écoles, coachs et ateliers collectifs.",
    imageUrl: wave2CollectiveImages.mobileVocalBooth,
    price: 3690,
    retailPrice: 4740,
    sellerId: "rhythm-workshop",
    locationId: "toulouse-saint-cyprien",
    joined: 16,
    target: 24,
    daysRemaining: 12,
  },
  {
    id: "wave2-collective-percussion-world-stage",
    category: "Batteries électroniques",
    brand: "Rhythm Atlas",
    model: "World Stage Ensemble",
    title: "World Stage · Ensemble de percussions complet",
    pitch: "Congas, djembe, cajón, bongos, cymbales, accessoires et microphones.",
    imageUrl: wave2CollectiveImages.worldPercussion,
    price: 1890,
    retailPrice: 2440,
    sellerId: "rhythm-workshop",
    locationId: "montpellier-beaux-arts",
    joined: 46,
    target: 60,
    daysRemaining: 6,
  },
  {
    id: "wave2-collective-percussion-school-twelve",
    category: "Batteries électroniques",
    brand: "Rhythm Atlas",
    model: "Percussion School Twelve",
    title: "Percussion School Twelve · Atelier collectif",
    pitch: "Douze postes variés, housses, baguettes et microphones pour ensembles.",
    imageUrl: wave2CollectiveImages.worldPercussion,
    price: 2290,
    retailPrice: 2950,
    sellerId: "session-club",
    locationId: "rouen-rive-droite",
    joined: 69,
    target: 88,
    daysRemaining: 3,
  },
  {
    id: "wave2-collective-percussion-studio-library",
    category: "Microphones",
    brand: "Rhythm Atlas",
    model: "Studio Percussion Library",
    title: "Studio Percussion Library · Collection enregistrable",
    pitch: "Sélection organique complète avec paire de micros et rangements dédiés.",
    imageUrl: wave2CollectiveImages.worldPercussion,
    price: 1590,
    retailPrice: 2090,
    sellerId: "camille-mix",
    locationId: "angers-doutre",
    joined: 23,
    target: 34,
    daysRemaining: 10,
  },
] satisfies readonly CollectiveWave2Seed[];

function createWave2CollectiveProduct(seed: CollectiveWave2Seed): MarketProduct {
  const progressPercent = Math.round((seed.joined / seed.target) * 100);
  const savingsPercent = Math.round(((seed.retailPrice - seed.price) / seed.retailPrice) * 100);

  return {
    id: seed.id,
    slug: seed.id,
    pillarId: "collective",
    category: seed.category,
    brand: seed.brand,
    model: seed.model,
    title: seed.title,
    description: `${seed.title}. ${seed.pitch}`,
    imageUrl: seed.imageUrl,
    imageAlt: `${seed.title}, achat groupé sur le Market Meewav`,
    condition: "new",
    conditionLabel: "Neuf · Commande groupée",
    price: {
      amount: seed.price,
      compareAtAmount: seed.retailPrice,
      currency: "EUR",
      unit: "item",
    },
    sellerId: seed.sellerId,
    locationId: seed.locationId,
    rating: {
      score: 4.7 + (seed.joined % 3) * 0.1,
      count: 48 + seed.joined,
    },
    favorite: false,
    cart: {
      eligible: false,
      quantity: 0,
      maxQuantity: 0,
    },
    rental: null,
    service: null,
    collective: {
      joined: seed.joined,
      target: seed.target,
      progressPercent,
      daysRemaining: seed.daysRemaining,
      retailUnitPrice: seed.retailPrice,
      unlockedUnitPrice: seed.price,
      savingsPercent,
    },
    featured: false,
    badge: `${progressPercent} % atteint`,
  };
}

/**
 * Thirty additional collective offers for the second expansion wave.
 * Integration remains explicit in `marketDemoData.ts` so the home rails stay curated.
 */
export const MARKET_EXPANSION_WAVE2_COLLECTIVE_PRODUCTS: MarketProduct[] =
  wave2CollectiveSeeds.map(createWave2CollectiveProduct);

export const MARKET_EXPANSION_WAVE2_COLLECTIVE_COUNT =
  MARKET_EXPANSION_WAVE2_COLLECTIVE_PRODUCTS.length;
