import type { PlaceProfile, PlaceRoomState } from "./place.types";

/** Investor/demo-only distribution for a freshly launched public choice. */
export const PLACE_DEMO_POLL_VOTE_COUNTS = [539, 219, 84] as const;

const profile = (
  id: string,
  displayName: string,
  handle: string,
  role: string,
  city: string,
  avatarUrl: string,
  gradeLevel: number,
): PlaceProfile => ({ id, displayName, handle, role, city, avatarUrl, gradeLevel });

export const PLACE_DEMO_PROFILES = {
  host: profile(
    "51000000-0000-4000-8000-000000000001",
    "Naya Oris",
    "@naya.oris",
    "Rappeuse · Autrice",
    "Grenoble",
    "/images/tremplin/artists/generated/naya-oris-boom-bap-rapper-grenoble-v1.webp",
    4,
  ),
  guestA: profile(
    "51000000-0000-4000-8000-000000000002",
    "Lior Benali",
    "@lior.benali",
    "Guitariste",
    "Lyon",
    "/images/tremplin/artists/generated/lior-benali-guitar-v1.webp",
    2,
  ),
  guestB: profile(
    "51000000-0000-4000-8000-000000000003",
    "Malik Soren",
    "@malik.soren",
    "Chanteur Soul",
    "Strasbourg",
    "/images/tremplin/artists/generated/malik-soren-chanteur-soul-strasbourg-v1.webp",
    3,
  ),
  guestC: profile(
    "51000000-0000-4000-8000-000000000004",
    "Solis Miro",
    "@solis.miro",
    "Chanteuse · Interprète",
    "Paris",
    "/images/tremplin/artists/generated/ai-experimental-voice-solis-miro.webp",
    5,
  ),
  viewerA: profile(
    "51000000-0000-4000-8000-000000000005",
    "Kenza Loba",
    "@kenza.loba",
    "DJ · Productrice",
    "Aubervilliers",
    "/images/tremplin/artists/generated/kenza-loba-dj-amapiano-aubervilliers-v1.webp",
    3,
  ),
  viewerB: profile(
    "51000000-0000-4000-8000-000000000006",
    "June Kairo",
    "@june.kairo",
    "DJ Drum & Bass",
    "Amiens",
    "/images/tremplin/artists/generated/june-kairo-dj-drum-bass-amiens-v1.webp",
    2,
  ),
  backstageB: profile(
    "51000000-0000-4000-8000-000000000025",
    "Louna Saphir",
    "@louna.saphir",
    "Violoncelliste",
    "Metz",
    "/images/tremplin/artists/generated/louna-saphir-violoncelliste-neo-classique-metz-v1.webp",
    3,
  ),
  backstageC: profile(
    "51000000-0000-4000-8000-000000000026",
    "Aïcha Sol",
    "@aicha.sol",
    "Coach vocale · Gospel",
    "Nîmes",
    "/images/tremplin/artists/generated/aicha-sol-coach-vocal-gospel-nimes-v1.webp",
    4,
  ),
};

export const PLACE_DEMO_CHAT_SCRIPT: ReadonlyArray<{
  author: PlaceProfile;
  content: string;
  delayMs: number;
}> = [
  { author: PLACE_DEMO_PROFILES.viewerA, content: "[[mw:coeur-casque]]", delayMs: 4_200 },
  { author: PLACE_DEMO_PROFILES.guestB, content: "Le niveau de la musique est bon pour moi.", delayMs: 5_600 },
  { author: PLACE_DEMO_PROFILES.viewerB, content: "Cette basse [[mw:enceinte-studio]] elle respire enfin", delayMs: 4_800 },
  { author: PLACE_DEMO_PROFILES.guestA, content: "Je garde le motif plus simple sur la prochaine prise.", delayMs: 6_300 },
  { author: PLACE_DEMO_PROFILES.backstageC, content: "La dernière note peut rester un peu plus droite avant le vibrato.", delayMs: 7_100 },
  { author: PLACE_DEMO_PROFILES.guestC, content: "Je double seulement la fin de phrase, pas tout le refrain.", delayMs: 5_400 },
  { author: PLACE_DEMO_PROFILES.viewerA, content: "[[mw:v2-boite-a-rythmes-808]] [[mw:note-en-flamme]]", delayMs: 6_800 },
  { author: PLACE_DEMO_PROFILES.guestB, content: "La transition est beaucoup plus naturelle maintenant [[mw:onde-neon]]", delayMs: 4_600 },
  { author: PLACE_DEMO_PROFILES.backstageB, content: "Le violoncelle peut prendre la réponse après la voix.", delayMs: 6_200 },
  { author: PLACE_DEMO_PROFILES.guestA, content: "Je vous propose une harmonique juste avant le pont.", delayMs: 5_900 },
  { author: PLACE_DEMO_PROFILES.viewerB, content: "Le silence avant le retour du beat [[mw:note-en-flamme]] gardez ça !", delayMs: 7_400 },
  { author: PLACE_DEMO_PROFILES.guestC, content: "Prête pour la doublure.", delayMs: 3_800 },
  { author: PLACE_DEMO_PROFILES.backstageC, content: "Pense à ouvrir la voyelle sur le dernier mot.", delayMs: 5_700 },
  { author: PLACE_DEMO_PROFILES.viewerA, content: "La boucle repart dans quatre temps.", delayMs: 4_100 },
  { author: PLACE_DEMO_PROFILES.guestB, content: "[[mw:micro-flamme]] [[mw:v3-rocket-mic]]", delayMs: 6_500 },
  { author: PLACE_DEMO_PROFILES.guestA, content: "Je coupe la guitare une mesure avant le pont.", delayMs: 5_200 },
  { author: PLACE_DEMO_PROFILES.backstageB, content: "Je peux préparer une ligne plus grave pour la sortie.", delayMs: 7_000 },
  { author: PLACE_DEMO_PROFILES.viewerB, content: "Au casque [[mw:casque-studio]] le contraste avec le couplet est nickel", delayMs: 4_700 },
  { author: PLACE_DEMO_PROFILES.guestC, content: "Je garde la tierce sur la première réponse seulement.", delayMs: 6_100 },
  { author: PLACE_DEMO_PROFILES.backstageC, content: "Oui, sinon l'harmonie devient trop dense.", delayMs: 4_900 },
  { author: PLACE_DEMO_PROFILES.viewerA, content: "Je vous envoie aussi une version sans percussion après la Room.", delayMs: 7_600 },
  { author: PLACE_DEMO_PROFILES.guestB, content: "On peut refaire le dernier passage une fois ?", delayMs: 5_300 },
  { author: PLACE_DEMO_PROFILES.guestA, content: "[[mw:signe-rock]] compris, juste les réponses", delayMs: 5_800 },
  { author: PLACE_DEMO_PROFILES.viewerB, content: "[[mw:coeur-musical]] [[mw:v2-etoile-talent]]", delayMs: 7_200 },
  { author: PLACE_DEMO_PROFILES.backstageB, content: "La dernière tenue peut mener directement vers l'outro.", delayMs: 6_400 },
  { author: PLACE_DEMO_PROFILES.guestC, content: "Je suis prête pour une dernière prise complète.", delayMs: 4_400 },
  { author: PLACE_DEMO_PROFILES.viewerA, content: "Niveaux prêts de mon côté.", delayMs: 3_900 },
];

const PLACE_DEMO_QUEUE_PROFILES: PlaceProfile[] = [
  PLACE_DEMO_PROFILES.viewerA,
  PLACE_DEMO_PROFILES.viewerB,
  profile("51000000-0000-4000-8000-000000000007", "Aina Sol", "@aina.sol", "DJ · Productrice", "Bordeaux", "/images/tremplin/artists/generated/aina-sol-dj-productrice-afro-house-bordeaux-v1.webp", 4),
  profile("51000000-0000-4000-8000-000000000008", "Sacha Bloom", "@sacha.bloom", "Clarinettiste", "Strasbourg", "/images/tremplin/artists/generated/sacha-bloom-clarinettiste-jazz-klezmer-strasbourg-v1.webp", 3),
  profile("51000000-0000-4000-8000-000000000009", "Mariam Delta", "@mariam.delta", "Productrice Gqom", "Roubaix", "/images/tremplin/artists/generated/mariam-delta-productrice-gqom-roubaix-v1.webp", 2),
  profile("51000000-0000-4000-8000-000000000010", "Imani Kader", "@imani.kader", "Saxophoniste", "Montpellier", "/images/tremplin/artists/generated/imani-kader-saxophonist-montpellier-v1.webp", 4),
  profile("51000000-0000-4000-8000-000000000011", "Miko Rêve", "@miko.reve", "Productrice Hyperpop", "Paris", "/images/tremplin/artists/generated/miko-reve-productrice-hyperpop-paris-v1.webp", 5),
  profile("51000000-0000-4000-8000-000000000012", "Sekou Maré", "@sekou.mare", "Danseur · Chorégraphe", "Marseille", "/images/tremplin/artists/generated/sekou-mare-danseur-choregraphe-marseille-v1.webp", 3),
  profile("51000000-0000-4000-8000-000000000013", "Rania Vox", "@rania.vox", "Chanteuse lyrique", "Avignon", "/images/tremplin/artists/generated/rania-vox-lyric-electro-singer-avignon-v1.webp", 4),
  profile("51000000-0000-4000-8000-000000000014", "Milo Kanza", "@milo.kanza", "Contrebassiste", "Dijon", "/images/tremplin/artists/generated/milo-kanza-double-bassist-dijon-v1.webp", 2),
  profile("51000000-0000-4000-8000-000000000015", "Maia Kuroda", "@maia.kuroda", "Violoniste", "Nantes", "/images/tremplin/artists/generated/maia-kuroda-violoniste-neo-classique-nantes-v1.webp", 5),
  profile("51000000-0000-4000-8000-000000000016", "Ilyes Pulse", "@ilyes.pulse", "Beatboxer", "Cergy", "/images/tremplin/artists/generated/ilyes-pulse-beatboxer-cergy-v1.webp", 2),
  profile("51000000-0000-4000-8000-000000000017", "Tess Aoki", "@tess.aoki", "VJ · Réalisatrice", "Rennes", "/images/tremplin/artists/generated/tess-aoki-music-video-director-vj-rennes-v1.webp", 4),
  profile("51000000-0000-4000-8000-000000000018", "Nola Mbaye", "@nola.mbaye", "Choriste Gospel", "Tours", "/images/tremplin/artists/generated/nola-mbaye-choriste-gospel-tours-v1.webp", 3),
  profile("51000000-0000-4000-8000-000000000019", "Jo Varenne", "@jo.varenne", "Guitariste Blues", "Toulouse", "/images/tremplin/artists/generated/jo-varenne-blues-rock-guitar-toulouse-v1.webp", 2),
  profile("51000000-0000-4000-8000-000000000020", "Elise Kemba", "@elise.kemba", "Productrice Dub", "Le Havre", "/images/tremplin/artists/generated/elise-kemba-dub-producer-le-havre-v1.webp", 3),
  profile("51000000-0000-4000-8000-000000000021", "Ophélie Grant", "@ophelie.grant", "Soprano", "Lyon", "/images/tremplin/artists/generated/ophelie-grant-soprano-cinematic-lyon-v1.webp", 4),
  profile("51000000-0000-4000-8000-000000000022", "Tiago Luz", "@tiago.luz", "Producteur Baile Funk", "Bayonne", "/images/tremplin/artists/generated/tiago-luz-baile-funk-producer-bayonne-v1.webp", 3),
  profile("51000000-0000-4000-8000-000000000023", "Inès Raku", "@ines.raku", "Batteuse", "Marseille", "/images/tremplin/artists/generated/ines-raku-drummer-marseille-v1.webp", 2),
  profile("51000000-0000-4000-8000-000000000024", "Idriss Noor", "@idriss.noor", "Oud · Compositeur", "Paris", "/images/tremplin/artists/generated/idriss-noor-oud-compositeur-paris-v1.webp", 4),
];

const waveform = Array.from({ length: 74 }, (_, index) => {
  const carrier = 0.24 + Math.abs(Math.sin(index * 0.43)) * 0.56;
  const detail = Math.abs(Math.cos(index * 1.31)) * 0.2;
  return Math.min(0.98, carrier + detail);
});

export function createPlaceDemoState(currentUserId?: string | null, roomType = "place"): PlaceRoomState {
  const { host, guestA, guestB, guestC, viewerA, viewerB, backstageB, backstageC } = PLACE_DEMO_PROFILES;
  const matchingDemoProfile = currentUserId
    ? Object.values(PLACE_DEMO_PROFILES).find((profile) => profile.id === currentUserId)
    : undefined;
  const currentUserProfile = currentUserId
    ? matchingDemoProfile ?? { ...viewerA, id: currentUserId }
    : null;
  const now = Date.now();
  return {
    id: `52000000-0000-4000-8000-${String(["place", "scene", "cage", "classe", "wave", "loge"].indexOf(roomType) + 1).padStart(12, "0")}`,
    source: "demo",
    title: "Open Studio — À contretemps",
    description: "Naya construit son prochain titre en direct avec la communauté.",
    status: "live",
    startedAt: new Date(Date.now() - 42 * 60_000 - 18_000).toISOString(),
    host,
    participantsCount: 1842,
    peakViewers: 2317,
    likesCount: 12846,
    goldenLikesCount: 214,
    hatTotalAmount: 842,
    currentUserHasLiked: false,
    currentUserHasGoldenLiked: false,
    goldenLikeAvailableAt: null,
    currentUserProfile,
    currentUserIsActiveParticipant: Boolean(currentUserProfile),
    queueOpen: true,
    connectionLabel: "Antenne stable · 38 ms",
    broadcastStatus: "active",
    participants: [
      {
        id: "host",
        profile: host,
        joinedAt: new Date(now - 43 * 60_000).toISOString(),
        status: "host",
        videoUrl: "/media/shorts-demo/landscape-roundtable.mp4",
        imageUrl: host.avatarUrl,
        isCameraEnabled: true,
        isMicrophoneEnabled: true,
        isSpeaking: true,
        latencyMs: 32,
      },
      {
        id: "guest-a",
        profile: guestA,
        joinedAt: new Date(now - 31 * 60_000).toISOString(),
        status: "backstage",
        videoUrl: "/media/shorts-demo/landscape-dj.mp4",
        imageUrl: guestA.avatarUrl,
        isCameraEnabled: true,
        isMicrophoneEnabled: true,
        isSpeaking: false,
        latencyMs: 44,
      },
      {
        id: "guest-b",
        profile: guestB,
        joinedAt: new Date(now - 18 * 60_000).toISOString(),
        status: "backstage",
        videoUrl: "/media/shorts-demo/landscape-guitar.mp4",
        imageUrl: guestB.avatarUrl,
        isCameraEnabled: true,
        isMicrophoneEnabled: true,
        isSpeaking: false,
        latencyMs: 41,
      },
      {
        id: "guest-c",
        profile: guestC,
        joinedAt: new Date(now - 7 * 60_000).toISOString(),
        status: "backstage",
        videoUrl: "/media/shorts-demo/portrait-vocal-session.mp4",
        imageUrl: guestC.avatarUrl,
        isCameraEnabled: true,
        isMicrophoneEnabled: false,
        isSpeaking: false,
        latencyMs: 49,
      },
      {
        id: "guest-d",
        profile: backstageB,
        joinedAt: new Date(now - 4 * 60_000).toISOString(),
        status: "backstage",
        imageUrl: backstageB.avatarUrl,
        isCameraEnabled: false,
        isMicrophoneEnabled: true,
        isSpeaking: false,
        latencyMs: 112,
      },
      {
        id: "guest-e",
        profile: backstageC,
        joinedAt: new Date(now - 2 * 60_000).toISOString(),
        status: "backstage",
        imageUrl: backstageC.avatarUrl,
        isCameraEnabled: true,
        isMicrophoneEnabled: true,
        isSpeaking: false,
        latencyMs: 46,
      },
    ],
    queue: PLACE_DEMO_QUEUE_PROFILES.map((queueProfile, index) => ({
      id: `queue-${index + 1}`,
      queueEntryId: `54000000-0000-4000-8${String(index + 1).padStart(3, "0")}-000000000001`,
      profile: queueProfile,
      joinedAt: new Date(now - (index + 1) * 75_000).toISOString(),
      status: "pending" as const,
      imageUrl: queueProfile.avatarUrl,
      isCameraEnabled: index % 5 !== 3,
      isMicrophoneEnabled: index % 4 !== 1,
      isSpeaking: false,
      latencyMs: 42 + (index % 8) * 7,
    })),
    messages: [
      { id: "message-1", author: viewerA, content: "Je te renvoie la boucle avec le kick plus sec. [[mw:beatpad-en-flamme]]", createdAt: new Date(Date.now() - 8 * 60_000).toISOString() },
      { id: "message-2", author: guestB, content: "Le refrain reste en tête, garde cette prise [[mw:micro-flamme]]", createdAt: new Date(Date.now() - 6 * 60_000).toISOString() },
      { id: "message-3", author: null, content: "Aïcha Sol est prête dans les Coulisses.", createdAt: new Date(Date.now() - 4 * 60_000).toISOString(), isSystem: true },
      { id: "message-4", author: viewerB, content: "Vous pouvez tester la dernière phrase sans la reverb ?", createdAt: new Date(Date.now() - 2 * 60_000).toISOString(), isPinned: true },
      { id: "message-5", author: guestA, content: "Je coupe les médiums sur la guitare pour laisser la voix respirer.", createdAt: new Date(Date.now() - 56_000).toISOString() },
    ],
    channels: [
      { id: "host-mic", participantId: host.id, label: "Ma voix", detail: "Naya Oris", kind: "microphone", gain: 0.82, level: 0.76, isMuted: false, isSolo: false, signalState: "active", accent: "#a578ff" },
      { id: "guest-lior", participantId: guestA.id, label: "Lior", detail: "Invité", kind: "guest", gain: 0.72, level: 0.38, isMuted: false, isSolo: false, signalState: "active", accent: "#a578ff" },
      { id: "guest-malik", participantId: guestB.id, label: "Malik", detail: "Invité", kind: "guest", gain: 0.74, level: 0.86, isMuted: false, isSolo: false, signalState: "active", accent: "#a578ff" },
      { id: "guest-solis", participantId: guestC.id, label: "Solis", detail: "Invitée", kind: "guest", gain: 0.69, level: 0.54, isMuted: false, isSelfMuted: false, isSolo: false, signalState: "active", accent: "#a578ff" },
      { id: "host-audio", participantId: host.id, label: "Musique", detail: "Instrumental", kind: "audio", gain: 0.68, level: 0.57, isMuted: false, isSolo: false, signalState: "active", accent: "#36d6c4" },
      { id: "master", label: "Master", detail: "Sortie publique", kind: "master", gain: 0.86, level: 0.71, isMuted: false, isSolo: false, signalState: "active", accent: "#f4f0ff" },
    ],
    personalVocal: {
      enabled: true,
      monitoring: false,
      preset: "Trap",
      // The correction engines are opt-in. Keep these parameters dormant until
      // the user selects the feature-flagged openDAW path or the MeeWav test path.
      tuneEnabled: false,
      tuneKey: "F#",
      tuneScale: "Mineure",
      tuneAmount: 0.98,
      tuneSpeed: 0.86,
      tuneHumanize: 0.22,
      tuneSmooth: 0.22,
      tuneShift: 0,
      tunePreset: "effect",
      reverbEnabled: true,
      reverbAmount: 0.18,
      reverbType: "Plate",
      reverbDuration: 1.8,
      reverbPreDelayMs: 24,
      eqEnabled: true,
      compEnabled: true,
      compAmount: 0.62,
      compThresholdDb: -12,
      compRatio: 3.2,
      compAttackMs: 18,
      compReleaseMs: 140,
      compMakeupDb: 2.5,
      delayEnabled: false,
      delayAmount: 0.16,
      delayTimeMs: 120,
      delayFeedback: 0.24,
    },
    track: {
      id: "track-contretemps",
      title: "À contretemps — Instrumental v7",
      artist: "Naya Oris · Kenza Loba",
      durationSeconds: 218,
      currentSeconds: 76,
      bpm: 92,
      musicalKey: "F♯ min",
      isPlaying: true,
      isLooping: true,
      waveform,
    },
    poll: null,
    giftDraw: null,
    pinnedMessageId: null,
    highlightText: null,
  };
}
