import { getRoomPreProfileBounds } from "../tools/panels/roomPreProfileBounds";
import { useEffect, useRef, useState, lazy, Suspense } from "react";
import { Check, LogOut, Share2, UserPlus } from "lucide-react";
import { getFollowState, getPublicPreProfile, setFollowState } from "../../globe/api/preProfile.api";
import { getPreProfileArtistForSeed } from "../../globe/components/preProfile/demoPreProfileArtist";
import { demoFollowedProfiles } from "../../globe/components/preProfile/demoFollowState";
import type { PlaceRoomState } from "./place.types";
import { MeewavGradeBadge } from "../../grades/MeewavGradeBadge";
import "./room-viewer-host.css";
const PreProfile=lazy(()=>import("../tools/panels/ClassStudentPreProfile"));
export default function RoomViewerHost({room,onLeaveRoom}:{room:PlaceRoomState;onLeaveRoom?:()=>void}) {
  const [following,setFollowing]=useState(false),[pending,setPending]=useState(false),[count,setCount]=useState<number|null>(null),[notice,setNotice]=useState("");
  const [ready,setReady]=useState(room.source === "demo");
  const [profileOpen,setProfileOpen]=useState(false);
  const portraitRef=useRef<HTMLButtonElement>(null);
  useEffect(()=>{let active=true;setReady(room.source === "demo");setFollowing(room.source==="demo"&&demoFollowedProfiles.has(room.host.id));setCount(null);setNotice("");setProfileOpen(false);if(room.source==="live")void Promise.allSettled([getPublicPreProfile(room.host.id),getFollowState(room.host.id)]).then(([profile,follow])=>{if(!active)return;if(profile.status==="fulfilled"&&profile.value)setCount(profile.value.followers_count);if(follow.status==="fulfilled")setFollowing(follow.value.following);setReady(true);});return()=>{active=false;};},[room.host.id,room.source]);
  const followers=room.source==="demo"?getPreProfileArtistForSeed({profileId:room.host.id,displayName:room.host.displayName}).followersLabel:count===null?"Abonnés : —":`${new Intl.NumberFormat("fr-FR",{notation:"compact",maximumFractionDigits:1}).format(count)} abonnés`;
  const follow=async()=>{if(pending)return;setPending(true);setNotice("");try{const next=!following;if(room.source==="demo"){if(next)demoFollowedProfiles.add(room.host.id);else demoFollowedProfiles.delete(room.host.id);setFollowing(next);}else{const result=await setFollowState(room.host.id,next);setFollowing(result.following);const profile=await getPublicPreProfile(room.host.id);if(profile)setCount(profile.followers_count);}}catch{setNotice("Le suivi n’a pas pu être enregistré. Réessayez.");}finally{setPending(false);}};
  const share=async()=>{try{await navigator.clipboard.writeText(window.location.href);setNotice("Lien de la room copié.");}catch{setNotice("Impossible de copier le lien. Réessayez.");}};
  return <div className="room-viewer-host" aria-label="Host et actions du live"><button ref={portraitRef} className="room-viewer-host__identity" type="button" aria-label={`Voir le profil de ${room.host.displayName}`} onClick={()=>setProfileOpen(true)}><img src={room.host.avatarUrl} alt=""/><span><span className="room-viewer-host__name"><strong>{room.host.displayName}</strong><MeewavGradeBadge level={room.host.gradeLevel} size="xs" /></span><small>{followers}</small></span></button><button type="button" className={`room-viewer-host__follow${following?" is-following":""}`} aria-pressed={following} disabled={!ready||pending||!room.currentUserProfile||room.currentUserProfile.id===room.host.id} onClick={()=>void follow()}>{following?<Check/>:<UserPlus/>}<span>{pending?"…":following?"Suivi":"Suivre"}</span></button><button type="button" className="room-viewer-host__share" aria-label="Partager la Room" title="Partager" onClick={()=>void share()}><Share2 /></button>{onLeaveRoom?<button type="button" className="room-viewer-host__leave" aria-label="Quitter la room" title="Quitter" onClick={onLeaveRoom}><LogOut/><span>Quitter</span></button>:null}{notice?<p role="status" onClick={()=>setNotice("")}>{notice}</p>:null}{profileOpen?<Suspense fallback={null}><PreProfile person={{id:room.host.id,name:room.host.displayName,avatarUrl:room.host.avatarUrl,role:room.host.role,microphone:"off",camera:"off",gradeLevel:([1,2,3,4,5,6] as const).find(level=>level===room.host.gradeLevel)}} source={room.source} onClose={()=>setProfileOpen(false)} returnFocusTo={portraitRef.current} {...getRoomPreProfileBounds(portraitRef.current)} /></Suspense>:null}</div>;
}
