import type {PlaceRoomState} from "../place/place.types";
import {useEffect,useRef,useState} from "react";
import {ArrowLeftRight,Users,Mic2,Radio,GraduationCap,AudioLines,DoorOpen,X,ArrowLeft} from "lucide-react";
import {createPortal} from "react-dom";
import {DESTINATIONS,destinationBlock,destinationName,type Experience} from "./switchRoom.domain";
import type {SwitchController} from "./useSwitchRoom";
import {SwitchRoomPreparation} from "./SwitchRoomPreparation";
import "./switch-room.css";
const icons={place:Users,scene:Mic2,cage:Radio,classe:GraduationCap,wave:AudioLines,loge:DoorOpen};
export function SwitchRoomButton({controller:c,enabled,room,onQueueOpen}:{controller:SwitchController;enabled:boolean;room?:PlaceRoomState;onQueueOpen?:(open:boolean)=>Promise<void>}){
 const [open,setOpen]=useState(false),[configuring,setConfiguring]=useState<Experience|null>(null);
 const root=useRef<HTMLDivElement>(null),trigger=useRef<HTMLButtonElement>(null);
 useEffect(()=>{if(!open)return;const pointer=(e:PointerEvent)=>{if(!root.current?.contains(e.target as Node))setOpen(false);};document.addEventListener("pointerdown",pointer);return()=>document.removeEventListener("pointerdown",pointer);},[open]);
 const close=()=>{setOpen(false);trigger.current?.focus();};
 return <div className="switch-room-anchor" ref={root} onKeyDown={e=>{if(e.key==="Escape"){e.stopPropagation();close();}}}><button ref={trigger} type="button" className="switch-room-button" aria-label="Switch Room" aria-expanded={open} aria-controls="switch-room-menu" aria-busy={c.busy} disabled={!enabled||c.busy} onClick={()=>setOpen(!open)}><ArrowLeftRight/><span>{c.busy?"Préparation…":"Switch Room"}</span></button>{open?<section id="switch-room-menu" className="switch-room-popup" aria-label="Choisir une expérience"><header><div><h2>Où continue-t-on le live ?</h2><p>Choisissez une nouvelle expérience. Votre public pourra vous accompagner.</p></div><button type="button" aria-label="Fermer Switch Room" onClick={close}><X/></button></header>{c.error&&!configuring?<p role="alert">{c.error}</p>:null}{!c.state?<p>Le service de changement de room n’est pas disponible. Le live continue normalement.</p>:configuring?<SwitchRoomPreparation key={configuring} room={room} onQueueOpen={onQueueOpen} target={configuring} busy={c.busy} submitError={c.error} onBack={()=>setConfiguring(null)} onSubmit={async config=>{if(await c.commit(configuring,config)){close();setConfiguring(null);}}}/>:<div className="switch-room-grid">{DESTINATIONS.map(d=>{const Icon=icons[d.id];const reason=destinationBlock(c.current,d.id);return <button type="button" key={d.id} disabled={Boolean(reason)||c.busy||!c.fresh} onClick={()=>{if(d.id==="classe"||(d.id!=="place"&&!c.state?.prepared?.includes(d.id)))setConfiguring(d.id);else void c.commit(d.id).then(ok=>{if(ok)close();});}}><Icon/><span><strong>{d.name}</strong><small>{d.description}</small>{reason?<em>{reason}</em>:null}</span></button>;})}</div>}</section>:null}</div>;
}
export function SwitchRoomInvitation({controller:c,hostName}:{controller:SwitchController;hostName:string}){
 const ref=useRef<HTMLDivElement>(null);const [critical,setCritical]=useState(false);
 useEffect(()=>{const check=()=>setCritical(Array.from(document.querySelectorAll<HTMLElement>('[role="dialog"]:not(.switch-room-invitation),[aria-modal="true"]:not(.switch-room-invitation)')).some(dialog=>!dialog.closest('[aria-hidden="true"],[hidden],[inert]')&&getComputedStyle(dialog).display!=="none"&&getComputedStyle(dialog).visibility!=="hidden"));check();const observer=new MutationObserver(check);observer.observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:["aria-modal","role","aria-hidden","hidden","class"]});return()=>observer.disconnect();},[]);
 const shown=c.invite&&!critical;
 useEffect(()=>{if(!shown)return;const previous=document.activeElement as HTMLElement|null;ref.current?.querySelector<HTMLButtonElement>("button")?.focus();return()=>{if(previous?.isConnected)previous.focus({preventScroll:true});};},[shown,c.state?.version]);
 if(!shown)return null;
 const destination=destinationName(c.current);
 return createPortal(<div className="switch-room-veil"><div className="switch-room-invitation" ref={ref} role="dialog" aria-modal="true" aria-labelledby="switch-room-invitation-title" onKeyDown={e=>{if(e.key==="Escape"){e.stopPropagation();c.defer();}if(e.key==="Tab"){const buttons=ref.current?.querySelectorAll<HTMLButtonElement>("button:not(:disabled)");if(!buttons?.length)return;const first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}}><button className="switch-room-close" type="button" aria-label="Pas maintenant, fermer" onClick={c.defer}><X/></button><small>{destinationName(c.state!.from)} → {destination}</small><h2 id="switch-room-invitation-title">On continue dans {destination} ?</h2><p>{hostName} vous invite à poursuivre le live dans {destination}.</p><p>Même live, même chat, nouvelle expérience.</p>{c.error?<p role="alert">{c.error}</p>:null}<button type="button" disabled={c.busy} onClick={()=>void c.accept()}>Continuer dans {destination}</button><button type="button" onClick={c.defer}>Pas maintenant</button></div></div>,document.body);
}
export function SwitchRoomWaiting({controller:c}:{controller:SwitchController}){return <div className="switch-room-waiting" role="status"><strong>Le live continue dans {destinationName(c.current)}.</strong><p>Le lecteur et le chat restent disponibles.</p>{c.error?<p>{c.error}</p>:null}<button type="button" disabled={c.busy||!c.fresh} onClick={()=>void c.accept()}>Rejoindre l’expérience</button>{!c.fresh?<button type="button" onClick={()=>void c.refresh()}>Réessayer</button>:null}</div>;}
