import type { User } from "@supabase/supabase-js";
import { canonicalizeMusicSceneSelection } from "./musicSceneSelection";
import { supabase } from "../../lib/supabaseClient";
import {
  completeOnboarding,
  isUsernameAvailable,
  updatePublicDiscoveryProfile,
} from "./auth.service";
import {
  getCanonicalOnboardingAvatarFile,
  getCanonicalOnboardingRoleLabel,
  getOnboardingAvatarIconId,
  resolveOnboardingRole,
  saveMusicSceneOnboarding,
  type MusicSceneOnboardingPayload,
} from "./musicSceneOnboardingContract";

function asRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === "object" && !Array.isArray(value)
    ? value as Record<string, unknown>
    : {};
}

function text(value: unknown) {
  return typeof value === "string" ? value.trim() : "";
}

function normalizeUsernameCandidate(value: string) {
  const normalized = value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLocaleLowerCase("fr-FR")
    .replace(/[^a-z0-9_]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .slice(0, 20);

  if (/^[a-z0-9_]{3,20}$/.test(normalized)) return normalized;
  const padded = `mw_${normalized || "profil"}`.slice(0, 20);
  return padded.length >= 3 ? padded : "mw_profil";
}

function buildUsernameCandidates(user: User, payload: MusicSceneOnboardingPayload) {
  const metadata = asRecord(user.user_metadata);
  const preferred = [
    text(metadata.username),
    payload.profile.username === "Mon profil" ? "" : payload.profile.username,
    text(metadata.preferred_username),
    user.email?.split("@")[0] ?? "",
    `mw_${user.id.replace(/-/g, "").slice(0, 10)}`,
  ]
    .filter(Boolean)
    .map(normalizeUsernameCandidate);

  const suffix = user.id.replace(/-/g, "").slice(-5);
  const expanded = preferred.flatMap((candidate) => [
    candidate,
    `${candidate.slice(0, Math.max(3, 19 - suffix.length))}_${suffix}`,
  ]);
  return [...new Set(expanded)].filter((candidate) => /^[a-z0-9_]{3,20}$/.test(candidate));
}

function getDisplayName(user: User, payload: MusicSceneOnboardingPayload) {
  const metadata = asRecord(user.user_metadata);
  const candidate = text(metadata.display_name)
    || text(metadata.full_name)
    || text(metadata.name)
    || (payload.profile.username !== "Mon profil" ? payload.profile.username : "")
    || text(metadata.preferred_username)
    || user.email?.split("@")[0]
    || "Mon profil";
  return candidate.trim().slice(0, 80) || "Mon profil";
}

function isUsernameConflict(error: unknown) {
  const record = asRecord(error);
  return record.code === "23505"
    || /username_(?:unavailable|already)|duplicate/i.test(text(record.message));
}

/**
 * Persists the source-of-truth Auth/Globe scene without changing its visual
 * arrival contract. Exact coordinates remain in the owner-only location row;
 * public discovery only receives canonical scene identifiers and a coarse
 * marker generated by the database.
 */
export async function persistMusicSceneProfile(
  user: User,
  payload: MusicSceneOnboardingPayload,
) {
  payload = { ...payload, ...await canonicalizeMusicSceneSelection(payload.city, payload.scene) };
  const [longitude, latitude] = payload.scene.center;
  if (
    !Number.isFinite(longitude)
    || !Number.isFinite(latitude)
    || longitude < -180
    || longitude > 180
    || latitude < -90
    || latitude > 90
  ) {
    throw new Error("invalid_scene_coordinates");
  }

  const displayName = getDisplayName(user, payload);
  const canonicalAvatarFile = getCanonicalOnboardingAvatarFile(payload.profile.avatarFile);
  const canonicalAvatarIconId = getOnboardingAvatarIconId(canonicalAvatarFile);
  const selectedRole = resolveOnboardingRole(canonicalAvatarFile, payload.profile.role);
  const candidates = buildUsernameCandidates(user, payload);
  let username = candidates[0] ?? `mw_${user.id.replace(/-/g, "").slice(0, 10)}`;
  let onboardingResult: Awaited<ReturnType<typeof completeOnboarding>> | null = null;
  let lastError: unknown = null;

  for (const candidate of candidates) {
    try {
      if (!await isUsernameAvailable(candidate)) continue;
      username = candidate;
      onboardingResult = await completeOnboarding({
        username,
        displayName,
        avatarStyleKey: canonicalAvatarIconId,
        primaryRoleKey: selectedRole.key,
        city: payload.city.result.label,
        countryCode: "FR",
        countryName: "France",
        street: null,
        postalCode: null,
        latitude,
        longitude,
        isGhostMode: !payload.profile.visible,
        showOnPublicProfile: payload.profile.visible,
      });
      lastError = null;
      break;
    } catch (error) {
      lastError = error;
      if (!isUsernameConflict(error)) throw error;
    }
  }

  if (!onboardingResult) throw lastError ?? new Error("username_unavailable");

  await updatePublicDiscoveryProfile({
    sceneName: payload.scene.label,
    communeCode: payload.city.communeCode,
    zoneId: payload.scene.zoneId,
    districtName: payload.scene.label,
    avatarIconId: canonicalAvatarIconId,
  });

  const canonicalProfile = asRecord(onboardingResult.profile);
  const canonicalRoleKey = text(canonicalProfile.primary_role_key) || selectedRole.key;
  const canonicalRoleLabel = canonicalRoleKey === selectedRole.key
    ? selectedRole.label
    : getCanonicalOnboardingRoleLabel(canonicalRoleKey);
  const authoritativeMetadata = {
    ...asRecord(user.user_metadata),
    username,
    display_name: displayName,
    full_name: displayName,
    avatar_name: canonicalAvatarFile,
    avatar_style_key: canonicalAvatarIconId,
    avatar_icon_id: canonicalAvatarIconId,
    artist_type: canonicalRoleLabel,
    primary_role_key: canonicalRoleKey,
    city: payload.city.result.label,
    country: "France",
    country_code: "FR",
    commune_code: payload.city.communeCode,
    zone_id: payload.scene.zoneId,
    district_id: payload.scene.zoneId,
    district_name: payload.scene.label,
    scene_name: payload.scene.label,
    scene_source: payload.scene.source,
    scene_geography_version: 'vinyl-v1',
    // Session metadata is not the exact-location source of truth. The RPC above
    // has already stored exact coordinates in profile_locations_private.
    longitude: Math.round(longitude * 100) / 100,
    latitude: Math.round(latitude * 100) / 100,
    scene_center_version: 2,
    is_ghost_mode: !payload.profile.visible,
    show_on_public_profile: payload.profile.visible,
    onboarding_completed: true,
  };
  const { error: metadataError } = await supabase.auth.updateUser({ data: authoritativeMetadata });
  if (metadataError) throw metadataError;

  const finalizedPayload: MusicSceneOnboardingPayload = {
    ...payload,
    auth: undefined,
    createdAt: Date.now(),
    profile: {
      ...payload.profile,
      profileId: user.id,
      username: displayName,
      role: canonicalRoleLabel,
      avatarFile: canonicalAvatarFile,
      avatarIconId: canonicalAvatarIconId,
    },
  };
  saveMusicSceneOnboarding(finalizedPayload);
  return finalizedPayload;
}
