import type { RoomVotingPolicy } from "../voting/roomVoting";
import type { RoomPerson } from "./roomTools.types";

/** Immutable copy of the sequencer configuration belonging to this live session. */
export type CageCompetitionConfig = {
  version: 1;
  title: string;
  discipline: string;
  format: "tournament" | "championship" | "open-mic" | "open-mic-battle";
  participantCount: number;
  rosterMode: "prepared" | "first-eligible" | "manual" | "random";
  rosterProfileIds: string[];
  championshipDays?: number;
  productionTeam?: "solo" | "regisseur";
  templateId?: string;
  rules: {
    performanceMode: "successive" | "alternating" | "simultaneous";
    rounds: number;
    passageDurationSeconds: number;
    votingDurationSeconds: number;
    votingMode: "public" | "jury" | "mixed";
    tieBreak: "sudden-death" | "replay";
    allowByes: boolean;
    allowFormatReduction: boolean;
    allowReplacement: boolean;
    disconnectGraceSeconds: number;
    noShowGraceSeconds: number;
    openMicFeedback?: "appreciation" | "scored" | "none";
  };
};
export type CageCompetitionStatus = "PREPARING" | "CHECK_IN" | "SEEDED" | "LOCKED" | "RUNNING" | "PAUSED" | "FINAL" | "COMPLETED" | "CANCELLED";
export type CageParticipantStatus = "WAITING" | "SELECTED" | "GREENHOUSE" | "READY" | "CALLED" | "ON_STAGE" | "PERFORMING" | "PERFORMED" | "ADVANCED" | "ELIMINATED" | "NO_SHOW" | "FORFEIT" | "DISQUALIFIED";
export type CageMatchStatus = "WAITING" | "CALLING" | "GREENHOUSE" | "READY" | "ON_STAGE" | "IN_PROGRESS" | "PAUSED" | "READY_FOR_VOTE" | "VOTING" | "TIE_BREAK" | "RESOLVED" | "CLOSED" | "POSTPONED";
export type CageReadiness = { camera: boolean; microphone: boolean; connection: boolean; mixer: boolean; permissions: boolean };
export type TournamentParticipant = {
  id: string;
  person: RoomPerson;
  present: boolean;
  registered: boolean;
  eligible: boolean;
  seed: number | null;
  status: CageParticipantStatus;
  readiness: CageReadiness;
  guestStatus: "waiting" | "backstage" | "on_stage" | "audience";
  graceEndsAt: string | null;
  replacesId?: string;
};
export type CagePerformanceStep = { id: string; label: string; side: "A" | "B" | "BOTH"; durationSeconds: number };
export type CageCompetitionMatch = {
  id: string;
  round: number;
  order: number;
  label: string;
  participantAId: string | null;
  participantBId: string | null;
  sourceA: { matchId: string; kind: "winner" } | null;
  sourceB: { matchId: string; kind: "winner" } | null;
  status: CageMatchStatus;
  stepIndex: number;
  steps: CagePerformanceStep[];
  timer: { startedAt: string | null; elapsedSeconds: number };
  vote: { votingMode?: "public" | "mixed" | "jury"; weightedScoreA?: number; weightedScoreB?: number; roundId: string; open: boolean; endsAt: string | null; ballots: Record<string, "A" | "B">; scoreA: number; scoreB: number; closedAt: string | null } | null;
  winnerId: string | null;
  incident: { participantId: string; reason: string; openedAt: string; graceEndsAt: string } | null;
  resolution?: "public" | "bye" | "forfeit";
  tieBreakRound?: number;
};
export type CageCompetitionRuntime = {
  votingPolicy?: RoomVotingPolicy;
  version: 1;
  config: CageCompetitionConfig;
  status: CageCompetitionStatus;
  participants: TournamentParticipant[];
  matches: CageCompetitionMatch[];
  /** Open Mic is a running order of individual performances, never a duel bracket. */
  openMicEntries?: CageOpenMicPassage[];
  activeEntryId?: string | null;
  preparedEntryId?: string | null;
  feedbackEntryId?: string | null;
  lockedAt: string | null;
  activeMatchId: string | null;
  preparedMatchId: string | null;
  autoRegie: boolean;
  publicBracketVisible: boolean;
  publicResults?: { matchId: string | null } | null;
  journal: Array<{ id: string; at: string; actorId: string; action: string; matchId: string | null; detail: string }>;
  processedCommandIds: string[];
  commandReceipts?: Record<string, { actorId: string; action: CageCompetitionAction; payload: string }>;
};
export type CageOpenMicPassage = {
  id: string;
  order: number;
  participantId: string;
  status: "WAITING" | "GREENHOUSE" | "READY" | "ON_STAGE" | "IN_PROGRESS" | "PAUSED" | "PERFORMED" | "POSTPONED" | "SKIPPED";
  timer: { startedAt: string | null; elapsedSeconds: number };
  durationSeconds: number;
  incident: { participantId: string; reason: string; openedAt: string; graceEndsAt: string } | null;
  feedback?: { mode: "appreciation" | "scored"; open: boolean; endsAt: string | null; closedAt: string | null; responses: Record<string, number>; count: number; total: number; average: number | null };
};
export type CageOpenMicAction = "openmic.schedule" | "openmic.move" | "openmic.remove" | "openmic.prepare" | "openmic.promote" | "openmic.start" | "openmic.pause" | "openmic.resume" | "openmic.end" | "openmic.incident" | "openmic.restart" | "openmic.report" | "openmic.feedback.open" | "openmic.feedback.cast" | "openmic.feedback.close";
export type CageCompetitionAction = CageOpenMicAction | "broadcast.results" | "competition.configure" | "broadcast.bracket" | "roster.select" | "roster.remove" | "roster.move" | "bracket.generate" | "bracket.reset" | "bracket.lock" | "regie.prepare" | "regie.ready" | "regie.promote" | "regie.auto" | "match.start" | "match.pause" | "match.resume" | "match.end-step" | "match.incident" | "match.restart" | "vote.open" | "vote.cast" | "vote.close" | "participant.recall" | "participant.grace" | "participant.replace" | "participant.forfeit" | "match.report";
export type CageCompetitionPayload = {
  format?: CageCompetitionConfig["format"];
  participantCount?: number;
  openMicFeedback?: "appreciation" | "scored" | "none";
  confirmReset?: boolean;
  participantIds?: string[];
  participantId?: string;
  replacementId?: string;
  toSeed?: number;
  mode?: "random" | "manual" | "first-eligible";
  shortage?: "wait" | "byes" | "reduce";
  matchId?: string;
  readiness?: CageReadiness;
  enabled?: boolean;
  reason?: string;
  choice?: "A" | "B";
  accountId?: string;
  entryId?: string;
  direction?: -1 | 1;
  score?: 1 | 2 | 3 | 4 | 5;
};
export type CageCompetitionCommand = {
  type: "cage.competition.command";
  action: CageCompetitionAction;
  payload?: CageCompetitionPayload;
  idempotencyKey: string;
  expectedRevision: number;
  expectedMatchId?: string;
  expectedStepIndex?: number;
  expectedEntryId?: string;
};
